; ---------------------------------------------------------------------
; asmtab.asm -- the on-machine assembler's mnemonic table.
;
; GENERATED by tools/mkasmtab.py from tools/opcodes.py. Do not edit:
; sim/test_asm.py regenerates this and fails if it differs, which is
; what keeps one source of truth for the encoding (AGENTS.md).
;
; Three key bytes -- first, second and last character of the mnemonic
; -- then a family in the high nibble and its base field in the low.
; The family names below are mirrored by the encoders in sw/asm.asm.
; ---------------------------------------------------------------------

AF_NONE   = 0
AF_ALU    = 1
AF_ALUDUP = 2
AF_ALUIM1 = 3
AF_BR     = 4
AF_UNARY  = 5
AF_BIT    = 6
AF_LDST   = 7
AF_W16    = 8
AF_STK    = 9
AF_JMP    = 10
AF_MUL    = 11
AF_XOR    = 12

AMENT   = 4                     ; bytes per entry
AMCOUNT = 73

amtab:
        .byte 'M','O','V',(AF_ALU<<4)|0        ; MOV
        .byte 'A','D','D',(AF_ALU<<4)|1        ; ADD
        .byte 'A','D','C',(AF_ALU<<4)|2        ; ADC
        .byte 'S','U','B',(AF_ALU<<4)|3        ; SUB
        .byte 'S','B','C',(AF_ALU<<4)|4        ; SBC
        .byte 'A','N','D',(AF_ALU<<4)|5        ; AND
        .byte 'O','R','R',(AF_ALU<<4)|6        ; OR
        .byte 'C','M','P',(AF_ALU<<4)|7        ; CMP
        .byte 'X','O','R',(AF_XOR<<4)|0        ; XOR
        .byte 'B','R','A',(AF_BR<<4)|0        ; BRA
        .byte 'B','N','V',(AF_BR<<4)|1        ; BNV
        .byte 'B','E','Q',(AF_BR<<4)|2        ; BEQ
        .byte 'B','N','E',(AF_BR<<4)|3        ; BNE
        .byte 'B','C','S',(AF_BR<<4)|4        ; BCS
        .byte 'B','C','C',(AF_BR<<4)|5        ; BCC
        .byte 'B','M','I',(AF_BR<<4)|6        ; BMI
        .byte 'B','P','L',(AF_BR<<4)|7        ; BPL
        .byte 'B','V','S',(AF_BR<<4)|8        ; BVS
        .byte 'B','V','C',(AF_BR<<4)|9        ; BVC
        .byte 'B','H','I',(AF_BR<<4)|10        ; BHI
        .byte 'B','L','S',(AF_BR<<4)|11        ; BLS
        .byte 'B','G','E',(AF_BR<<4)|12        ; BGE
        .byte 'B','L','T',(AF_BR<<4)|13        ; BLT
        .byte 'B','G','T',(AF_BR<<4)|14        ; BGT
        .byte 'B','L','E',(AF_BR<<4)|15        ; BLE
        .byte 'B','H','S',(AF_BR<<4)|4        ; BHS
        .byte 'B','L','O',(AF_BR<<4)|5        ; BLO
        .byte 'B','Z','Z',(AF_BR<<4)|2        ; BZ
        .byte 'B','N','Z',(AF_BR<<4)|3        ; BNZ
        .byte 'B','N','N',(AF_BR<<4)|6        ; BN
        .byte 'B','P','P',(AF_BR<<4)|7        ; BP
        .byte 'C','L','R',(AF_ALUDUP<<4)|3        ; CLR
        .byte 'T','S','T',(AF_ALUDUP<<4)|6        ; TST
        .byte 'S','H','L',(AF_ALUDUP<<4)|1        ; SHL
        .byte 'R','O','L',(AF_ALUDUP<<4)|2        ; ROL
        .byte 'I','N','C',(AF_ALUIM1<<4)|1        ; INC
        .byte 'D','E','C',(AF_ALUIM1<<4)|3        ; DEC
        .byte 'N','O','T',(AF_UNARY<<4)|0        ; NOT
        .byte 'N','E','G',(AF_UNARY<<4)|1        ; NEG
        .byte 'S','W','P',(AF_UNARY<<4)|2        ; SWAP
        .byte 'S','H','R',(AF_UNARY<<4)|3        ; SHR
        .byte 'S','A','R',(AF_UNARY<<4)|4        ; SAR
        .byte 'R','O','R',(AF_UNARY<<4)|5        ; ROR
        .byte 'B','S','T',(AF_BIT<<4)|0        ; BSET
        .byte 'B','C','R',(AF_BIT<<4)|1        ; BCLR
        .byte 'B','T','T',(AF_BIT<<4)|2        ; BTST
        .byte 'N','O','P',(AF_NONE<<4)|0        ; NOP
        .byte 'H','A','T',(AF_NONE<<4)|1        ; HALT
        .byte 'R','E','T',(AF_NONE<<4)|2        ; RET
        .byte 'R','E','I',(AF_NONE<<4)|3        ; RETI
        .byte 'E','I','I',(AF_NONE<<4)|4        ; EI
        .byte 'D','I','I',(AF_NONE<<4)|5        ; DI
        .byte 'C','L','C',(AF_NONE<<4)|6        ; CLC
        .byte 'S','E','C',(AF_NONE<<4)|7        ; SEC
        .byte 'B','R','K',(AF_NONE<<4)|8        ; BRK
        .byte 'C','L','V',(AF_NONE<<4)|9        ; CLV
        .byte 'L','D','D',(AF_LDST<<4)|0        ; LD
        .byte 'S','T','T',(AF_LDST<<4)|1        ; ST
        .byte 'L','D','W',(AF_W16<<4)|0        ; LDW
        .byte 'S','T','W',(AF_W16<<4)|1        ; STW
        .byte 'M','O','W',(AF_W16<<4)|2        ; MOVW
        .byte 'A','D','W',(AF_W16<<4)|3        ; ADDW
        .byte 'S','U','W',(AF_W16<<4)|4        ; SUBW
        .byte 'L','E','A',(AF_W16<<4)|5        ; LEA
        .byte 'I','N','W',(AF_W16<<4)|6        ; INCW
        .byte 'D','E','W',(AF_W16<<4)|7        ; DECW
        .byte 'P','U','W',(AF_W16<<4)|8        ; PUSHW
        .byte 'P','O','W',(AF_W16<<4)|9        ; POPW
        .byte 'P','U','H',(AF_STK<<4)|0        ; PUSH
        .byte 'P','O','P',(AF_STK<<4)|1        ; POP
        .byte 'J','M','P',(AF_JMP<<4)|0        ; JMP
        .byte 'C','A','L',(AF_JMP<<4)|1        ; CALL
        .byte 'M','U','L',(AF_MUL<<4)|0        ; MUL
        .byte 0

; No-operand instructions: prefix ($00 for page 1) and opcode.
amnone:
        .byte $00,$20                 ; NOP
        .byte $00,$21                 ; HALT
        .byte $00,$22                 ; RET
        .byte $00,$23                 ; RETI
        .byte $00,$24                 ; EI
        .byte $00,$25                 ; DI
        .byte $00,$26                 ; CLC
        .byte $00,$27                 ; SEC
        .byte $00,$2E                 ; BRK
        .byte $2F,$E2                 ; CLV

