' ---------------------------------------------------------------------
' basic.bas -- COOL8 BASIC, the system.
'
' One screen, a cursor, and a Return key. Type a line and it runs; put a
' number in front and it is stored instead. That is the whole model, and
' it is the Commodore one because it is the right one: no modes, no
' panes, nothing to switch between.
'
' ## The screen is the buffer
'
' There is no edit buffer. LIST puts lines on the screen; you move the
' cursor onto one, type over it, and press Return anywhere on the row.
' The system reads the whole 80-character row back, and if it starts
' with a number, that line replaces whatever line had that number.
'
' Editing a program and entering one are therefore the same operation,
' which is why this needs a fraction of the machinery a separate editor
' does.
'
' ## Where things live (docs/04-system.md owns the map)
'
'   $0200-$7FFF   program text, then compiled code, variables, strings
'   $8000-$9FFF   the screen: 128x32 cells at stride 256, 80x30 shown
'   $A000-$FDFF   this program
'
' The map must be 8 KB aligned -- the row wrap is a mask, not a compare
' -- so the screen sits at $8000 or $A000 and nowhere between. It is at
' $8000 because that is where mode 0's preset, the boot ROM's banner and
' the monitor already put it; the editor used to override the preset to
' $A000, and that override was the only thing forcing this program up to
' $C000. Moving it back buys 8 KB of system space for 8 KB of program
' space, and leaves one screen base instead of three.
'
' Program text grows up from $0200 and is kept in ascending line order,
' tokenised: keywords become one byte each, which measured 23 % smaller
' than storing the text.
' ---------------------------------------------------------------------

EXTERN s_putn
EXTERN s_number
EXTERN TOKTAB
EXTERN RUNTAB
EXTERN iisr
EXTERN inmi
EXTERN irring
EXTERN irhead
EXTERN irtail
EXTERN ibreak
EXTERN MSGFREE
EXTERN MSGKFREE

CONST SCREEN  = $8000
CONST PROG    = $0200           ' program text starts here
CONST MEMTOP  = $7FFF
' The user area really ends here. RUN puts the string accumulator at
' $7F00 and the CALL stack at $7EE0, so the top 288 bytes are not a
' program's to fill. FREE reported MEMTOP - progend, and a program
' that believed it would have run into both.
' $7DE8, not $7EDF: the system storage region sits at $7DE9-$7EDF, and
' the user area ends one byte below its floor. The floor follows the
' claims -- 247 bytes of them -- and `tools/memmap.py --check` refuses a
' value here that disagrees with the arithmetic, so this cannot drift
' into the region the way every hand-written free-space figure in this
' project has drifted before ([D67]).
CONST USERTOP = $7C9B

' The I/O registers, generated by tools/ioregs.py from the Verilog that
' decodes them -- the same source sw/io.asm comes from. They were eight
' CONSTs written out here, which is eight more places the page's address
' was written down ([D67]).
'
' **CONSTs and not EXTERNs, and the difference is 89 bytes.** A CONST
' folds at compile time, so `POKE VID_MODE, x` assembles a literal
' address; an EXTERN is a link-time symbol the compiler cannot fold, and
' switching these eight to EXTERN grew the image from 23,541 to 23,630.
' Generating the constants keeps the folding and still writes the
' address down once.
INCLUDE "io.bas"

' attributes: foreground in the low nibble, background in the high
CONST A_TEXT = $07
CONST A_BANR = $0B
CONST A_HEAD = $08
CONST A_VAL  = $0F
CONST A_FREE = $0E
CONST A_ERR  = $04

' key codes above 255 -- the decoder returns these for named keys
CONST K_UP    = 256
CONST K_DOWN  = 257
CONST K_LEFT  = 258
CONST K_RIGHT = 259
CONST K_HOME  = 260
CONST K_END   = 261
CONST K_DEL   = 262
CONST K_INS   = 263

' A numeric literal, stored as two binary bytes rather than as digits.
' Without it a loop re-parses decimal on every iteration, which is most
' of what makes an interpreted FOR slow. Appended, so saved programs
' keep working -- TOKTAB order is frozen.
CONST T_LIT   = $A4
CONST T_REM   = $C5
' Three addresses in the system storage region that this file reaches by
' number. Each is named `<name>` in sw/zp.asm, and `tools/memmap.py
' --check` refuses a CONST here whose name matches a claim there and
' whose address does not -- which is what caught `IRST = $FF86` still
' pointing at the old workspace page after the I/O page moved on top of
' it. The symptom was the editor calling doreset() on every pass of the
' key loop, because $FF86 had become a flash register that reads
' non-zero ([D67]).
'
' CONSTs and not EXTERNs for the reason io.bas gives: a CONST folds.
CONST IRST    = $7E6F           ' the NMI handler's restart flag
CONST FRAMES  = $7E0F           ' the frame counter, two bytes
CONST DIRBUF  = $7E70           ' the staged direct line, a whole record

DIM cx AS BYTE                  ' cursor column on screen
DIM cy AS BYTE                  ' cursor row on screen
DIM vtop AS BYTE                ' which map row is displayed at the top

' The visible geometry, in zero page so nothing pays to ask. The cell
' map at $8000 stays 128x32 stride 256 in every mode -- the TRUTH the
' editor edits -- and these describe only what the current mode shows
' and how the mirror paints it. setgeom() fills them whenever the
' editor regains the machine.
DIM cols AS BYTE AT $00A4       ' visible columns: 80, 40 or 32
DIM rows AS BYTE AT $00A5       ' visible rows: 30 or 24
DIM gkind AS BYTE AT $00A6      ' 0 text, 1 tiles, 2 bitmap
DIM curph AS BYTE AT $00A7      ' soft-cursor blink phase, 0 = off
DIM rpl AS BYTE AT $00A8        ' rows a full logical line spans
DIM bpc AS BYTE AT $00A9        ' bitmap bytes per cell row (= bpp)
DIM gbase AS CARD AT $00AA      ' bitmap display base, tracked
DIM gs8 AS CARD AT $00AC        ' bitmap stride * 8: one cell row down
DIM glim AS BYTE AT $00AE       ' base high byte that forces a repaint
' Row r continues the logical line above it -- the C64's $D9 link
' table, one byte a row instead of one bit.
DIM cont(31) AS BYTE AT $00B0
DIM blb AS CARD AT $00D0        ' frame count at the last blink flip
DIM bfa AS CARD AT $00D2        ' bglyph: font row address
DIM bva AS CARD AT $00D4        ' bglyph: framebuffer cell address
DIM binv AS BYTE AT $00D6       ' bglyph: $FF to draw inverted
DIM grow AS BYTE AT $00D7       ' bglyph: font rows per glyph, 8 or 16
DIM bstr AS CARD AT $00D8       ' bglyph: the mode's stride
' CARD, not INT: $9FFF is 40,959 and as a signed value that is
' negative, which makes every bounds check on an address backwards.
DIM progend AS CARD             ' first free byte of program text
DIM lbuf(127) AS BYTE           ' the line being worked on, as text
DIM llen AS BYTE
DIM tbuf(127) AS BYTE           ' the same line, tokenised
DIM tlen AS BYTE

' ---------------------------------------------------------------------
' Screen addressing.
'
' Scrolling moves the origin rather than the memory: the fetch engine
' wraps the row pointer inside stride*32, so displayed row r is map row
' (vtop + r) AND 31 and scrolling is one register write.
' ---------------------------------------------------------------------

FUNCTION rowaddr(r AS INT) AS CARD
  RETURN SCREEN + (((vtop + r) AND 31) << 8)
END FUNCTION

' The geometry for whatever mode the machine is in RIGHT NOW -- called
' whenever the editor regains control, because a program or a direct
' MODE leaves the mode exactly as it set it. Nothing is restored any
' more: mode, palette, sprites and sound all stay, and the editor
' simply works wherever it wakes up.
SUB setgeom()
  DIM m AS BYTE
  m = PEEK(VID_MODE) AND 15
  cols = 80
  rows = 30
  gkind = 2
  grow = 8
  IF m = 0 THEN
    gkind = 0
  END IF
  IF m = 1 THEN
    gkind = 0
    cols = 40
  END IF
  IF m = 2 THEN
    gkind = 1
    cols = 40
    CALL tilefont()
  END IF
  IF m = 4 THEN
    cols = 40
  END IF
  IF m = 5 THEN
    cols = 32
    rows = 24
  END IF
  IF m = 6 THEN
    cols = 32
  END IF
  rpl = 1
  IF cols = 40 THEN
    rpl = 2
  END IF
  IF cols = 32 THEN
    rpl = 3
  END IF
  IF gkind = 0 THEN
    POKE CUR_CTRL, $17          ' style 3, the C64's reverse blink, in
  ELSE                          '   silicon; rate 2, 32 frames a phase
    POKE CUR_CTRL, 0            ' soft cursor, drawn by curdrw
  END IF
  IF gkind = 2 THEN
    bpc = 4                     ' modes 4 and 5
    IF m = 3 THEN
      bpc = 1
      ' Mode 3 is the one bitmap mode without line doubling, so its
      ' cells are 16 raster lines and the console uses the 8x16 font
      ' the boot stub seeds at $F600 -- the same Spleen face text
      ' mode reads from its ROM, at full height. 30 rows x 16 = 480:
      ' the whole screen, where 8-line cells covered half of it.
      grow = 16
      ' mode 3's two colours: entry 1 goes white, or the editor
      ' writes CGA blue on black -- the one palette touch setgeom
      ' allows itself, and only on the way INTO the 1 bpp console
      POKE PAL_IDX, 1
      POKE PAL_DATA, $0F
      POKE PAL_DATA, $FF
    END IF
    IF m = 6 THEN
      bpc = 8
    END IF
    gbase = PEEK(VID_BASE_L) + (PEEK(VID_BASE_H) << 8)
    gs8 = (PEEK(VID_STRIDE_L) + (PEEK(VID_STRIDE_H) << 8)) << 3
    ' the blit's row step is one raster line -- the hardware stride --
    ' set once here, not per glyph: bput leaves bstr alone
    bstr = gs8 >> 3
    IF m = 3 THEN gs8 = gs8 + gs8
    ' repaint when the scrolled window would reach the fonts, whose
    ' floor is the 8x16 set at $F600
    glim = ($F600 - rows * gs8) >> 8
  END IF
  curph = 0
END SUB

' Mode 2's console: the 96 GTEXT glyphs expanded once into 4 bpp tile
' patterns at VRAM $1000, and palette bank 2 seeded as bank 0's
' inverse pair so the cursor can blink by flipping one attribute
' nibble. PAT_BASE points at the set and the map is the mirror.
SUB tilefont()
  DIM ch AS INT
  DIM k AS BYTE
  DIM fb AS BYTE
  DIM fa AS CARD
  POKE VID_PAT_L, 0
  POKE VID_PAT_H, $10
  POKE VRAM_ADDR_L, 0
  POKE VRAM_ADDR_H, $10
  ch = 0
  DO WHILE ch < 96
    ' the blitter does the expansion: 4 bpp straight into the
    ' pattern slot, no inversion, stride 4 -- rows are contiguous
    bfa = $FC00 + (ch << 3)
    bva = $1000 + (ch << 5)
    binv = 0
    bstr = 4
    bpc = 4
    ASM
        CALL bglyph
    END ASM
    ch = ch + 1
  LOOP
  ' bank 2 = bank 0's inverse pair: entry 32 white, entry 47 black.
  POKE PAL_IDX, 32
  POKE PAL_DATA, $0F
  POKE PAL_DATA, $FF
  POKE PAL_IDX, 47
  POKE PAL_DATA, $00
  POKE PAL_DATA, $00
END SUB

' The console: every write lands in the cell map (the truth), and the
' mirror repeats it wherever the current mode actually looks -- the
' tile map in mode 2, the framebuffer in the bitmap modes. Text modes
' need no mirror: the engine reads the cells itself.
SUB putat(r AS INT, c AS INT, ch AS INT, a AS INT)
  DIM p AS CARD
  IF c > cols - 1 THEN
    RETURN
  END IF
  p = rowaddr(r) + c + c
  POKE p, ch
  POKE p + 1, a
  ' the mirror covers only the VISIBLE rows: the cell map's rows 30
  ' and 31 exist for the scroll wrap, and in mode 6 their mirrored
  ' addresses land on the font at $FC00 -- CLS ate it, once
  IF gkind <> 0 THEN
    IF r < rows THEN
      IF gkind = 1 THEN
        CALL tput(r, c, ch, 0)
      ELSE
        CALL bput(r, c, ch, 0)
      END IF
    END IF
  END IF
END SUB

' One mode-2 map entry: the glyph as a tile, the attribute's low
' nibble picking palette bank 0 (normal) or 2 (the inverse pair the
' cursor blinks with). The map mirrors the cell map's circular rows.
SUB tput(r AS INT, c AS INT, ch AS INT, inv AS INT)
  DIM a AS CARD
  IF ch < 32 THEN
    ch = 32
  END IF
  a = (((vtop + r) AND 31) << 7) + c + c
  POKE VRAM_ADDR_L, a AND 255
  POKE VRAM_ADDR_H, a >> 8
  POKE VRAM_DATA, ch - 32
  POKE VRAM_DATA, inv + inv         ' bank 0 normal, bank 2 the inverse
END SUB

' One glyph into the framebuffer, expanded from the 1 bpp GTEXT font
' at VRAM $FC00 to the mode's depth. inv draws it reversed -- the
' cursor. Fg is the depth's brightest, bg 0, so invert is complement.
' BASIC computes the two addresses; the row loop is hand assembly on
' zero-page scratch, because compiled bit-twiddling was 400 bytes the
' ceiling did not have.
SUB bput(r AS INT, c AS INT, ch AS INT, inv AS INT)
  IF ch < 32 THEN
    ch = 32
  END IF
  ' grow picks the font with the row count: the 8x16 set at $F600 for
  ' mode 3's undoubled cells, the 8x8 at $FC00 everywhere else. bstr,
  ' the one-raster-line row step, was set by setgeom; tilefont sets
  ' its own and the tile console never comes here.
  IF grow = 16 THEN
    bfa = $F600 + ((ch - 32) << 4)
  ELSE
    bfa = $FC00 + ((ch - 32) << 3)
  END IF
  bva = gbase + r * gs8 + c * bpc
  binv = 0
  IF inv <> 0 THEN
    binv = 255
  END IF
  ASM
        CALL bglyph
  END ASM
END SUB

FUNCTION getat(r AS INT, c AS INT) AS INT
  RETURN PEEK(rowaddr(r) + c + c)
END FUNCTION

SUB clearrow(r AS INT)
  DIM c AS BYTE
  c = 0
  DO WHILE c < cols
    CALL putat(r, c, 32, A_TEXT)
    c = c + 1
  LOOP
END SUB

SUB cls()
  DIM r AS BYTE
  r = 0
  DO WHILE r < 32
    CALL clearrow(r)
    cont(r) = 0
    r = r + 1
  LOOP
  cx = 0
  cy = 0
  CALL showcur()
END SUB

' The soft cursor: the cell drawn inverted, or restored. Text modes
' never come here -- the hardware cursor's style 3 IS the C64's
' reverse blink, in silicon.
SUB curdrw(on AS INT)
  IF gkind = 1 THEN
    CALL tput(cy, cx, getat(cy, cx), on)
  ELSE
    CALL bput(cy, cx, getat(cy, cx), on)
  END IF
END SUB

' Any movement or edit calls this with the cursor already at its new
' place: the hardware follows in text modes, the soft cursor restarts
' its phase elsewhere.
SUB showcur()
  IF gkind = 0 THEN
    POKE CUR_X, cx
    POKE CUR_Y, cy
  END IF
END SUB


' Scroll one row: the link table shifts with the rows, then the base
' moves -- one register write in the text and tile modes, and in the
' bitmap modes a tracked base that repaints from the cell map when
' the window nears the font at $FC00 (about one repaint in sixty).
SUB scroll()
  DIM r AS BYTE
  DIM a AS CARD
  r = 0
  DO WHILE r < 31
    cont(r) = cont(r + 1)
    r = r + 1
  LOOP
  cont(31) = 0
  vtop = (vtop + 1) AND 31
  IF gkind = 0 THEN
    POKE VID_BASE_H, (SCREEN >> 8) + vtop
  ELSE
    IF gkind = 1 THEN
      a = vtop << 7
    ELSE
      gbase = gbase + gs8
      IF (gbase >> 8) >= glim THEN
        gbase = 0
        CALL brepaint()
      END IF
      a = gbase
    END IF
    POKE VID_BASE_L, a AND 255
    POKE VID_BASE_H, a >> 8
  END IF
  CALL clearrow(rows - 1)
END SUB

' Every cell redrawn from the truth -- the bitmap window reset.
SUB brepaint()
  DIM r AS BYTE
  DIM c AS BYTE
  r = 0
  DO WHILE r < rows
    c = 0
    DO WHILE c < cols
      CALL bput(r, c, getat(r, c), 0)
      c = c + 1
    LOOP
    r = r + 1
  LOOP
END SUB

SUB newline()
  DIM k AS BYTE
  cx = 0
  CALL dnrow()
  ' A new logical line starts here -- and any STALE chain hanging
  ' below it is cut, or a later Return would drag leftover screen
  ' text into the line it reads. (Found the classic way: break a
  ' printing loop, type LIST, get the list and then ?SYNTAX.)
  cont(cy) = 0
  k = cy
  DO WHILE k < rows - 1
    IF cont(k + 1) = 0 THEN
      EXIT DO
    END IF
    cont(k + 1) = 0
    k = k + 1
  LOOP
  CALL showcur()
END SUB

' Cursor down a row, column kept -- the C64's rule: at the bottom the
' screen scrolls, and the cursor never wraps to the top.
SUB dnrow()
  IF cy < rows - 1 THEN
    cy = cy + 1
  ELSE
    CALL scroll()
  END IF
END SUB

SUB emit(ch AS INT)
  CALL putat(cy, cx, ch, A_TEXT)
  IF cx < cols - 1 THEN
    cx = cx + 1
  ELSE
    ' typing past the row's end: onto the next row, linked into this
    ' logical line while it is still short of 80 characters
    IF cy - lstart(cy) + 1 < rpl THEN
      cx = 0
      CALL dnrow()
      cont(cy) = 1
    ELSE
      CALL newline()
    END IF
  END IF
  CALL showcur()
END SUB

SUB puts(s AS CARD)
  DIM c AS BYTE
  DO
    c = PEEK(s)
    IF c = 0 THEN
      EXIT DO
    END IF
    CALL emit(c)
    s = s + 1
  LOOP
END SUB

' putn and tenth were here. They are sw/ed.asm's s_putn now,
' hand-written: the same digits, out of udiv16 rather than
' five subtracted constants. See docs/13-basic.md section 10.

' ---------------------------------------------------------------------
' The keyboard.
'
' PS/2 Set 2 scancodes are what a keyboard sends, and are the only way
' to see a cursor key or Home. The serial console is decoded from ANSI
' into the same codes, so nothing above this cares which wire a key
' arrived on.
' ---------------------------------------------------------------------

FUNCTION getkey() AS INT
  DIM c AS INT
  DO
    c = serialkey()
    IF c <> 0 THEN
      IF curph <> 0 THEN        ' any key: the soft cursor lifts off
        CALL curdrw(0)          '   before whatever happens next
        curph = 0
      END IF
      RETURN c
    END IF
    ' the soft blink, C64-timed: 20 frames a phase, only while
    ' waiting -- which is also the only time the C64 blinked
    IF gkind <> 0 THEN
      IF PEEK(FRAMES) + (PEEK(FRAMES + 1) << 8) - blb >= 32 THEN
        curph = 1 - curph
        CALL curdrw(curph)
        blb = PEEK(FRAMES) + (PEEK(FRAMES + 1) << 8)
      END IF
    END IF
  LOOP
END FUNCTION

' Non-blocking: 0 if nothing is waiting.
'
' It reads the ring the interrupt fills, not the device. That is the
' C64's arrangement and the BBC's -- the interrupt keeps the input
' fresh and everything above it reads memory -- and it is what lets a
' *running* program be stopped, since a running program cannot poll.
' `.rk0` is still the "nothing waiting" branch: sim/test_basic.py
' settles on it.
FUNCTION rawkey() AS INT
  ASM
        LD   R0,[irtail]
        LD   R1,[irhead]
        CMP  R0,R1
        BEQ  .rk0
        PUSHW X
        LDW  X,#irring
        ADDW X,R0
        LD   R1,[X]
        POPW X
        ADD  R0,#1
        AND  R0,#15
        ST   [irtail],R0
        MOV  R0,R1
        CLR  R1
        RET
.rk0:   CLR  R0
        CLR  R1
        RET
  END ASM
END FUNCTION

FUNCTION waitraw() AS INT
  DIM c AS INT
  DO
    c = rawkey()
    IF c <> 0 THEN
      RETURN c
    END IF
  LOOP
END FUNCTION

' ESC [ A and friends into the named key codes -- and $80+n, which is
' what sw/kbd.asm returns for the same keys off the PS/2 port. The two
' wires meet here and nowhere else, so everything above this function
' sees one set of key codes whichever one a key arrived on.
FUNCTION serialkey() AS INT
  DIM c AS INT
  DIM d AS INT
  c = rawkey()
  IF c = 0 THEN
    RETURN 0
  END IF
  IF c >= 128 THEN
    RETURN K_UP + (c - 128)
  END IF
  IF c <> 27 THEN
    RETURN c
  END IF
  ' A lone Escape is Escape. Waiting for the rest of a sequence that is
  ' never coming would hang a game's loop on the one key it is most
  ' likely to test for; a terminal sends ESC [ A in a single burst and
  ' the interrupt has the whole of it in the ring before anything looks.
  IF PEEK(irhead) = PEEK(irtail) THEN
    RETURN 27
  END IF
  d = waitraw()
  IF d <> 91 THEN
    IF d <> 79 THEN
      RETURN 27
    END IF
  END IF
  d = waitraw()
  IF d = 65 THEN
    RETURN K_UP
  END IF
  IF d = 66 THEN
    RETURN K_DOWN
  END IF
  IF d = 67 THEN
    RETURN K_RIGHT
  END IF
  IF d = 68 THEN
    RETURN K_LEFT
  END IF
  IF d = 72 THEN
    RETURN K_HOME
  END IF
  IF d = 70 THEN
    RETURN K_END
  END IF
  IF d = 51 THEN
    d = waitraw()
    RETURN K_DEL
  END IF
  IF d = 50 THEN
    d = waitraw()
    RETURN K_INS
  END IF
  RETURN 27
END FUNCTION

' ---------------------------------------------------------------------
' Reading a logical line back off the screen.
'
' This is the whole trick: Return does not read what you typed, it reads
' what is on the row. Move the cursor onto a listed line, change a
' character, press Return, and the line is re-entered.
' ---------------------------------------------------------------------

' The first row of the logical line that holds row r.
FUNCTION lstart(r AS INT) AS INT
  DO WHILE cont(r) <> 0
    r = r - 1
  LOOP
  RETURN r
END FUNCTION

' The last row of the logical line that starts at row r.
FUNCTION lend(r AS INT) AS INT
  DO WHILE r < rows - 1
    IF cont(r + 1) = 0 THEN
      RETURN r
    END IF
    r = r + 1
  LOOP
  RETURN r
END FUNCTION

' The whole logical line holding row r into lbuf, trailing spaces
' trimmed -- the C64's Return-reads-the-logical-line, generalised.
SUB readrow(r AS INT)
  DIM c AS BYTE
  DIM last AS BYTE
  DIM r0 AS INT
  DIM re AS INT
  DIM k AS BYTE
  r0 = lstart(r)
  re = lend(r0)
  k = 0
  last = 0
  DO WHILE r0 <= re
    c = 0
    DO WHILE c < cols
      lbuf(k) = getat(r0, c)
      IF lbuf(k) <> 32 THEN
        last = k + 1
      END IF
      k = k + 1
      c = c + 1
    LOOP
    r0 = r0 + 1
  LOOP
  llen = last
END SUB

' lbuf written back over the logical line starting at row r0, spanning
' n rows, links maintained. The editing ops read, edit, rewrite.
SUB writelog(r0 AS INT, n AS INT)
  DIM c AS BYTE
  DIM k AS BYTE
  DIM r AS INT
  k = 0
  r = r0
  DO WHILE r < r0 + n
    c = 0
    DO WHILE c < cols
      IF k < llen THEN
        CALL putat(r, c, lbuf(k), A_TEXT)
      ELSE
        CALL putat(r, c, 32, A_TEXT)
      END IF
      k = k + 1
      c = c + 1
    LOOP
    IF r > r0 THEN
      cont(r) = 1
    END IF
    r = r + 1
  LOOP
END SUB

' ---------------------------------------------------------------------
' Tokenising.
'
' A word that is a keyword becomes one byte >= $80; everything else is
' copied. Quoted text and comments are copied whole -- PRINT "FOR" must
' not become PRINT <FOR-token>.
' ---------------------------------------------------------------------



' A character that can appear inside a name: a letter, a digit, or _.


' The token for the word of `n` characters at lbuf(i), or 0.
' The character classes live in their own file because the compiler's
' lexer needs exactly the same ones, and two copies would be two
' answers to "is this a letter".
INCLUDE "chars.bas"

FUNCTION lookup(i AS INT, n AS INT) AS INT
  DIM p AS CARD
  DIM m AS BYTE
  DIM k AS BYTE
  DIM hit AS BYTE
  DIM tok AS BYTE
  p = TOKTAB
  tok = $80
  DO WHILE PEEK(p) <> 0
    m = PEEK(p)
    IF m = n THEN
      k = 0
      hit = 1
      DO WHILE k < n
        IF upper(lbuf(i + k)) <> PEEK(p + 1 + k) THEN
          hit = 0
        END IF
        k = k + 1
      LOOP
      IF hit = 1 THEN
        RETURN tok
      END IF
    END IF
    p = p + m + 1
    tok = tok + 1
  LOOP
  RETURN 0
END FUNCTION

' A literal into tbuf as T_LIT and two bytes.
SUB puttnum(v AS CARD)
  tbuf(tlen) = T_LIT
  tlen = tlen + 1
  tbuf(tlen) = v AND 255
  tlen = tlen + 1
  tbuf(tlen) = v >> 8
  tlen = tlen + 1
END SUB

FUNCTION ishex(c AS INT) AS INT
  IF isdigit(c) <> 0 THEN
    RETURN 1
  END IF
  IF upper(c) > 64 THEN
    IF upper(c) < 71 THEN
      RETURN 1
    END IF
  END IF
  RETURN 0
END FUNCTION

FUNCTION hexof(c AS INT) AS INT
  IF isdigit(c) <> 0 THEN
    RETURN c - 48
  END IF
  RETURN upper(c) - 55
END FUNCTION

SUB tokenise()
  DIM i AS BYTE
  DIM v AS CARD
  DIM w AS BYTE
  DIM t AS BYTE
  DIM k AS BYTE
  DIM q AS BYTE
  i = 0
  tlen = 0
  q = 0
  DO WHILE i < llen
    IF lbuf(i) = 34 THEN
      q = 1 - q
    END IF
    IF q = 1 THEN
      tbuf(tlen) = lbuf(i)
      tlen = tlen + 1
      i = i + 1
    ELSE
      IF lbuf(i) = 39 THEN
        ' a comment runs to the end of the line, verbatim
        DO WHILE i < llen
          tbuf(tlen) = lbuf(i)
          tlen = tlen + 1
          i = i + 1
        LOOP
      ELSE
        IF isalpha(lbuf(i)) <> 0 THEN
          ' A whole identifier, digits and underscores included -- not
          ' just the letters. Scanning only letters split `x_end` into
          ' `x_` and `end`, and `end` is a keyword, so the tail of the
          ' name turned into a keyword token and the name came back from
          ' LIST as something else entirely.
          ' **Bounded by llen, and that is not decoration.**
          ' `shiftlbuf` slides the line down over the line number and
          ' shortens llen without clearing what it left behind, so
          ' `20 END` becomes `END` with `END` still sitting at lbuf(3).
          ' An unbounded scan read `ENDEND`, found no keyword, and
          ' stored six characters where the END token belonged -- so the
          ' interpreter walked off the end of the program instead of
          ' stopping. `PRINT` escaped it only because its own stale tail
          ' happened to begin with a space.
          w = 0
          DO WHILE i + w < llen
            IF isident(lbuf(i + w)) = 0 THEN
              EXIT DO
            END IF
            w = w + 1
          LOOP
          ' A trailing $ is part of the name, not the start of a hex
          ' literal. The suffix is the type -- it is what keeps A and A$
          ' apart -- so it is taken here, before the $ arm below can
          ' claim it. A bare $FE70 still parses as hex, because it does
          ' not follow an identifier.
          IF i + w < llen THEN
            IF lbuf(i + w) = 36 THEN
              w = w + 1
            END IF
          END IF
          t = lookup(i, w)
          IF w = 0 THEN
            t = 0
          END IF
          IF t <> 0 THEN
            tbuf(tlen) = t
            tlen = tlen + 1
            ' REM is an ordinary keyword -- lookup finds it, case and
            ' all -- and it takes the rest of the line with it,
            ' verbatim. So LIST prints the keyword back from the token
            ' and the comment exactly as typed, and the interpreter
            ' skips the line on one dispatch. Stored as plain text, as
            ' it was, a comment reached the assignment handler instead
            ' and every REM was ?SYNTAX.
            IF t = T_REM THEN
              i = i + w
              w = 0
              DO WHILE i < llen
                tbuf(tlen) = lbuf(i)
                tlen = tlen + 1
                i = i + 1
              LOOP
            END IF
          ELSE
            k = 0
            DO WHILE k < w
              tbuf(tlen) = lbuf(i + k)
              tlen = tlen + 1
              k = k + 1
            LOOP
          END IF
          i = i + w
        ELSE
          IF isdigit(lbuf(i)) <> 0 THEN
            v = 0
            DO WHILE i < llen
              IF isdigit(lbuf(i)) = 0 THEN
                EXIT DO
              END IF
              v = v * 10 + (lbuf(i) - 48)
              i = i + 1
            LOOP
            CALL puttnum(v)
          ELSE
            IF lbuf(i) = 36 THEN
              ' $ and hex digits
              v = 0
              i = i + 1
              DO WHILE i < llen
                IF ishex(lbuf(i)) = 0 THEN
                  EXIT DO
                END IF
                v = (v << 4) + hexof(lbuf(i))
                i = i + 1
              LOOP
              CALL puttnum(v)
            ELSE
              tbuf(tlen) = lbuf(i)
              tlen = tlen + 1
              i = i + 1
            END IF
          END IF
        END IF
      END IF
    END IF
  LOOP
END SUB

' A token byte back into its word, printed.
SUB puttok(t AS INT)
  DIM p AS CARD
  DIM m AS BYTE
  DIM k AS BYTE
  DIM n AS BYTE
  p = TOKTAB
  n = $80
  DO WHILE PEEK(p) <> 0
    m = PEEK(p)
    IF n = t THEN
      k = 0
      DO WHILE k < m
        CALL emit(PEEK(p + 1 + k))
        k = k + 1
      LOOP
      RETURN
    END IF
    p = p + m + 1
    n = n + 1
  LOOP
END SUB

' ---------------------------------------------------------------------
' The program: tokenised lines in ascending order.
'
'   lineno (2, little endian)   len (1)   tokens (len bytes)
'
' `len` makes skipping a line one add, so finding line n is a walk and
' not a search.
' ---------------------------------------------------------------------

FUNCTION lineno(p AS CARD) AS INT
  RETURN PEEK(p) + (PEEK(p + 1) << 8)
END FUNCTION

FUNCTION linelen(p AS CARD) AS INT
  RETURN PEEK(p + 2)
END FUNCTION

' A record is lineno(2) len(1) tokens(len) and then a zero, so the
' interpreter can ask "end of line?" with one load instead of a 16-bit
' compare against a maintained end pointer. The terminator is not
' counted in len, so LIST and the memmoves are unchanged.
FUNCTION nextline(p AS CARD) AS CARD
  RETURN p + 4 + linelen(p)
END FUNCTION

' The first line with a number >= n, or progend.
FUNCTION findline(n AS INT) AS CARD
  DIM p AS CARD
  p = PROG
  DO WHILE p < progend
    IF lineno(p) >= n THEN
      RETURN p
    END IF
    p = nextline(p)
  LOOP
  RETURN progend
END FUNCTION

SUB memmove(dst AS CARD, src AS CARD, n AS CARD)
  ' Overlapping copies both ways: growing a line moves the tail up,
  ' shrinking it moves the tail down, and the direction has to follow
  ' or the copy eats itself.
  '
  ' The count is tested at the top of each loop, before the borrow is
  ' propagated. Testing after it means R2:R3 has already wrapped to
  ' $FFFF and the loop never ends.
  ASM
        LD   R0,[SP+2]
        MOV  XL,R0
        LD   R0,[SP+3]
        MOV  XH,R0
        LD   R0,[SP+4]
        MOV  YL,R0
        LD   R0,[SP+5]
        MOV  YH,R0
        LD   R2,[SP+6]
        LD   R3,[SP+7]
        LD   R0,[SP+2]                  ; dst - src, 16-bit
        LD   R1,[SP+4]
        SUB  R0,R1
        LD   R0,[SP+3]
        LD   R1,[SP+5]
        SBC  R0,R1
        BLO  .up                        ; dst below src: walk up
        ADDW X,R2                       ; else point past the end
        MOV  R0,XH
        ADD  R0,R3
        MOV  XH,R0
        ADDW Y,R2
        MOV  R0,YH
        ADD  R0,R3
        MOV  YH,R0
.dn:    MOV  R0,R2
        OR   R0,R3
        BEQ  .mm9
        DECW X
        DECW Y
        LD   R0,[Y]
        ST   [X],R0
        SUB  R2,#1
        BCS  .dn
        SUB  R3,#1
        BRA  .dn
.up:    MOV  R0,R2
        OR   R0,R3
        BEQ  .mm9
        LD   R0,[Y]
        ST   [X],R0
        INCW X
        INCW Y
        SUB  R2,#1
        BCS  .up
        SUB  R3,#1
        BRA  .up
.mm9:
  END ASM
END SUB

' Store, replace or delete the line now in tbuf with number n.
SUB storeline(n AS INT)
  DIM p AS CARD
  DIM old AS INT
  DIM need AS INT
  DIM k AS BYTE
  p = findline(n)
  old = 0
  IF p < progend THEN
    IF lineno(p) = n THEN
      old = 4 + linelen(p)
    END IF
  END IF
  need = 0
  IF tlen > 0 THEN
    need = 4 + tlen
  END IF
  IF progend - old + need > USERTOP THEN
    CALL errmsg(4)
    RETURN
  END IF
  ' make the hole the right size
  IF need <> old THEN
    CALL memmove(p + need, p + old, progend - p - old)
    progend = progend - old + need
  END IF
  IF need = 0 THEN
    RETURN
  END IF
  POKE p, n AND 255
  POKE p + 1, n >> 8
  POKE p + 2, tlen
  k = 0
  DO WHILE k < tlen
    POKE p + 3 + k, tbuf(k)
    k = k + 1
  LOOP
  POKE p + 3 + tlen, 0          ' the end-of-line marker
END SUB

' ---------------------------------------------------------------------
' Commands.
' ---------------------------------------------------------------------

SUB list(a AS INT, b AS INT)
  DIM p AS CARD
  DIM k AS BYTE
  DIM t AS BYTE
  DIM v AS CARD
  p = PROG
  DO WHILE p < progend
    IF lineno(p) >= a THEN
      IF lineno(p) > b THEN
        RETURN
      END IF
      CALL s_putn(lineno(p))
      CALL emit(32)
      k = 0
      DO WHILE k < linelen(p)
        t = PEEK(p + 3 + k)
        IF t = T_LIT THEN
          ' a binary literal: two bytes, printed back as digits
          v = PEEK(p + 4 + k)
          v = v + (PEEK(p + 5 + k) << 8)
          CALL s_putn(v)
          k = k + 3
        ELSE
          IF t > 127 THEN
            CALL puttok(t)
          ELSE
            CALL emit(t)
          END IF
          k = k + 1
        END IF
      LOOP
      CALL newline()
    END IF
    p = nextline(p)
  LOOP
END SUB

SUB new()
  progend = PROG
END SUB

SUB renumber(start AS INT, step AS INT)
  DIM p AS CARD
  DIM n AS INT
  n = start
  p = PROG
  DO WHILE p < progend
    POKE p, n AND 255
    POKE p + 1, n >> 8
    n = n + step
    p = nextline(p)
  LOOP
END SUB

SUB deleterange(a AS INT, b AS INT)
  DIM p AS CARD
  DIM q AS CARD
  p = findline(a)
  q = p
  DO WHILE q < progend
    IF lineno(q) > b THEN
      EXIT DO
    END IF
    q = nextline(q)
  LOOP
  IF q > p THEN
    CALL memmove(p, q, progend - q)
    progend = progend - (q - p)
  END IF
END SUB

FUNCTION freebytes() AS CARD
  RETURN USERTOP - progend
END FUNCTION

' ---------------------------------------------------------------------
' Errors, C64-shaped: short, because string space is scarce.
' ---------------------------------------------------------------------

' ---------------------------------------------------------------------
' RUN.
'
' The interpreter walks the program the editor is holding -- there is no
' compile step and no second copy -- so all this does is tell it where
' everything is, assemble any ASM blocks, and go.
'
' The map above the program, from the top down:
'
'   $7F00-$7FFF   the string accumulator, 256 bytes
'   $7EE0-$7EFF   the CALL stack, 8 frames of 4
'   ...-$7EDF     the heap, growing down
'   codetop...    the name table, growing up
'   progend...    the assembled ASM blocks
'   $0200...      the program text
'
' The name table starts where the assembled code ends, which is why the
' assembly pass runs first: until it has, codetop is not known.
' ---------------------------------------------------------------------
SUB dorun()
  DIM e AS BYTE
  DIM p AS CARD
  ASM
        MOV  R0,#$00            ; LREC = PROG, the first record
        ST   [$0014],R0
        MOV  R0,#$02
        ST   [$0015],R0
        ; ACBASE was the on-machine assembler's output base and [D63]
        ; deleted the assembler. Nothing in the image reads $00DC any
        ; more -- only sw/asm.asm did, and that is out of the build --
        ; and the byte now belongs to the float operand stack, so the
        ; write was a leftover aimed into live storage. Harmless only
        ; because FSTK is empty when RUN starts.
        ; **Names, not literals, and HEAP is why.** This block wrote
        ; $7EDF into HEAP as two halves -- the top of the user area back
        ; when the workspace lived in the $FF00 page. The system storage
        ; region is at $7DE9-$7EDF now ([D67]), so that literal aimed the
        ; heap at DIRBUF, FORSTK and the keyboard ring, and the first
        ; array a program dimensioned would have grown down through all
        ; three. USERTOP is a symbol in sw/zp.asm and follows the region.
        MOV  R0,#>SACCBUF       ; the string accumulator
        ST   [SACC+1],R0
        MOV  R0,#<SACCBUF
        ST   [SACC],R0
        MOV  R0,#<CSTKBUF       ; the CALL stack
        ST   [CSTK],R0
        MOV  R0,#>CSTKBUF
        ST   [CSTK+1],R0
        MOV  R0,#<USERTOP       ; the heap comes down from here
        ST   [HEAP],R0
        MOV  R0,#>USERTOP
        ST   [HEAP+1],R0
  END ASM
  ' PEND and the name table need progend, which is a BASIC variable.
  ' **The name table starts at progend now.** It used to start wherever
  ' the assembly pass had finished laying code down; there is no pass
  ' any more ([D63]), so nothing sits between the program and the names.
  POKE $0016, progend AND 255
  POKE $0017, progend >> 8
  POKE $0027, progend AND 255
  POKE $0028, progend >> 8
  ASM
        MOV  R0,#$00            ; ERR is cleared HERE, at the entry of
        ST   [$0018],R0         ;   the code that reads it. irun only
                                ;   ever SETS it, so a stale ?BREAK from
                                ;   the last run must not survive into
                                ;   this one
        MOV  R0,#$00            ; LREC to the first record
        ST   [$0014],R0
        MOV  R0,#$02
        ST   [$0015],R0
        CALL irun
  END ASM
  ' NOTHING is restored, by ruling: mode, palette, scroll, sprites and
  ' sound all stay exactly as the program left them, and the editor
  ' works wherever it wakes up -- the C64's deal, made livable by the
  ' console knowing every mode. setgeom reads the world as it is.
  CALL setgeom()
  e = PEEK($0018)
  IF e <> 255 THEN
    IF e <> 0 THEN
      CALL runerr(e)
    END IF
  END IF
END SUB

' ?<what> IN <line>. LREC still holds the record that failed, so the
' line number is a read rather than a search.
SUB runerr(n AS INT)
  DIM p AS CARD
  DIM k AS BYTE
  DIM r AS CARD
  p = RUNTAB
  k = 1
  DO WHILE k < n
    DO WHILE PEEK(p) <> 0
      p = p + 1
    LOOP
    p = p + 1
    k = k + 1
  LOOP
  CALL emit(63)
  CALL puts(p)
  r = PEEK($0014) + (PEEK($0015) << 8)
  IF r >= PROG THEN
    IF r < progend THEN
      CALL emit(32)
      CALL emit(73)
      CALL emit(78)
      CALL emit(32)
      CALL s_putn(lineno(r))
    END IF
  END IF
  CALL newline()
END SUB

' puts' length-counted sibling. A heap string carries its length rather
' than a terminator, so PRINT of one cannot go through puts -- which
' would run on into whatever follows it in the accumulator.
SUB putsn(p AS CARD, n AS INT)
  DIM k AS BYTE
  k = 0
  DO WHILE k < n
    CALL emit(PEEK(p + k))
    k = k + 1
  LOOP
END SUB

' One message table for the editor and the interpreter alike: n is a
' RUNTAB index. One namespace is also what a direct mode will need --
' a statement typed at the editor fails with the same words either way.
SUB errmsg(n AS INT)
  DIM p AS CARD
  DIM k AS BYTE
  p = RUNTAB
  k = 0
  DO WHILE k < n
    DO WHILE PEEK(p) <> 0
      p = p + 1
    LOOP
    p = p + 1
    k = k + 1
  LOOP
  CALL emit(63)
  CALL puts(p)
  CALL newline()
END SUB


' ---------------------------------------------------------------------
' Files.
'
' sw/fs.asm does the flash; this turns a typed name into the eleven-byte
' 8.3 field the directory holds, and hands it the program text.
'
' The volume is log-structured, so SAVE over a name that already exists
' deletes the old entry and appends a new one at the tail. On NOR flash
' that is the cheap operation and not the expensive one: programming can
' only clear bits, so deleting is one byte cleared to $00 and writing is
' bytes that are still $FF. Nothing is erased and nothing is rewritten in
' place, and no 4 KB buffer is needed anywhere.
' ---------------------------------------------------------------------

' Two of fs.asm's variables, by address, because BASIC cannot see an
' assembler equate. They must track FSVARS in sw/fs.asm, which is at
' $0074 -- it was moved out of $0100 so that page 1 is the CPU stack and
' nothing else. If fs.asm moves again these move with it.
CONST FSENT = $007B             ' fs.asm's fsent -- FSVARS+7
CONST FSFPG = $0078             ' and its first free page -- FSVARS+4
CONST VOLPGS = 1776             ' data pages; the rest is scratch

DIM fname(10) AS BYTE           ' 8.3, space padded, upper case
DIM faddr AS CARD               ' where the bytes are, or go
DIM flen AS CARD                ' how many of them
DIM fdrv AS BYTE                ' the mounted drive
DIM fidx AS BYTE                ' the directory entry DIR is reading
DIM fok AS BYTE                 ' did the last call succeed

SUB fsmount()
  ASM
        LD   R0,[v_fdrv]
        CALL fs_mount
  END ASM
END SUB

SUB fsfind()
  ASM
        LDW  X,#a_fname
        CALL fs_find
        BCC  .fn1
        LD   R0,[fsent+14]
        ST   [v_flen],R0
        LD   R0,[fsent+15]
        ST   [v_flen+1],R0
        MOV  R0,#1
        BRA  .fn2
.fn1:   CLR  R0
.fn2:   ST   [v_fok],R0
  END ASM
END SUB

SUB fssave()
  ASM
        LD   R0,[v_flen]
        ST   [fslen],R0
        LD   R0,[v_flen+1]
        ST   [fslen+1],R0
        LDW  X,#a_fname
        LDW  Y,[v_faddr]
        CALL fs_save
        BCC  .sv1
        MOV  R0,#1
        BRA  .sv2
.sv1:   CLR  R0
.sv2:   ST   [v_fok],R0
  END ASM
END SUB

SUB fsload()
  ASM
        LDW  X,#a_fname
        LDW  Y,[v_faddr]
        CALL fs_load
        BCC  .ld1
        LD   R0,[fslen]
        ST   [v_flen],R0
        LD   R0,[fslen+1]
        ST   [v_flen+1],R0
        MOV  R0,#1
        BRA  .ld2
.ld1:   CLR  R0
.ld2:   ST   [v_fok],R0
  END ASM
END SUB

SUB fserase()
  ASM
        LDW  X,#a_fname
        CALL fs_delete
        BCC  .er1
        MOV  R0,#1
        BRA  .er2
.er1:   CLR  R0
.er2:   ST   [v_fok],R0
  END ASM
END SUB

' ---- whole pages, for COMPACT

' One page in transit -- laid over the string accumulator rather than
' allocated. The two lifetimes cannot meet: SACC exists only while a
' program runs, and every filesystem command runs from the editor.
DIM pbuf(255) AS BYTE AT $7F00
DIM cpage AS INT                ' the page it comes from or goes to

SUB rdpage(p AS INT)
  cpage = p
  ASM
        LD   R0,[v_cpage]
        ST   [fspg],R0
        LD   R0,[v_cpage+1]
        ST   [fspg+1],R0
        LDW  X,#$7F00           ; pbuf, laid over SACC
        STW  [fsbuf],X
        CALL fs_rdpg
  END ASM
END SUB

SUB wrpage(p AS INT)
  cpage = p
  ASM
        LD   R0,[v_cpage]
        ST   [fspg],R0
        LD   R0,[v_cpage+1]
        ST   [fspg+1],R0
        LDW  X,#$7F00           ; pbuf, laid over SACC
        STW  [fsbuf],X
        CALL fs_wrpg
  END ASM
END SUB

SUB erasesect(p AS INT)
  cpage = p
  ASM
        LD   R0,[v_cpage]
        ST   [fspg],R0
        LD   R0,[v_cpage+1]
        ST   [fspg+1],R0
        CALL fs_erapg
  END ASM
END SUB

' Read directory entry `fidx` into fs.asm's fsent, where DIR PEEKs it.
SUB fsreadent()
  ASM
        LD   R0,[v_fidx]
        CALL fs_seekent
        CALL fls_seek
        CALL fls_open
        CALL fs_rdent
        CALL fls_close
  END ASM
END SUB

' ---------------------------------------------------------------------
' The command line: what Return does with a row.
' ---------------------------------------------------------------------

DIM ip AS BYTE                  ' where the parser is in lbuf

SUB skipsp()
  DO WHILE ip < llen
    IF lbuf(ip) <> 32 THEN
      EXIT DO
    END IF
    ip = ip + 1
  LOOP
END SUB

' A decimal number at ip, or -1 if there is not one.
' number() is sw/ed.asm's s_number now: the shared parser
' snumi, plus a position. See docs/01-decisions.md D66.

' A file name at ip -- NAME, "NAME", or either with .EXT -- into fname as
' the eleven-byte 8.3 field the directory holds. 1 if there was one.
FUNCTION parsename() AS INT
  DIM k AS BYTE
  DIM c AS BYTE
  DIM q AS BYTE
  k = 0
  DO WHILE k < 11
    fname(k) = 32
    k = k + 1
  LOOP
  CALL skipsp()
  q = 0
  IF ip < llen THEN
    IF lbuf(ip) = 34 THEN
      q = 1
      ip = ip + 1
    END IF
  END IF
  k = 0
  DO WHILE ip < llen
    c = upper(lbuf(ip))
    IF c = 34 THEN
      ip = ip + 1
      EXIT DO
    END IF
    IF q = 0 THEN
      IF c = 32 THEN
        EXIT DO
      END IF
      IF c = 44 THEN
        EXIT DO
      END IF
    END IF
    IF c = 46 THEN
      k = 8
    ELSE
      IF k < 11 THEN
        fname(k) = c
        k = k + 1
      END IF
    END IF
    ip = ip + 1
  LOOP
  IF fname(0) = 32 THEN
    RETURN 0
  END IF
  ' Nothing typed after the dot: a program is a .BAS.
  IF fname(8) = 32 THEN
    fname(8) = 66
    fname(9) = 65
    fname(10) = 83
  END IF
  RETURN 1
END FUNCTION

' The command cores. fname, where one is needed, is already set: the
' interpreter's tname bridge read the quoted name out of the token
' stream into lbuf and ran the same parsename the editor always used.
SUB dofree()
  CALL s_putn(freebytes())
  CALL puts(MSGFREE)
  CALL newline()
END SUB

SUB drivecore(n AS INT)
  IF n < 0 THEN
    n = 0
  END IF
  fdrv = n AND 15
  CALL fsmount()
END SUB

SUB eracore()
  CALL fserase()
  IF fok = 0 THEN
    CALL errmsg(20)
  END IF
END SUB

' SAVE "N" AT a, l -- l raw bytes from a: sprite sheets, tile sets,
' fonts, machine code. The BBC's *SAVE, brought inside the language.
SUB savedata(a AS CARD, l AS CARD)
  faddr = a
  flen = l
  CALL fssave()
  IF fok = 0 THEN
    CALL errmsg(19)
  END IF
END SUB

' LOAD "N" AT a -- the file's bytes to address a, no line stitching.
SUB loaddata(a AS CARD)
  CALL fsfind()
  IF fok = 0 THEN
    CALL errmsg(20)
    RETURN
  END IF
  faddr = a
  CALL fsload()
  IF fok = 0 THEN
    CALL errmsg(20)
  END IF
END SUB

SUB savecore()
  DIM had AS BYTE
  ' Write first, delete second -- the order matters twice over.
  '
  ' Deleting first would drop the old file out of the scan that derives
  ' the free pointer, so the new version would be programmed on top of
  ' the old one's pages. Those pages are not $FF any more and
  ' programming only clears bits, so what came back would be the two
  ' versions ANDed together.
  '
  ' It is also the safe order across a power cut: the worst that can be
  ' interrupted is a second copy nobody is using yet, and the old one
  ' still loads. fs_find takes the first match scanning from entry zero,
  ' which is the older of the two, so the delete afterwards removes the
  ' right one.
  CALL fsfind()
  had = fok
  faddr = PROG
  flen = progend - PROG
  CALL fssave()
  IF fok = 0 THEN
    CALL errmsg(19)
    RETURN
  END IF
  IF had <> 0 THEN
    CALL fserase()
  END IF
END SUB

' Copy the stored line at p into tbuf, so storeline can place it.
SUB fetchline(p AS CARD)
  DIM k AS BYTE
  tlen = linelen(p)
  k = 0
  DO WHILE k < tlen
    tbuf(k) = PEEK(p + 3 + k)
    k = k + 1
  LOOP
END SUB

SUB loadcore(from AS INT)
  DIM p AS CARD
  DIM top AS CARD
  IF from < 0 THEN
    CALL new()
    faddr = PROG
    CALL fsload()
    IF fok = 0 THEN
      CALL errmsg(20)
      RETURN
    END IF
    progend = PROG + flen
    RETURN
  END IF
  ' LOAD "n",100 merges the file from line 100 on into what is already
  ' there. The file lands at the top of free memory and the lines are
  ' stored one at a time, which keeps the program in order and costs
  ' nothing that a typed-in line does not. The text grows upward as they
  ' go in, so the two must not meet: the worst case is the whole file.
  CALL fsfind()
  IF fok = 0 THEN
    CALL errmsg(20)
    RETURN
  END IF
  top = MEMTOP - flen + 1
  IF progend + flen >= top THEN
    CALL errmsg(4)
    RETURN
  END IF
  faddr = top
  CALL fsload()
  IF fok = 0 THEN
    CALL errmsg(20)
    RETURN
  END IF
  p = top
  DO WHILE p < top + flen
    IF lineno(p) >= from THEN
      CALL fetchline(p)
      CALL storeline(lineno(p))
    END IF
    p = nextline(p)
  LOOP
END SUB

' ---------------------------------------------------------------------
' COMPACT -- the only command that erases.
'
' Deleting a file clears its status byte and leaves the bytes where they
' are, because that is all NOR flash lets you do cheaply. COMPACT is what
' gets the space back: it slides the live files down and rewrites the
' directory.
'
' Sliding means erasing a 4 KB sector before rewriting it, which destroys
' whatever else lives in that sector -- so the contents have to be
' somewhere else first. There is nowhere in RAM to put 4 KB: main RAM
' holds the user's program and video RAM holds their sprites and the
' compiler image, and a command that quietly ate either would be worse
' than no command. So the somewhere else is the last sector of the
' volume, reserved for exactly this. Gather a sector's worth into the
' scratch, erase the destination, copy it back.
'
' It costs 4 KB of every volume, and it is slow -- every byte is
' programmed twice, and a program is one flash opcode. Compaction was
' slow on every machine that had it.
' ---------------------------------------------------------------------

CONST SCRATCH = 1776            ' the reserved sector, and the data end
CONST LASTSEC = 110             ' the last sector of data

DIM ci AS INT                   ' the entry nextsrc is walking
DIM cleft AS INT                ' pages left in it
DIM csrc AS INT                 ' and its next source page
DIM spg(15) AS INT              ' the sixteen sources for one sector

FUNCTION entpages() AS INT
  DIM n AS INT
  n = PEEK(FSENT + 15)
  IF PEEK(FSENT + 14) <> 0 THEN
    n = n + 1                   ' a partial page still costs a page
  END IF
  RETURN n
END FUNCTION

FUNCTION entpage() AS INT
  DIM n AS INT
  n = PEEK(FSENT + 13)
  n = n << 8
  RETURN n + PEEK(FSENT + 12)
END FUNCTION

' The live files' pages, in order, one per call. 0 when there are no
' more. Entries are appended and data goes at the tail, so walking the
' directory in index order walks the pages in increasing order too.
FUNCTION nextsrc() AS INT
  DIM st AS BYTE
  DIM r AS INT
  DO WHILE cleft = 0
    IF ci > 255 THEN
      RETURN 0
    END IF
    fidx = ci
    ci = ci + 1
    CALL fsreadent()
    st = PEEK(FSENT + 11)
    IF st = 255 THEN
      ci = 256
      RETURN 0
    END IF
    IF st <> 0 THEN
      IF st <> 128 THEN
        csrc = entpage()
        cleft = entpages()
      END IF
    END IF
  LOOP
  r = csrc
  csrc = csrc + 1
  cleft = cleft - 1
  RETURN r
END FUNCTION

' The directory, rebuilt: the live entries at new page numbers, in the
' same order, with the deleted ones gone.
SUB rewritedir()
  DIM i AS INT
  DIM slot AS INT
  DIM k AS INT
  DIM st AS BYTE
  DIM dst AS INT
  DIM np AS INT
  ' Build it in the scratch first, so the old directory is still there
  ' to read while the new one is being written.
  CALL erasesect(SCRATCH)
  k = 0
  DO WHILE k < 256
    pbuf(k) = 255
    k = k + 1
  LOOP
  slot = 0
  dst = 16
  i = 0
  DO WHILE i < 256
    fidx = i
    CALL fsreadent()
    st = PEEK(FSENT + 11)
    IF st = 255 THEN
      EXIT DO
    END IF
    IF st <> 0 THEN
      k = 0
      DO WHILE k < 16
        pbuf((slot AND 15) * 16 + k) = PEEK(FSENT + k)
        k = k + 1
      LOOP
      IF st <> 128 THEN
        np = entpages()
        pbuf((slot AND 15) * 16 + 12) = dst AND 255
        pbuf((slot AND 15) * 16 + 13) = dst >> 8
        dst = dst + np
      END IF
      slot = slot + 1
      IF (slot AND 15) = 0 THEN
        CALL wrpage(SCRATCH + (slot >> 4) - 1)
        k = 0
        DO WHILE k < 256
          pbuf(k) = 255
          k = k + 1
        LOOP
      END IF
    END IF
    i = i + 1
  LOOP
  IF (slot AND 15) <> 0 THEN
    CALL wrpage(SCRATCH + (slot >> 4))
  END IF
  ' Now the swap. Everything above the entries stays $FF from the erase.
  CALL erasesect(0)
  k = 0
  DO WHILE k <= slot >> 4
    CALL rdpage(SCRATCH + k)
    CALL wrpage(k)
    k = k + 1
  LOOP
END SUB

SUB docompact()
  DIM sect AS INT
  DIM n AS INT
  DIM s AS INT
  DIM moved AS BYTE
  DIM done AS BYTE
  ci = 0
  cleft = 0
  sect = 1
  done = 0
  DO WHILE sect <= LASTSEC
    IF done <> 0 THEN
      ' past the live data: stale bytes, and nothing may be appended
      ' over them, so they have to go back to $FF.
      CALL erasesect(sect * 16)
    ELSE
      n = 0
      moved = 0
      DO WHILE n < 16
        s = nextsrc()
        IF s = 0 THEN
          EXIT DO
        END IF
        spg(n) = s
        IF s <> sect * 16 + n THEN
          moved = 1
        END IF
        n = n + 1
      LOOP
      IF n < 16 THEN
        moved = 1               ' a partial sector: its tail must be clean
        done = 1
      END IF
      IF moved <> 0 THEN
        ' Read before erasing, always. The sources are all at or above
        ' this sector, and sixteen live pages consumed from at or above
        ' its start leaves the cursor past its end -- so by the time the
        ' destination is erased there is nothing left in it to lose.
        CALL erasesect(SCRATCH)
        s = 0
        DO WHILE s < n
          CALL rdpage(spg(s))
          CALL wrpage(SCRATCH + s)
          s = s + 1
        LOOP
        CALL erasesect(sect * 16)
        s = 0
        DO WHILE s < n
          CALL rdpage(SCRATCH + s)
          CALL wrpage(sect * 16 + s)
          s = s + 1
        LOOP
      END IF
    END IF
    sect = sect + 1
  LOOP
  CALL rewritedir()
  CALL fsmount()
END SUB

SUB dodir()
  DIM i AS INT
  DIM k AS BYTE
  DIM st AS BYTE
  DIM sz AS CARD
  i = 0
  DO WHILE i < 256
    fidx = i
    CALL fsreadent()
    st = PEEK(FSENT + 11)
    IF st = 255 THEN
      EXIT DO
    END IF
    ' $00 is deleted and $80 is the volume label; neither is a file.
    IF st <> 0 THEN
      IF st <> 128 THEN
        k = 0
        DO WHILE k < 11
          IF k = 8 THEN
            CALL emit(46)
          END IF
          CALL emit(PEEK(FSENT + k))
          k = k + 1
        LOOP
        CALL emit(32)
        sz = PEEK(FSENT + 15)
        sz = sz << 8
        sz = sz + PEEK(FSENT + 14)
        CALL s_putn(sz)
        CALL newline()
      END IF
    END IF
    i = i + 1
  LOOP
  ' What is left is the tail, in pages of 256 bytes -- 448 KB of them
  ' does not fit in sixteen bits, so this counts in KB.
  sz = PEEK(FSFPG + 1)
  sz = sz << 8
  sz = sz + PEEK(FSFPG)
  CALL s_putn((VOLPGS - sz) >> 2)
  CALL puts(MSGKFREE)
  CALL newline()
END SUB

' Does lbuf at ip start with the word at table entry `idx`?


' Direct mode. The line is tokenised into tbuf as any stored line
' would be, staged as a record at DIRBUF ($FF88) with the sentinel
' line number $FFFF -- no legal line is 65535, and runerr's own
' bounds check already prints a bare ?FAULT for a record outside the
' program -- and executed by idrct with the same preflight RUN gets.
' What is deliberately NOT done: no variable clear (state survives,
' PRINT A after a break works), and none of dorun's mode/sound
' restore -- a direct MODE 3 takes effect and STAYS, which is the
' whole point and exactly the C64's freedom. MODE 0 typed blind
' brings the editor back.
SUB dodirect()
  DIM k AS BYTE
  DIM q AS BYTE
  DIM e AS BYTE
  CALL shiftlbuf()
  CALL tokenise()
  ' a direct ASM statement has nothing behind it -- the assembler
  ' pass covers the stored program, not this buffer
  q = 0
  k = 0
  DO WHILE k < tlen
    IF tbuf(k) = 34 THEN
      q = 1 - q
    END IF
    IF q = 0 THEN
      IF tbuf(k) = $9E THEN
        CALL errmsg(9)
        RETURN
      END IF
    END IF
    k = k + 1
  LOOP
  POKE DIRBUF, 255
  POKE DIRBUF + 1, 255
  POKE DIRBUF + 2, tlen
  k = 0
  DO WHILE k < tlen
    POKE DIRBUF + 3 + k, tbuf(k)
    k = k + 1
  LOOP
  POKE DIRBUF + 3 + tlen, 0
  ' dorun's preflight, verbatim: frame constants, the assembler pass
  ' over the program, the name table, then idrct instead of irun.
  ASM
        MOV  R0,#$00            ; LREC = PROG, the first record
        ST   [$0014],R0
        MOV  R0,#$02
        ST   [$0015],R0
        ; **Names, not literals, and HEAP is why.** This block wrote
        ; $7EDF into HEAP as two halves -- the top of the user area back
        ; when the workspace lived in the $FF00 page. The system storage
        ; region is at $7DE9-$7EDF now ([D67]), so that literal aimed the
        ; heap at DIRBUF, FORSTK and the keyboard ring, and the first
        ; array a program dimensioned would have grown down through all
        ; three. USERTOP is a symbol in sw/zp.asm and follows the region.
        MOV  R0,#>SACCBUF       ; the string accumulator
        ST   [SACC+1],R0
        MOV  R0,#<SACCBUF
        ST   [SACC],R0
        MOV  R0,#<CSTKBUF       ; the CALL stack
        ST   [CSTK],R0
        MOV  R0,#>CSTKBUF
        ST   [CSTK+1],R0
        MOV  R0,#<USERTOP       ; the heap comes down from here
        ST   [HEAP],R0
        MOV  R0,#>USERTOP
        ST   [HEAP+1],R0
  END ASM
  POKE $0016, progend AND 255
  POKE $0017, progend >> 8
  POKE $0027, progend AND 255
  POKE $0028, progend >> 8
  ASM
        MOV  R0,#$00            ; ERR cleared at the entry of the
        ST   [$0018],R0         ;   code that reads it, as in dorun
        MOV  R0,#$00            ; LREC back to PROG for subscan
        ST   [$0014],R0
        MOV  R0,#$02
        ST   [$0015],R0
        CALL idrct
  END ASM
  ' a direct MODE just took effect: the editor follows it, here
  CALL setgeom()
  e = PEEK($0018)
  IF e <> 255 THEN
    IF e <> 0 THEN
      CALL runerr(e)
    END IF
  END IF
END SUB


' Return was pressed on row r.
SUB enter(r AS INT)
  DIM n AS INT
  CALL readrow(r)
  ' the cursor lands after the whole LOGICAL line, as on the C64
  cy = lend(lstart(r))
  CALL newline()
  ip = 0
  CALL skipsp()
  IF ip >= llen THEN
    RETURN
  END IF
  IF isdigit(lbuf(ip)) <> 0 THEN
    n = s_number()
    ' the rest of the row is the line; drop one separating space
    IF ip < llen THEN
      IF lbuf(ip) = 32 THEN
        ip = ip + 1
      END IF
    END IF
    CALL shiftlbuf()
    CALL tokenise()
    CALL storeline(n)
    RETURN
  END IF
  ' No line number: execute. Commands are ordinary statements now, so
  ' this one branch is the whole grammar -- the BBC's exact shape.
  CALL dodirect()
END SUB

' Slide lbuf down so the line body starts at 0.
SUB shiftlbuf()
  DIM k AS BYTE
  k = 0
  DO WHILE ip + k < llen
    lbuf(k) = lbuf(ip + k)
    k = k + 1
  LOOP
  llen = k
  ip = 0
END SUB

' The boot screen is painted by the relocating stub -- run-once code
' the init below wipes along with the rest of user RAM -- so neither
' its text nor its painting costs a resident byte. tools/mkboot.py owns
' it, free count included: a freshly booted machine is empty by
' definition, so the number is a build-time constant.

' Ctrl+Esc: put the machine back where the editor can be used, and keep
' the program. That is the state a program ruins rather than the memory
' it fills -- MODE 4 with sprites over an unreadable screen is a working
' machine nobody can see, and the listing is the thing worth not losing.
' Ctrl+Shift+Esc does not come here: the keyboard resets the machine
' itself, because a program that has stopped listening cannot be asked
' to.
SUB doreset()
  POKE IRST, 0
  POKE VID_MODE, $80
  POKE VID_BASE_L, SCREEN AND 255
  POKE VID_BASE_H, SCREEN >> 8
  POKE SPR_CTRL, 0                 ' sprites off
  vtop = 0
  CALL setgeom()
  CALL cls()
END SUB

' ---------------------------------------------------------------------
' The loop.
' ---------------------------------------------------------------------

DIM k AS INT

POKE VID_MODE, $80
POKE VID_BASE_L, SCREEN AND 255
POKE VID_BASE_H, SCREEN >> 8
' The cursor is NOT enabled here: the wipe and the mount below take a
' visible moment, and an enabled cursor would sit at the ROM's stale
' position for all of it before snapping home. It turns on at the end
' of init, already in place.
vtop = 0
progend = PROG
fdrv = 0

' The input interrupt. sw/boot.asm leaves NMI, IRQ and BRK all pointing
' at a bare RETI and never enables interrupts, so this is the first
' handler the machine has had. Vblank is the tick for the *UART*, which
' cannot raise an interrupt of its own -- the core sees
' `irq | vid_irq | ps2_irq` and nothing carries the UART to it -- so the
' tick does the reading, exactly as the C64's jiffy IRQ scans a keyboard
' that cannot interrupt either.
'
' The keyboard is not in that position: KBD_CTRL bit 4 puts it on the
' same line, so a keypress is seen when it happens rather than up to a
' frame later. Both sources land in one handler and one ring.
POKE $FFFC, iisr AND 255
POKE $FFFD, iisr >> 8
' ...and the break button. The ROM's NMI handler went away with the
' overlay, so an uninstalled vector would send SW[0] into image bytes.
POKE $FFFA, inmi AND 255
POKE $FFFB, inmi >> 8
POKE VID_IRQ, $20                 ' enable the vertical blank interrupt
POKE KBD_CTRL, $11                 ' clear the keyboard FIFO and enable its
POKE KBD_CTRL, $10                 ' interrupt -- stale codes are not input
ASM
        ; User RAM and the system storage region above it, wiped in one
        ; pass to $7EFF: the relocating stub -- and the boot screen it
        ; painted from -- lived at $0200, and nothing of it may survive
        ; to be executed, LISTed or LOADed over. This is also what makes
        ; an empty program's memory actually empty.
        ;
        ; **This used to be two loops and the order mattered the other
        ; way round.** The workspace was the $FF00 page, which this loop
        ; could not reach, so it was cleared separately and `rseed` was
        ; seeded before the user-RAM wipe. With the region at $7DE9
        ; ([D67]) the one loop covers it, and seeding first would have
        ; the wipe zero the seed again -- a zeroed xorshift stays zero
        ; forever, so RND would have returned 0 for the life of the
        ; machine, quietly.
        ;
        ; Before EI either way, because the ISR writes the ring.
        LDW  X,#$0200
        CLR  R0
urwz:   ST   [X],R0
        INCW X
        MOV  R1,XH
        CMP  R1,#$7F
        BNE  urwz
        MOV  R0,#1              ; a zeroed xorshift stays zero forever
        ST   [rseed],R0
        EI
END ASM
CALL fsmount()
' The screen already shows the boot banner -- the stub painted it (and
' was just wiped). The cursor goes under it.
cy = 10
cx = 0
CALL showcur()
CALL setgeom()                  ' mode 0: the hardware cursor comes on
                                ' here, style 3 -- the C64's reverse
                                ' blink -- and only now that it is
                                ' placed
' The boot ROM lit the green LED when it found BOOT.BIN; the system is
' up now, so out it goes. Its whole duration is the relocation and this
' startup -- a blink, with no timer anywhere.
POKE LED, 0

DO
  k = getkey()
  IF PEEK(IRST) <> 0 THEN
    CALL doreset()
  END IF
  IF k = 13 THEN
    CALL enter(cy)
  ELSE
    IF k = K_LEFT THEN
      CALL curleft()
      CALL showcur()
    ELSE
      IF k = K_RIGHT THEN
        ' the C64's right: past the row's end, on to the next row --
        ' and at the bottom the screen scrolls
        IF cx < cols - 1 THEN
          cx = cx + 1
        ELSE
          cx = 0
          CALL dnrow()
        END IF
        CALL showcur()
      ELSE
        IF k = K_UP THEN
          IF cy > 0 THEN
            cy = cy - 1
          END IF
          CALL showcur()
        ELSE
          IF k = K_DOWN THEN
            CALL dnrow()
            CALL showcur()
          ELSE
            IF k = K_HOME THEN
              cx = 0
              cy = 0
              CALL showcur()
            ELSE
              IF k = K_END THEN
                CALL gotoend()
              ELSE
                IF k = 8 THEN
                  CALL backspace()
                ELSE
                  IF k = 127 THEN
                    CALL backspace()
                  ELSE
                    IF k = K_DEL THEN
                      CALL delchar()
                    ELSE
                      IF k = K_INS THEN
                        CALL insch()
                      ELSE
                        IF k > 31 THEN
                          IF k < 127 THEN
                            CALL emit(k)
                          END IF
                        END IF
                      END IF
                    END IF
                  END IF
                END IF
              END IF
            END IF
          END IF
        END IF
      END IF
    END IF
  END IF
LOOP WHILE 0 = 0
END

SUB gotoend()
  cx = cols - 1                 ' End: the row's edge. The scan for
  CALL showcur()                ' the last character paid 50 bytes the
END SUB                         ' mode-3 CLS needed more

' The editing ops work on the LOGICAL line: read it whole, edit the
' buffer, write it back. Three rows of 32 columns is the worst case,
' and one implementation covers every mode and both widths.
FUNCTION lpos() AS INT
  RETURN (cy - lstart(cy)) * cols + cx
END FUNCTION

SUB delchar()
  DIM p AS INT
  DIM k AS INT
  DIM r0 AS INT
  DIM n AS INT
  r0 = lstart(cy)
  n = lend(r0) - r0 + 1
  CALL readrow(cy)
  p = lpos()
  IF p >= llen THEN
    RETURN
  END IF
  k = p
  DO WHILE k < llen - 1
    lbuf(k) = lbuf(k + 1)
    k = k + 1
  LOOP
  llen = llen - 1
  CALL writelog(r0, n)
END SUB

' INS: open a one-character gap at the cursor -- the ruling's insert.
SUB insch()
  DIM p AS INT
  DIM k AS INT
  DIM r0 AS INT
  DIM n AS INT
  r0 = lstart(cy)
  n = lend(r0) - r0 + 1
  CALL readrow(cy)
  p = lpos()
  IF llen >= 80 THEN
    RETURN
  END IF
  k = llen
  DO WHILE k > p
    lbuf(k) = lbuf(k - 1)
    k = k - 1
  LOOP
  lbuf(p) = 32
  llen = llen + 1
  CALL writelog(r0, n)
END SUB

' Cursor one left, wrapping to the previous row's end -- the C64's
' left-at-column-0, and nothing at the very home.
SUB curleft()
  IF cx > 0 THEN
    cx = cx - 1
    RETURN
  END IF
  IF cy > 0 THEN
    cy = cy - 1
    cx = cols - 1
  END IF
END SUB

SUB backspace()
  IF cx = 0 THEN
    IF cont(cy) = 0 THEN
      RETURN
    END IF
    CALL curleft()
    CALL delchar()
    CALL showcur()
    RETURN
  END IF
  cx = cx - 1
  CALL delchar()
  CALL showcur()
END SUB

ASM
; ---- the keyword table. It is its own file because sw/asm.asm reads
; ---- it too -- the editor tokenises the inside of an ASM block, so the
; ---- assembler has to turn those bytes back into words.
        .include "toktab.asm"

; ---- commands, in the order docommand tests them

; ---- every error message, one table. Entries 0-18 are the
; interpreter's, indexed by ERR - 1; the tail is the editor's, reached
; through errmsg() by the same indices. One namespace, ready for a
; direct mode where the two report through one mouth.
RUNTAB:
        .asciz "SYNTAX"
        .asciz "FORS"
        .asciz "NO FOR"
        .asciz "COMPLEX"
        .asciz "OUT OF MEM"
        .asciz "VARS"
        .asciz "INDEX"
        .asciz "STR LEN"
        .asciz "TYPE"
        .asciz "ASM"
        .asciz "NO INSTR"
        .asciz "SYMBOL"
        .asciz "ERR"
        .asciz "BRANCH"
        .asciz "DIV BY 0"
        .asciz "LOOP"
        .asciz "CALL"
        .asciz "BREAK"
        .asciz "NO DATA"
        ; ---- from here, editor-only: the tables are one. The ? is the
        ; ---- whole ceremony; there is no ERROR suffix anywhere.
        .asciz "DISK FULL"
        .asciz "NO FILE"
        .byte 0

MSGFREE:
        .asciz " BYTES FREE"

MSGKFREE:
        .asciz "K FREE"

; ---- the bitmap console's glyph blitter. bfa/bva/binv/bstr in zero
; ---- page are its arguments; bpc picks the depth. One font row is
; ---- read through the VRAM port, complemented for the cursor, and
; ---- written back expanded -- 1:1, two bits to a byte through
; ---- nibtab, or one bit to a byte.
nibtab: .byte $00,$0F,$F0,$FF
bglyph: LD   R3,[$00D7]         ; grow: 8 font rows, or mode 3's 16
.bg:    PUSH R3
        LD   R0,[$00D2]         ; seek the font row
        ST   [VRAM_ADDR_L],R0
        LD   R0,[$00D3]
        ST   [VRAM_ADDR_H],R0
        LD   R1,[VRAM_DATA]
        LD   R0,[$00D6]
        XOR  R1,R0              ; the cursor's complement, or nothing
        LD   R0,[$00D4]         ; seek the cell row
        ST   [VRAM_ADDR_L],R0
        LD   R0,[$00D5]
        ST   [VRAM_ADDR_H],R0
        LD   R0,[$00A9]         ; bpc: 1, 4 or 8
        CMP  R0,#4
        BEQ  .b4
        CMP  R0,#8
        BEQ  .b8
        ST   [VRAM_DATA],R1         ; 1 bpp: the row goes in raw
        BRA  .bnx
.b4:    MOV  R3,#4              ; 4 bpp: two bits to a byte, four times
.b4l:   MOV  R2,#0
        ADD  R1,R1
        ADC  R2,R2
        ADD  R1,R1
        ADC  R2,R2
        LDW  X,#nibtab
        LD   R0,[X+R2]
        ST   [VRAM_DATA],R0
        SUB  R3,#1
        BNE  .b4l
        BRA  .bnx
.b8:    MOV  R3,#8              ; 8 bpp: one bit to a byte -- entry 15,
.b8l:   MOV  R0,#0              ; the seeded white; 255 is unseeded
        ADD  R1,R1              ; black and the text would be invisible
        BCC  .b80
        MOV  R0,#$0F
.b80:   ST   [VRAM_DATA],R0
        SUB  R3,#1
        BNE  .b8l
.bnx:   LD   R0,[$00D2]         ; next font row
        ADD  R0,#1
        ST   [$00D2],R0
        LD   R0,[$00D3]
        ADC  R0,#0
        ST   [$00D3],R0
        LD   R0,[$00D4]         ; next cell row: one stride down
        LD   R1,[$00D8]
        ADD  R0,R1
        ST   [$00D4],R0
        LD   R0,[$00D5]
        LD   R1,[$00D9]
        ADC  R0,R1
        ST   [$00D5],R0
        POP  R3
        SUB  R3,#1
        BEQ  .bgd               ; the body outgrew a short branch
        JMP  .bg
.bgd:   RET

; ---- the filesystem, whole. Its state lives at $0074, in page 0 with
; ---- the interpreter's, so that page 1 is the CPU stack alone.
        .include "fs.asm"

; ---------------------------------------------------------------------
; The input ring, and the interrupt that fills it.
;
; **Neither the editor nor the interpreter reads a device.** The C64's
; STOP routine "does not scan the keyboard" -- the 60 Hz jiffy IRQ sets
; a flag and BASIC polls it -- and the BBC's 100 Hz interrupt sets the
; escape flag the same way. Copying that is what lets a *running*
; program be stopped at all: it cannot poll, so something else must.
;
; The vertical blank is the tick for the UART, which cannot raise an
; interrupt (docs/04-system.md section 6: the core sees
; `irq | vid_irq | ps2_irq` and nothing carries the UART to it). So the
; tick does the reading, which is the C64's shape exactly -- its jiffy
; IRQ scans a keyboard that cannot interrupt either.
;
; The PS/2 port *is* on that line, through KBD_CTRL bit 4, so a keypress
; is handled when it happens. Both sources end in the same ring and
; nothing above here can tell which wire a key came in on.
;
; Sixteen bytes, which is the UART's own FIFO depth. At 115200 a full
; line arrives faster than 60 Hz can drain it, so a host that streams
; will still overrun -- a person typing never will, and the harness
; waits for the ring to empty between chunks.
IRSIZE  = 16
; The ring, the keyboard state and the interpreter's workspace are all
; in sw/zp.asm's system storage region now ([D67]). They lived in the
; $FF00 page, which the I/O page has since moved on top of -- and which
; was outside the boot ROM's clear, so `init` had to zero it by hand.
; The region is below $7EE0, inside what the ROM already clears.
;
; kbd.asm declares none of its own state, because the same source is
; assembled into the boot ROM where a `.byte` would land in ROM and
; could never be written -- so the includer names them, and the ROM's
; monitor names its own copies at MVARS instead.

; The break button. SW[0]'s NMI lands here now that BASIC owns the
; machine: the ROM's bare-RETI handler went away with the overlay, and
; an unhandled NMI executed whatever image bytes sat at the stale
; vector -- a break that half worked and an interpreter that needed a
; reboot. One flag, the same one Ctrl+Pause and the serial Ctrl-C set,
; so every way of asking for a break is the same break.
inmi:   PUSH R0
        ; Ctrl+Esc arrives here too -- the keyboard raises NMI for it and
        ; latches a flag saying which it was, so the break button and the
        ; restart chord share one unmaskable path and are told apart by
        ; asking. Acknowledged by writing the bit back, the shape
        ; VID_IRQ and UART_STAT use.
        LD   R0,[KBD_MOD]
        BTST R0,#$08
        BEQ  .brk
        MOV  R0,#$08
        ST   [KBD_MOD],R0
        MOV  R0,#1
        ST   [irst],R0          ; the editor's loop does the restart
.brk:   MOV  R0,#1
        ST   [ibreak],R0
        POP  R0
        RETI

iisr:   PUSH R0
        PUSH R1
        PUSHW X
        MOV  R0,#$22            ; acknowledge vblank, keep it enabled
        ST   [VID_IRQ],R0
        LD   R0,[frames]        ; the tick TIMER reads and VSYNC waits on
        ADD  R0,#1
        ST   [frames],R0
        LD   R0,[frames+1]      ; LD leaves C alone, so the carry rides
        ADC  R0,#0
        ST   [frames+1],R0
.more:  LD   R0,[UART_STAT]         ; UART_STAT: anything waiting?
        BTST R0,#$01
        BEQ  .kbd
        LD   R0,[UART_DATA]         ; taking it is the only way to see it
        CMP  R0,#$03            ; Ctrl-C, the serial console's Break
        BNE  .keep
.stop:  MOV  R0,#1
        ST   [ibreak],R0        ; the flag the interpreter polls
        BRA  .more
.keep:  CALL irpush
        BRA  .more

        ; The keyboard. Raw Set 2 arrives and kbd.asm turns it into a
        ; key, or into nothing at all for a prefix, a release or a
        ; shift. Ctrl+Pause decodes to $03, so the Break key and the
        ; serial console's Ctrl-C are the same byte and stop a program
        ; through the same test above.
.kbd:   LD   R0,[KBD_STAT]         ; KBD_STAT
        BTST R0,#$01
        BEQ  .done
        LD   R0,[KBD_DATA]         ; KBD_DATA, read has a side effect
        CALL scancode
        TST  R0
        BEQ  .kbd
        CMP  R0,#$03
        BEQ  .stop
        CALL irpush
        BRA  .kbd
.done:  POPW X
        POP  R1
        POP  R0
        RETI

; irpush -- R0 into the ring. Both inputs come through here.
irpush: LD   R1,[irhead]
        LDW  X,#irring
        ADDW X,R1
        ST   [X],R0
        ADD  R1,#1
        AND  R1,#15
        ST   [irhead],R1
        RET

; ---- the interpreter. Written without .org for exactly this: every
; ---- address in the image is relative and nothing hardcodes one, so
; ---- joining it here shifts everything and breaks nothing.
;
; zp.asm comes first and exactly once; interp.asm does not include it,
; because more than one copy would redefine every name.
;
; **asm.asm is not here any more** -- see [D63]. The on-machine
; assembler was never wired up: nothing in the interpreter ever invoked
; it, so no ASM block was ever assembled and no label was ever defined.
; It cost 2,886 bytes of the image and 38 bytes of page 0, and page 0 is
; the resource with no slack anywhere. The file stays in the tree, and
; tools/cool8asm.py is the assembler now -- assemble on the host, load
; the bytes, and reach them with SYS.
        .include "zp.asm"
        .include "interp.asm"
        .include "ed.asm"

; ---- floating point, resident. [D63] spent the assembler's 2,886 bytes
; ---- on this: the package that was a loadable library in D62 is part
; ---- of the system now, so SIN, LOG, SQR and ^ are ordinary functions
; ---- and a float can appear in an expression.
        .include "fp.asm"
        .include "fpbas.asm"

; ---- the keyboard, the same source the boot ROM's monitor is built
; ---- from. It cannot be shared at run time: this image ends at $F20A,
; ---- so its last 523 bytes are under the ROM window and turning ROMEN
; ---- on to call into the ROM would hide those bytes from the CPU.
; ---- kdown.asm is the half the monitor does not want, and the reason
; ---- kdset/kdclr are the includer's rather than kbd.asm's own.
        .include "kbd.asm"
        .include "keymap.asm"
        .include "kdown.asm"
END ASM
