; ---------------------------------------------------------------------
; io.asm -- the I/O page, generated by tools/ioregs.py.
;
; **Do not edit.** The offsets are read out of the Verilog localparams
; that decode them (rtl/soc/*.v), the base is IO_BASE in the generator,
; and `poe check` fails if this file is stale.
;
; Every address is IOBASE + offset rather than a literal, so the page
; can move by changing one constant on each side -- which is the whole
; point: it used to be sixty literals across five files ([D67]).
; ---------------------------------------------------------------------

IOBASE  = $FF00

; ---- cool8_flash.v
FLS_ADDR_L  = IOBASE + $88       ; SPI flash address, low
FLS_ADDR_M  = IOBASE + $89       ; SPI flash address, middle
FLS_ADDR_H  = IOBASE + $8A       ; SPI flash address, high
FLS_DATA    = IOBASE + $8B       ; read the byte at that address
FLS_CTRL    = IOBASE + $8C       ; start a read, select the device
FLS_STAT    = IOBASE + $8D       ; busy and done
FLS_WDATA   = IOBASE + $8E       ; byte to program
FLS_WCTRL   = IOBASE + $8F       ; program and erase control

; ---- cool8_pixport.v
PIX_X_L     = IOBASE + $34       ; plot X, low
PIX_X_H     = IOBASE + $35       ; plot X, high
PIX_Y_L     = IOBASE + $36       ; plot Y, low
PIX_Y_H     = IOBASE + $37       ; plot Y, high
PIX_DATA    = IOBASE + $38       ; write plots the pixel at X,Y, then X advances
PIX_DATA_Y  = IOBASE + $39       ; write plots the pixel at X,Y, then Y advances

; ---- cool8_ps2.v
KBD_STAT    = IOBASE + $40       ; PS/2 status: byte ready, error
KBD_DATA    = IOBASE + $41       ; the scancode; reading clears ready
KBD_CTRL    = IOBASE + $42       ; interrupt enable and reset
KBD_TX      = IOBASE + $43       ; byte to send to the keyboard
KBD_MOD     = IOBASE + $44       ; modifier state, decoded in hardware

; ---- cool8_snd.v
SND_IDX     = IOBASE + $50       ; voice to address
SND_DATA    = IOBASE + $51       ; that voice's registers

; ---- cool8_soc.v
SYS_CTRL    = IOBASE + $00       ; system control: reset and bank selects
SYS_STAT    = IOBASE + $02       ; system status, read-only
LED         = IOBASE + $03       ; the board's LEDs, one per bit
UART_STAT   = IOBASE + $70       ; transmit ready, receive ready
UART_DATA   = IOBASE + $71       ; read receives, write transmits
UART_DIV_L  = IOBASE + $72       ; baud divisor, low
UART_DIV_H  = IOBASE + $73       ; baud divisor, high
LDR_CTRL    = IOBASE + $80       ; boot loader control
LDR_STAT    = IOBASE + $81       ; boot loader status

; ---- cool8_sprite.v
SPR_IDX     = IOBASE + $2A       ; sprite to address
SPR_DATA    = IOBASE + $2B       ; that sprite's attribute bytes
SPR_CTRL    = IOBASE + $2C       ; per-sprite enable bits

; ---- cool8_vport.v
VRAM_ADDR_L = IOBASE + $26       ; indirect VRAM address, low
VRAM_ADDR_H = IOBASE + $27       ; indirect VRAM address, high
VRAM_STEP   = IOBASE + $28       ; added to the address after each access
VRAM_DATA   = IOBASE + $29       ; the byte at that address; access auto-steps

; ---- cool8_vregs.v
VID_MODE    = IOBASE + $10       ; screen mode, low nibble
VID_CTRL    = IOBASE + $11       ; display enable, sprite enable, blanking
VID_BASE_L  = IOBASE + $12       ; character/bitmap base, low
VID_BASE_H  = IOBASE + $13       ; character/bitmap base, high
VID_STRIDE_L = IOBASE + $14       ; bytes per row, low
VID_STRIDE_H = IOBASE + $15       ; bytes per row, high
VID_SCX_L   = IOBASE + $16       ; horizontal scroll, low
VID_SCX_H   = IOBASE + $17       ; horizontal scroll, high
VID_SCY_L   = IOBASE + $18       ; vertical scroll, low
VID_SCY_H   = IOBASE + $19       ; vertical scroll, high
VID_BORDER  = IOBASE + $1A       ; border colour index
VID_RASTER  = IOBASE + $1B       ; current raster line, read-only
VID_RCMP    = IOBASE + $1C       ; raster line to compare against
VID_IRQ     = IOBASE + $1D       ; interrupt enable and acknowledge
PAL_IDX     = IOBASE + $1E       ; palette entry to address
PAL_DATA    = IOBASE + $1F       ; that entry's colour
VID_PAT_L   = IOBASE + $20       ; pattern/tile base, low
VID_PAT_H   = IOBASE + $21       ; pattern/tile base, high
CUR_X       = IOBASE + $22       ; text cursor column
CUR_Y       = IOBASE + $23       ; text cursor row
CUR_CTRL    = IOBASE + $24       ; cursor enable and blink
TMR_L       = IOBASE + $2D       ; frames since reset, low byte
TMR_M       = IOBASE + $2E       ; ...middle byte
TMR_H       = IOBASE + $2F       ; ...high byte
VID_DBASE_H = IOBASE + $30       ; display base override, high byte -- the fetch engine scans from {this,$00} while VID_CTRL bit 6 is set, so VID_BASE can point drawing at a hidden page (D92)

