' ---------------------------------------------------------------------
' io.bas -- the I/O page for COOL8 BASIC, generated by tools/ioregs.py.
'
' **Do not edit.** Same source as sw/io.asm: the Verilog localparams in
' rtl/soc/*.v that decode these addresses. `poe check` fails if stale.
'
' CONST and not EXTERN on purpose -- a CONST folds and an EXTERN does
' not, which was worth 89 bytes of image ([D67]).
' ---------------------------------------------------------------------

CONST SYS_CTRL     = $FF00       ' system control: reset and bank selects
CONST SYS_STAT     = $FF02       ' system status, read-only
CONST LED          = $FF03       ' the board's LEDs, one per bit
CONST VID_MODE     = $FF10       ' screen mode, low nibble
CONST VID_CTRL     = $FF11       ' display enable, sprite enable, blanking
CONST VID_BASE_L   = $FF12       ' character/bitmap base, low
CONST VID_BASE_H   = $FF13       ' character/bitmap base, high
CONST VID_STRIDE_L = $FF14       ' bytes per row, low
CONST VID_STRIDE_H = $FF15       ' bytes per row, high
CONST VID_SCX_L    = $FF16       ' horizontal scroll, low
CONST VID_SCX_H    = $FF17       ' horizontal scroll, high
CONST VID_SCY_L    = $FF18       ' vertical scroll, low
CONST VID_SCY_H    = $FF19       ' vertical scroll, high
CONST VID_BORDER   = $FF1A       ' border colour index
CONST VID_RASTER   = $FF1B       ' current raster line, read-only
CONST VID_RCMP     = $FF1C       ' raster line to compare against
CONST VID_IRQ      = $FF1D       ' interrupt enable and acknowledge
CONST PAL_IDX      = $FF1E       ' palette entry to address
CONST PAL_DATA     = $FF1F       ' that entry's colour
CONST VID_PAT_L    = $FF20       ' pattern/tile base, low
CONST VID_PAT_H    = $FF21       ' pattern/tile base, high
CONST CUR_X        = $FF22       ' text cursor column
CONST CUR_Y        = $FF23       ' text cursor row
CONST CUR_CTRL     = $FF24       ' cursor enable and blink
CONST CUR_LINES    = $FF25       ' first and last scanline of the cursor cell
CONST VRAM_ADDR_L  = $FF26       ' indirect VRAM address, low
CONST VRAM_ADDR_H  = $FF27       ' indirect VRAM address, high
CONST VRAM_STEP    = $FF28       ' added to the address after each access
CONST VRAM_DATA    = $FF29       ' the byte at that address; access auto-steps
CONST SPR_IDX      = $FF2A       ' sprite to address
CONST SPR_DATA     = $FF2B       ' that sprite's attribute bytes
CONST SPR_CTRL     = $FF2C       ' per-sprite enable bits
CONST PIX_X_L      = $FF34       ' plot X, low
CONST PIX_X_H      = $FF35       ' plot X, high
CONST PIX_Y_L      = $FF36       ' plot Y, low
CONST PIX_Y_H      = $FF37       ' plot Y, high
CONST PIX_DATA     = $FF38       ' write plots the pixel at X,Y
CONST KBD_STAT     = $FF40       ' PS/2 status: byte ready, error
CONST KBD_DATA     = $FF41       ' the scancode; reading clears ready
CONST KBD_CTRL     = $FF42       ' interrupt enable and reset
CONST KBD_TX       = $FF43       ' byte to send to the keyboard
CONST KBD_MOD      = $FF44       ' modifier state, decoded in hardware
CONST SND_IDX      = $FF50       ' voice to address
CONST SND_DATA     = $FF51       ' that voice's registers
CONST UART_STAT    = $FF70       ' transmit ready, receive ready
CONST UART_DATA    = $FF71       ' read receives, write transmits
CONST UART_DIV_L   = $FF72       ' baud divisor, low
CONST UART_DIV_H   = $FF73       ' baud divisor, high
CONST LDR_CTRL     = $FF80       ' boot loader control
CONST LDR_STAT     = $FF81       ' boot loader status
CONST FLS_ADDR_L   = $FF88       ' SPI flash address, low
CONST FLS_ADDR_M   = $FF89       ' SPI flash address, middle
CONST FLS_ADDR_H   = $FF8A       ' SPI flash address, high
CONST FLS_DATA     = $FF8B       ' read the byte at that address
CONST FLS_CTRL     = $FF8C       ' start a read, select the device
CONST FLS_STAT     = $FF8D       ' busy and done
CONST FLS_WDATA    = $FF8E       ' byte to program
CONST FLS_WCTRL    = $FF8F       ' program and erase control
