; ---------------------------------------------------------------
; org.asm -- GENERATED by tools/memmap.py. Do not edit.
;
; The image is top-aligned under the I/O page: it ends at $FEFF
; and starts at $BB8F, because it is 17265 bytes long.
;
; This was a written-down $A000, chosen when the system was
; compiled BASIC and 23,528 bytes. A constant picked for a size
; the software no longer is leaves the difference stranded above
; the image, where nothing can reach it. Derived, the boundary
; follows: whatever BASIC stops using appears below it.
; ---------------------------------------------------------------
        .org  $BB8F

