; ---------------------------------------------------------------
; org.asm -- GENERATED by tools/memmap.py. Do not edit.
;
; The image is top-aligned under the I/O page: it ends at $FEFF
; and starts at $BBBF, because it is 17217 bytes long.
;
; This was a written-down $A000, chosen when the system was
; compiled BASIC and 23,528 bytes. A constant picked for a size
; the software no longer is leaves the difference stranded above
; the image, where nothing can reach it. Derived, the boundary
; follows: whatever BASIC stops using appears below it.
; ---------------------------------------------------------------
        .org  $BBBF

; The gap top-aligning leaves, between the screen and the image.
; It is the heap's: arrays and strings allocate down from here
; instead of down from USERTOP, so a DIM no longer competes with
; the program text for the same bytes. It grows when BASIC
; shrinks, which is the whole point of deriving the origin.
HEAPTOP = $BBBE                 ; the heap's first byte, growing down
HEAPBOT = $A000                 ; and the screen is the floor
