; ---------------------------------------------------------------------
; sysbot.asm -- GENERATED by tools/memmap.py. Do not edit.
;
; The floor of system storage is the lowest claim anywhere in sw/,
; which no single module can name: an equate may only refer to a
; symbol already seen, and the module holding the lowest claim is not
; the first one read. Written as a number for that reason, and
; checked against the claims by `poe check`.
;
; The user region ends at the text map. After [D69] the map,
; system storage and the image are all above it, so $0200 runs
; contiguously to USERTOP and the heap comes down from the top
; of the same region the program grows up through.
;
; Lowest system claim: MAINK at $B400, in main.asm.
; System storage spans $B400-$B669, 618 bytes claimed.
; ---------------------------------------------------------------------
SYSBOT  = $A000                 ; the first byte not a program's
USERTOP = $9FFF                 ; the last byte a program may use
