; ---------------------------------------------------------------------
; sysbot.asm -- GENERATED by tools/memmap.py. Do not edit.
;
; The floor of system storage is the lowest claim anywhere in sw/,
; which no single module can name: an equate may only refer to a
; symbol already seen, and the module holding the lowest claim is not
; the first one read. Written as a number for that reason, and
; checked against the claims by `poe check`.
;
; The user region ends at the text map. After [D69] the map,
; system storage and the image are all above it, so $0200 runs
; contiguously to USERTOP and the heap comes down from the top
; of the same region the program grows up through.
;
; Lowest system claim: MAINK at $B400, in main.asm.
; System storage spans $B400-$B669, 618 bytes claimed.
;
; The map's address and pitch are here for the same reason, and
; because they have to reach the boot ROM as well as BASIC. They
; did not, once: [D70] moved the map from $8000 to $A000 and
; sw/boot.asm and sw/monitor.asm kept their own $8000, so the
; ROM banner and the whole monitor drew into user RAM while the
; display read somewhere else. Every suite passed -- the monitor's
; gate reads the serial line, and the cosim compares two models
; that were both looking at the right address and seeing nothing.
; ---------------------------------------------------------------------
SYSBOT  = $A000                 ; the first byte not a program's
USERTOP = $9FFF                 ; the last byte a program may use
SCREEN  = $A000                 ; the text map, 5120 bytes
CSTRIDE = 160                   ; bytes per map row: 80 cells of char+attr
