; ---------------------------------------------------------------------
; sysbot.asm -- GENERATED by tools/memmap.py. Do not edit.
;
; The floor of system storage is the lowest claim anywhere in sw/,
; which no single module can name: an equate may only refer to a
; symbol already seen, and the module holding the lowest claim is not
; the first one read. Written as a number for that reason, and
; checked against the claims by `poe check`.
;
; Lowest claim: MAINK at $7C76, in main.asm.
; The region spans $7C76-$7EDF, 618 bytes claimed.
; ---------------------------------------------------------------------
SYSBOT  = $7C76                 ; the lowest claim in sw/
USERTOP = $7C75                 ; the last byte a program may use
