; ---------------------------------------------------------------------
; tokens.asm -- the keyword token values, generated by tools/vocab.py.
;
; **Do not edit.** The values are TOKTAB's own order: the first entry
; is $80 and each one after it is the next byte. `poe check` fails if
; this file is stale, so the table can be reordered by rebuilding.
; ---------------------------------------------------------------------

K_PRINT    = $80
K_SUB      = $81
K_FLT      = $82
K_DIM      = $83
K_RUN      = $84
K_FOR      = $85
K_NEXT     = $86
K_TO       = $87
K_DO       = $88
K_LOOP     = $89
K_WHILE    = $8A
K_UNTIL    = $8B
K_EXIT     = $8C
K_IF       = $8D
K_THEN     = $8E
K_ELSE     = $8F
K_ELSEIF   = $90
K_END      = $91
K_RETURN   = $92
K_CALL     = $93
K_AS       = $94
K_INT      = $95
K_BYTE     = $96
K_PEEK     = $97
K_POKE     = $98
K_AND      = $99
K_OR       = $9A
K_XOR      = $9B
K_CARD     = $9C
K_AT       = $9D
K_SYS      = $9E
K_EXTERN   = $9F
K_INCLUDE  = $A0
K_INLINE   = $A1
K_GOTO     = $A2
K_WEND     = $A3
K_NUM      = $A4
K_MODE     = $A5
K_VSYNC    = $A6
K_SCROLL   = $A7
K_PALETTE  = $A8
K_SPRITE   = $A9
K_VPOKE    = $AA
K_SOUND    = $AB
K_HLINE    = $AC
K_PLOT     = $AD
K_LINE     = $AE
K_INPUT    = $AF
K_DATA     = $B0
K_READ     = $B1
K_RESTORE  = $B2
K_STEP     = $B3
K_ON       = $B4
K_TILE     = $B5
K_CLG      = $B6
K_PITCH    = $B7
K_GTEXT    = $B8
K_LIST     = $B9
K_NEW      = $BA
K_FREE     = $BB
K_RENUM    = $BC
K_DELETE   = $BD
K_CLS      = $BE
K_SAVE     = $BF
K_LOAD     = $C0
K_DIR      = $C1
K_ERA      = $C2
K_COMPACT  = $C3
K_DRIVE    = $C4
K_REM      = $C5
K_FLT      = $C6
K_CLEAR    = $C7
K_LOCAL    = $C8
K_TAB      = $C9
K_SPC      = $CA
K_PAUSE    = $CB
K_CONT     = $CC
K_NOT      = $CD

NTOK    = 78                    ; keywords, $80-$CD
T_LIT   = K_NUM                 ; the stored-number marker, as tokenise writes it
