; ---------------------------------------------------------------------
; tokflag.asm -- what each keyword does to the tokeniser and to
; RENUMBER, generated by tools/vocab.py. One byte per keyword, in
; TOKTAB order, so token $80+n is TOKFLG+n.
;
; **Do not edit.** The flags are declared in vocab.py because they are a
; decision per keyword; this file is how the machine sees them.
; ---------------------------------------------------------------------

F_VERB  = $01                   ; rest of the line is verbatim: REM
F_LINE  = $02                   ; line numbers follow: GOTO, THEN, LIST

TOKFLG:
        .byte 0                ; $80 PRINT
        .byte 0                ; $81 SUB
        .byte 0                ; $82 !
        .byte 0                ; $83 DIM
        .byte 0                ; $84 RUN
        .byte 0                ; $85 FOR
        .byte 0                ; $86 NEXT
        .byte 0                ; $87 TO
        .byte 0                ; $88 DO
        .byte 0                ; $89 LOOP
        .byte 0                ; $8A WHILE
        .byte 0                ; $8B UNTIL
        .byte 0                ; $8C EXIT
        .byte 0                ; $8D IF
        .byte F_LINE           ; $8E THEN
        .byte 0                ; $8F ELSE
        .byte 0                ; $90 ELSEIF
        .byte 0                ; $91 END
        .byte 0                ; $92 RETURN
        .byte 0                ; $93 CALL
        .byte 0                ; $94 AS
        .byte 0                ; $95 INT
        .byte 0                ; $96 BYTE
        .byte 0                ; $97 PEEK
        .byte 0                ; $98 POKE
        .byte 0                ; $99 AND
        .byte 0                ; $9A OR
        .byte 0                ; $9B XOR
        .byte 0                ; $9C CARD
        .byte 0                ; $9D AT
        .byte 0                ; $9E SYS
        .byte 0                ; $9F EXTERN
        .byte 0                ; $A0 INCLUDE
        .byte 0                ; $A1 INLINE
        .byte F_LINE           ; $A2 GOTO
        .byte 0                ; $A3 WEND
        .byte 0                ; $A4 ?
        .byte 0                ; $A5 MODE
        .byte 0                ; $A6 VSYNC
        .byte 0                ; $A7 SCROLL
        .byte 0                ; $A8 COLOR
        .byte 0                ; $A9 CURSOR
        .byte 0                ; $AA VPOKE
        .byte 0                ; $AB SOUND
        .byte 0                ; $AC HLINE
        .byte 0                ; $AD PLOT
        .byte 0                ; $AE LINE
        .byte 0                ; $AF INPUT
        .byte 0                ; $B0 DATA
        .byte 0                ; $B1 READ
        .byte 0                ; $B2 RESTORE
        .byte 0                ; $B3 STEP
        .byte 0                ; $B4 ON
        .byte 0                ; $B5 TILE
        .byte 0                ; $B6 CLG
        .byte 0                ; $B7 PITCH
        .byte 0                ; $B8 GTEXT
        .byte F_LINE           ; $B9 LIST
        .byte 0                ; $BA NEW
        .byte 0                ; $BB FREE
        .byte 0                ; $BC RENUM
        .byte F_LINE           ; $BD DELETE
        .byte 0                ; $BE CLS
        .byte 0                ; $BF SAVE
        .byte 0                ; $C0 LOAD
        .byte 0                ; $C1 DIR
        .byte 0                ; $C2 ERA
        .byte 0                ; $C3 COMPACT
        .byte 0                ; $C4 DRIVE
        .byte F_VERB           ; $C5 REM
        .byte 0                ; $C6 !
        .byte 0                ; $C7 CLEAR
        .byte 0                ; $C8 LOCAL
        .byte 0                ; $C9 TAB
        .byte 0                ; $CA SPC
        .byte 0                ; $CB PAUSE
        .byte 0                ; $CC CONT
        .byte 0                ; $CD NOT
        .byte 0                ; $CE STOP
        .byte 0                ; $CF OPENIN
        .byte 0                ; $D0 CLOSE
        .byte 0                ; $D1 ERROR
        .byte 0                ; $D2 GOSUB
