; ---------------------------------------------------------------------
; zp.asm -- page 0, and who owns which byte of it.
;
; Page 0 is not faster than anywhere else: COOL8 has no zero-page
; addressing mode (D6), so $0040 costs exactly what $9040 costs. What
; this layout buys is that **page 1 holds the CPU stack and nothing
; else** -- sw/boot.asm:339 sets SP to $0200 and nothing moves it, so
; the stack grows down through page 1, and the filesystem's workspace
; used to sit at $0100 where a deep expression would quietly corrupt a
; mounted volume. That is the arrangement the BBC Micro used, with its
; filing system workspace in page 0 below the stack.
;
;   $0000-$0011   DO/LOOP's own stack
;   $0014-$0022   the interpreter
;   $0023-$0026   multiply scratch
;   $0027-$0033   long names: the table, the heap floor, the scan buffer
;   $0040-$0073   VARS, A-Z, two bytes each
;   $0074-$00A1   sw/fs.asm's FSVARS, 46 bytes
;   $00A2-$00A3   FDEPTH and EDEPTH
;   $00A4         SDIG, moved here when NBUF took its seventh byte
;   $00A5-$00D9   free, 53 bytes -- **the editor's, until it stopped
;                 being compiled BASIC**. `cols`, `rows`, `gkind`,
;                 `curph`, `rpl`, `bpc`, `gbase`, `gs8`, `glim`, `cont`,
;                 `blb`, `bfa`, `bva`, `binv`, `grow` and `bstr` were
;                 pinned here by `DIM x AT $00xx` in sw/basic.bas, which
;                 [D68] deleted. sw/console.asm holds their equivalents
;                 at $7DAF and up, where they are claims the map can see
;                 rather than allocations nothing could.
;   $00DA-$00FE   floating point's operand stack (was the assembler)
;   $00FF         SFRAC
;   $0100-$01FF   the CPU stack, growing down from $0200
;
; **This comment is not the source of truth and has been wrong.** It
; still listed FORSTK in page 0 long after it left. `tools/memmap.py`
; holds the map machine-readably, `poe check` verifies it against the
; equates below, and it also refuses two names on one byte -- which is
; the mistake page 0 invites, being full and tempting. The equates in
; this file are what the assembler reads and remain authoritative; the
; prose above is a convenience that a check now keeps honest.
;
; **Include this exactly once**, before interp.asm or asm.asm. Both
; assume it and neither includes it, because in the built system both
; are present and a second copy would redefine every name.
; ---------------------------------------------------------------------

; The I/O page, generated by tools/ioregs.py from the Verilog that
; decodes it. It comes in here because every program that includes this
; file also talks to the hardware, and because the addresses should be
; written down in exactly one place ([D67]). The include is idempotent,
; so fs.asm may ask for it too.
        .include "io.asm"

; ---- DO/LOOP.
;
; A stack of its own, in the BBC Micro's shape: it gave FOR, REPEAT and
; GOSUB one each and said so when one filled, rather than merging them
; onto the processor stack the way BBC BASIC (86) did. The processor
; stack here is 256 bytes shared with a recursive evaluator, so the
; Micro is the one to copy.
;
; No cached innermost frame, unlike FOR. FOR pays per *iteration* and
; the cache is most of why nesting is free; a DO pays twice per loop, at
; the top and at the bottom, and the indexing is lost in the test.
DOFR    = 4                     ; where the body starts, and its record
MAXDO   = 4
DOSTK   = $0000                 ;: 16 MAXDO frames of DOFR
DDEPTH  = $0010                 ;: 1 loops open, 0 = none
DNEST   = $0011                 ;: 1 nesting seen while skipping one
BENT    = $0012                 ;: 2 the builtin table entry being tried

; ---- the interpreter
LREC    = $0014                 ;: 2 the current line record
PEND    = $0016                 ;: 2 progend, snapshot at RUN
ERR     = $0018                 ;: 1 nonzero stops the program
TVAR    = $0019                 ;: 1 a variable index, doubled

; The innermost FOR, held in fixed locations rather than at the top of
; the stack, so that nesting costs nothing per iteration.
LVAR    = $001A                 ;: 1 the FOR variable, doubled
LLIM    = $001B                 ;: 2 its limit
LBODY   = $001D                 ;: 2 where its body starts
LLINE   = $001F                 ;: 2 and which line that was
LSTEP   = $0021                 ;: 2 the step, 1 unless STEP said otherwise.
                                ;    Contiguous with the four above: fpush
                                ;    block-copies the frame, so the frame
                                ;    is an address range, not a struct.
FDEPTH  = $00A2                 ;: 1 FOR loops active, 0 = none. Moved
SFRAC   = $00FF                 ;: 1 VAL's fraction digits, $FF until a
                                ;    '.' is met. Doubles as the flag and
                                ;    the count, which is why $FF rather
                                ;    than a second byte for "seen one".
                                ;    **This byte has now been wrong
                                ;    twice.** It was $00A4, which is the
                                ;    editor's `cols`, so every snumi told
                                ;    the editor its screen was 254 columns
                                ;    wide. It was moved to $00B1 into what
                                ;    this file called a 31-byte free run --
                                ;    and $00B1 is `cont(1)`, because
                                ;    `DIM cont(31) AS BYTE AT $00B0` spans
                                ;    $00B0-$00CF and nothing could see an
                                ;    extent. $00FF is the last free byte in
                                ;    the page, and it is free by
                                ;    derivation now rather than by claim:
                                ;    tools/memmap.py reads every `;:` here
                                ;    and every `AT` in sw/*.bas and refuses
                                ;    a byte with two owners. [D67] moves
                                ;    this out of page 0 entirely.
EDEPTH  = $00A3                 ;: 1 expression nesting -- STEP took their
                                ;    old $21-$22, and $12-$13 is BENT's,
                                ;    which the first draft of this move
                                ;    sat on. They live in FORSTK's old
                                ;    ground, which is *not* free above
                                ;    $00A3: the editor is there.

MTMP    = $0023                 ;: 4 multiply scratch

; ---- long names.
;
; A-Z stay resident and stay the fast path; anything longer lives in a
; linearly-searched table of fixed 10-byte entries, so a slot number
; times NENT is its address and no walk is needed to index one. Six
; significant characters rather than five, because the assembler's
; labels are now BASIC variables ([D45](docs/01-decisions.md)) and
; `.done1`/`.done2` have to stay apart.
;
; **Seven now, and a builtin's name is why.** `isbuilt` matches an entry
; by comparing NLEN against its length and then that many bytes out of
; NBUF, so the longest name in `btab` sets the buffer -- and `STRING$`
; is seven characters. At six, its seventh compare read NLEN itself and
; the entry could never match, deterministically and silently. The same
; pressure that took this from five to six, one name later.
;
; NENT is derived rather than written down. It was the literal 12 while
; NSIG was 6, which is this project's most expensive shape: one number
; in two places, agreeing until the day one of them moves.
NSIG    = 7                     ; significant characters
NENT    = NSIG + 6              ; type, length, NSIG name bytes, value, aux
MAXNAME = 32

; A string variable's four bytes are BBC BASIC's descriptor exactly:
; where the characters are, how many there are, and how many were
; allocated. The last is what lets an assignment that fits reuse the
; space instead of abandoning it -- the entry's `value` is the address
; and `aux` is the two lengths.

NTAB    = $0027                 ;: 2 the table's base, fixed at RUN
NNAME   = $0029                 ;: 1 how many names are defined
HEAP    = $002A                 ;: 2 the heap floor; arrays grow down
NBUF    = $002C                 ;: 7 the identifier just scanned, folded
NLEN    = $0033                 ;: 1 how long it really was

; ---- strings.
;
; Every string expression is built in one accumulator and only an
; assignment copies out of it, which is BBC BASIC's STRACC and the
; reason concatenation needs no code at all: the second operand simply
; appends where the first stopped, and no intermediate ever reaches the
; heap.
SMAX    = 255                   ; as much as one byte of length allows
SACC    = $0034                 ;: 2 where the accumulator lives
SLEN    = $0036                 ;: 1 how much of it is in use
STYPE   = $0037                 ;: 1 1 when the last value was a string

; ---- division. One restoring pass gives the quotient and the
; remainder both, so MOD costs a dispatch entry and nothing else.
DVSR    = $0038                 ;: 2 the divisor, out of the way of the
                                ;    four registers the loop needs
DREM    = $003A                 ;: 2 what was left over
DSGN    = $003C                 ;: 1 bit 0 negates the quotient, bit 1
                                ;    the remainder

; ---- CALL/RETURN. A stack of its own again, and out in the user area
; because page 0 has no room left for eight frames -- which costs
; nothing, since there is no zero-page addressing mode to lose (D6).
; ---- calls, their parameters, and the values those parameters hid.
;
; **Both stacks live in the user's memory**, laid out above the name
; table by `main_pre`, and that is deliberate: 32 frames and 256 bytes
; of saves is 416 bytes, which does not fit the image's growth slack and
; is nothing at all against 40,448 ([D72]). Deep recursion costs the
; user's memory, which is the honest place for it to cost -- it is where
; BBC BASIC puts its stack too, descending from HIMEM.
CALLFR  = 5                     ; Y, LREC, and how many saves to undo
MAXCALL = 32                    ; nesting, which parameters make useful
LSTKSZ  = 256                   ; the save stack, 51 saved variables
CSAVESZ = 10                    ; CONT's record: where, and how deep
LSAVE   = 5                     ; a handle and the four bytes it hid
CSTK    = $003D                 ;: 2 where that stack lives
CDEPTH  = $003F                 ;: 1 calls active, 0 = none
; LDEPTH is in sw/console.asm, on one of the two bytes the hardware
; cursor gave back -- page 0 is full to the byte and that block was
; kept named rather than as a hole for exactly this.
;
; The save stack's base is **derived**, not stored: it sits directly
; above the call stack, so `lstk` computes CSTK + MAXCALL*CALLFR when
; it is wanted. Page 0 had exactly one byte left and this needed three;
; a stored pointer would have meant moving the map, which [D72] costs
; at forty claims. The call site during argument passing goes on the
; CPU stack for the same reason.
; SDIG sat at $003F until NBUF grew its seventh byte and pushed the run
; below it up by one. It is a scalar with no neighbours that care, which
; is what makes it the one to move rather than anything around it.
;
; **It went to $0074 first, and `memmap.check()` said no**: that byte is
; FSVARS, which lives in `fs.asm` and is invisible from here. The free
; run in page 0 is $00A4..$00D9, between EDEPTH and the float stack, and
; the tool is the only thing that knows -- three files claim this page
; and none of them can see the other two.
SDIG    = $00A4                 ;: 1 digits STR$ has stacked, or
                                ;    characters VAL has left

VARS    = $0040                 ;: 52 A-Z, two bytes each

FORFR   = 9                     ; bytes per FOR frame, STEP included
MAXFOR  = 8                     ; nesting levels, as it always was
; FORSTK left page 0 when STEP made the frame nine bytes: eight frames
; is 72 and the page had 56. It lives with the interpreter's other
; absolutes in sw/interp.asm now, and **$00A2-$00D9 is free** -- the
; first 56 bytes page 0 has ever gained back.

; ---- floating point's operand stack, in what the assembler left
;
; **$00DA-$00FF was the on-machine assembler's**, all 38 bytes of it,
; until [D63] took the assembler out of the image. This is what the
; space went to.
;
; `erel` pushes the left operand here before evaluating the right, so
; one frame is one pending operator and the depth is the expression's.
; Five bytes a frame: a type and four of value, the same size whether
; the value is a two-byte integer or a four-byte unpacked float, so the
; pop does not have to branch before it knows which.
;
; **Seven frames because thirty-eight bytes is what there was.** It sat
; at four in the image while the binding was being written, which was a
; size compromise and is paid off here: this is RAM the image no longer
; carries, and deeper besides. `fsav` refuses past the top with
; ?FORMULA TOO COMPLEX rather than writing off the end -- the same error
; `edin` gives, and for the same reason.
FSDEEP  = 7                     ; frames
FSTK    = $00DA                 ;: 35 FSDEEP frames of five
FSP     = $00FD                 ;: 1 the next free byte, an offset
FLTY    = $00FE                 ;: 1 the left's type, across fpair
; $00FF is SFRAC's, and the page is now full: one byte at $00AF and
; nothing else. `python tools/memmap.py` prints the free runs rather
; than this comment asserting them, which is the point of [D67] --
; every prose free-space figure this file has carried has been wrong.

; =====================================================================
; The system storage region -- $7DE9-$7EDF, ending where the CALL stack
; begins.
;
; **This was the $FF00 page until the I/O page moved on top of it**
; ([D67]). That page was never a good home: it is outside the boot ROM's
; $0000-$EFFF clear, so BASIC had to zero it itself, and it existed at
; all only because page 0 was full and page 0 was believed to be worth
; defending. [D6] says it is not -- there is no zero-page addressing
; mode, so $0040 costs exactly what $7E40 costs -- and so the workspace
; is simply RAM now, in one run, below the block the machine already
; protects for the CALL stack and the string accumulator.
;
; **Packed, with no slack, and the tool enforces that.** The region's
; floor is not a round number chosen for comfort: it is the lowest
; claim, so USERTOP is 247 bytes below the CALL stack because the claims
; are 247 bytes. Add one and the floor moves by exactly its size;
; `tools/memmap.py --check` refuses a gap, an overlap, and a `USERTOP`
; in sw/basic.bas that disagrees with the arithmetic. That is what makes
; "the user gets whatever is left" true rather than aspirational.
;
; The addresses are literal because the check reads them out of this
; file without assembling it. Relative expressions would compute the
; floor in the assembler and hide it from the one tool that has to see
; the whole map at once.

; ---- the keyboard, and the break key. sw/basic.bas's ASM block
; ---- declared these; the ROM's monitor has its own copies at MVARS
; ---- because the two are never resident together.
irring  = $B173                 ;: 16 the decoded-key ring the ISR fills
irhead  = $B183                 ;: 1 where the editor reads it
irtail  = $B184                 ;: 1 where the ISR writes it
kshift  = $B185                 ;: 1 either shift is down
kbrk    = $B186                 ;: 1 the next code is a release
kext    = $B187                 ;: 1 the next code had an $E0 before it
kdown   = $B188                 ;: 16 the key-down bitmap KEY() reads
ibreak  = $B198                 ;: 1 the break flag; ipoll reads it

; ---- the interpreter's own workspace.
frames  = $B199                 ;: 2 the frame counter TIMER reads
rseed   = $B19B                 ;: 2 the xorshift seed, 1 after init
garg    = $B19D                 ;: 10 up to five parsed arguments
lwk     = $B1A7                 ;: 10 dx, dy, err, sx, sy -- all words

; DIM's working set, overlaid on `lwk`.
;
; **Same bargain sw/prog.asm's command scratch makes**, and the same
; invariant written down: `lwk` is h_line's five words, one statement
; runs at a time, and `eval` reaches builtins only -- never another
; statement handler -- so nothing can be drawing a line while DIM is
; parsing its bounds. Ten bytes that would otherwise come out of the
; user's memory, in a region that is packed against the screen below and
; the CALL stack above with nowhere to grow.
;
; `aelem` deliberately does NOT use this. `A(B(1))` nests, so the outer
; call is mid-parse when the inner one runs; its working state goes on
; the CPU stack instead.
DTYPE   = lwk                   ; 0 integer, 1 float, 2 string
DRANK   = lwk+1                 ; dimensions seen so far
DTOT    = lwk+2                 ; the running product, in elements
DCNT    = lwk+4                 ; up to three counts, two bytes each
FORSTK  = $B1B1                 ;: 72 MAXFOR frames of FORFR
irst    = $B1F9                 ;: 1 the NMI handler's restart flag
DIRBUF  = $B1FA                 ;: 112 the staged direct line: a whole
                                ;    record -- $FFFF, len, tokens, 0 --
                                ;    built fresh by dodirect each time

; **The floor is the lowest claim anywhere, not the lowest claim here.**
; This said `irring`, which was true while sw/zp.asm held every claim in
; the region. sw/console.asm then claimed $7DAF-$7DE8 -- CONT, the
; mirror, the cursor and the whole of the geometry -- below `irring` and
; therefore inside what USERTOP was calling user space. `DIM A(3)` took
; ten bytes off the heap, got $7DDE-$7DE7, and wrote the array over
; CCY, CTOP, CCOLS, CROWS, CKIND and CLIM. The console then printed
; nothing at all, which reads exactly like a program that never printed.
;
; `tools/memmap.py --check` now refuses a SYSBOT that is not the lowest
; claim, so the next module to claim below this one fails the build
; instead of eating the screen at run time ([D67]).
; SYSBOT and USERTOP come from tools/memmap.py, which is the only place
; that can see every claim at once. Twice now this was an equate over a
; symbol -- irring, then CONT -- and twice the next module claimed
; below it and the heap was handed system storage to allocate over.
        .include "sysbot.asm"

; The two blocks the machine has always protected above USERTOP, named
; so that nothing has to write their addresses down. They carry no `;:`
; because they are not claims in the region: `pbuf` is deliberately laid
; over SACCBUF, and a claim would read as two owners rather than as the
; overlay it is.
; **Not `;:` claims, so `tools/memmap.py` cannot move them and the
; relocation script did not.** They are declared to memmap as regions
; instead, because fscmd's page buffer deliberately overlays SACCBUF and
; a claim would read as two owners. That exemption is exactly why they
; were the two addresses left behind when the map moved down a kilobyte
; -- SACC's pointer went on addressing where the accumulator used to be,
; and COMPACT, which writes a page through that buffer, was the suite
; that noticed.
;
; CSTKBUF is dead: the call stack lives in the user's memory now, above
; the name table, because 32 frames and 256 bytes of saves do not fit
; here ([D72]). Kept as a name so the region it holds open stays
; accounted for until something wants it.
; **CSTKBUF is gone, and its 32 bytes are the ones D80 needed.** It had
; been dead since the call stack moved into the user's memory, and it
; was holding the string accumulator 32 bytes higher than it had to sit
; -- which is 32 bytes off the gap between system storage and the image,
; the only number that was short. Reclaiming dead system storage is
; where those bytes come from. **Not from the user's region**: the text
; map does not move for this, and `FREE` still answers 39,424.
SACCBUF = $B26A                 ; the string accumulator, SMAX + 1

; ---- error codes. The interpreter's caller reads ERR; 255 is a clean
; ---- stop and everything else is a fault.
E_SYN   = 1                     ; ?SYNTAX ERROR
E_FORS  = 2                     ; ?TOO MANY FORS ERROR
E_NEXT  = 3                     ; ?NEXT WITHOUT FOR ERROR
E_DEEP  = 4                     ; ?FORMULA TOO COMPLEX ERROR
E_MEM   = 5                     ; ?OUT OF MEMORY ERROR
E_NAMES = 6                     ; ?TOO MANY VARIABLES ERROR
E_SUBS  = 7                     ; ?SUBSCRIPT ERROR
E_STR   = 8                     ; ?STRING TOO LONG ERROR
E_TYPE  = 9                     ; ?TYPE MISMATCH ERROR
E_ASYN  = 10                    ; ?SYNTAX ERROR, in an ASM line
E_AENC  = 11                    ; no encoding for that operand shape
E_ASYM  = 12                    ; undefined symbol
E_ARNG  = 14                    ; branch out of range
E_DIV0  = 15                    ; ?DIVISION BY ZERO ERROR
E_DOS   = 16                    ; ?TOO MANY DOS / ?LOOP WITHOUT DO
E_CALL  = 17                    ; ?NO SUCH SUB / ?RETURN WITHOUT CALL
E_STOP  = 18                    ; ?BREAK -- the user stopped it
E_DATA  = 19                    ; ?OUT OF DATA -- READ past the last DATA
; The two disk failures. They were `errmsg(19)` and `errmsg(20)` in the
; compiled editor -- indices into the tail of the same message table,
; reached by a call rather than by setting ERR. As ERR codes they index
; that tail through the same ERR-1 the interpreter's own errors use, so
; a failed SAVE now stops the statement the way every other error does
; instead of printing and carrying on ([D68]).
E_NOSPC = 20                    ; ?DISK FULL
E_NOFILE = 21                   ; ?NO SUCH FILE
E_REDIM = 22                    ; ?REDIM -- an array dimensioned twice
E_CONT  = 23                    ; ?CONT -- nothing to continue
; 13 was E_AFULL, "too many symbols". There is no symbol table to fill:
; a label is a BASIC variable, so running out of them is E_NAMES.
E_DONE  = 255
