#!/usr/bin/env python3
"""The boot ROM and the overlay.

Four tests, in the order that localises a failure fastest:

  1. `cool8_rom_tb` against the RTL — the image parses and reads back.
  2. `cool8_rom_tb` against the netlist `synth_ice40` produces. This is
     the only test that says the ROM will be in the *bitstream*: the RTL
     run proves `$readmemh` works, the netlist run proves the EBR blocks
     came out with the right INIT_0..INIT_F. A boot ROM that is right in
     simulation and empty on the board is not a hypothetical failure.
  3. `cool8_mem_tb` — the overlay's four rules, against patterns rather
     than against real code, so "which memory answered" is readable from
     the data.
  4. `cool8_boot_tb` — the machine booting. Core, SPRAM, ROM and overlay
     from power-on with SPRAM undefined, running the real image; then the
     loader's path, BOOTRAM set and the ROM out of the map.

    python sim/test_boot.py
    python sim/test_boot.py --skip-netlist      # the slow one

The ROM image is generated by tools/mkrom.py into sim/build, not
committed: it is derived from sw/boot.asm and the assembler, and a stale
checked-in copy would be a boot ROM that does not match its own source.

Set OSS_CAD_SUITE to the toolchain root if the tools are not on PATH.
"""

import argparse
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
BUILD = os.path.join(HERE, "build")

sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(ROOT, "tools"))

import cosim                                   # noqa: E402
import mkrom                                   # noqa: E402

SOC = [os.path.join(ROOT, "rtl", "soc", f)
       for f in ("cool8_rom.v", "cool8_spram.v", "cool8_mem.v")]
CORE = [os.path.join(ROOT, "rtl", "core", f)
        for f in ("cool8_alu.v", "cool8_agu.v", "cool8_core.v")]
TB = os.path.join(HERE, "tb")

BOOT_ASM = os.path.join(ROOT, "sw", "boot.asm")
ROM_HEX = os.path.join(BUILD, "boot.hex")
ROM_SYN = os.path.join(BUILD, "cool8_rom_syn.v")


def run(vvp, args, cwd=None):
    r = subprocess.run([cosim._tool("vvp"), vvp] + args, cwd=cwd,
                       capture_output=True, text=True)
    return "\nPASS" in r.stdout, r.stdout + r.stderr


def report(name, ok, out, detail=()):
    print(f"  {name:<44} {'ok' if ok else 'FAIL'}")
    for line in out.splitlines():
        if line.startswith("FAIL") or any(k in line for k in detail):
            print("    " + line)
    return ok


def synth_rom():
    """Map cool8_rom to iCE40 cells and write the netlist out."""
    cells = cosim.ice40_cells()
    script = (f'read_verilog -lib "{cells}"; '
              f'read_verilog "{SOC[0]}"; '
              f'synth_ice40 -top cool8_rom -flatten; '
              f'write_verilog -noattr "{ROM_SYN}"')
    r = subprocess.run([cosim._tool("yosys"), "-q", "-p", script],
                       cwd=BUILD, capture_output=True, text=True)
    if r.returncode != 0:
        print(r.stdout, r.stderr)
        sys.exit("yosys failed mapping the boot ROM")
    with open(ROM_SYN, encoding="utf-8") as fh:
        text = fh.read()
    return text.count("SB_RAM40_4K")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--skip-netlist", action="store_true")
    ap.add_argument("-v", "--verbose", action="store_true")
    args = ap.parse_args()

    os.makedirs(BUILD, exist_ok=True)
    base, img, rom = mkrom.build(BOOT_ASM)
    with open(ROM_HEX, "w") as fh:
        for b in rom:
            fh.write("%02x\n" % b)
    print(f"  boot.asm: {len(img)} bytes at ${base:04X}, "
          f"{sum(1 for b in rom if b)} non-zero of {len(rom)}")

    cells = cosim.ice40_cells()
    ok = True

    vvp = cosim._build("cool8_rom_tb", os.path.join(TB, "cool8_rom_tb.v"),
                       [SOC[0], cells], gen="2012")
    good, out = run(vvp, ["+expect=boot.hex"], cwd=BUILD)
    ok &= report("ROM image, RTL", good, out, ["bytes read back"])

    if not args.skip_netlist:
        blocks = synth_rom()
        vvp = cosim._build("cool8_rom_syn_tb",
                           os.path.join(TB, "cool8_rom_tb.v"),
                           [ROM_SYN, cells], gen="2012")
        good, out = run(vvp, ["+expect=boot.hex"], cwd=BUILD)
        ok &= report(f"ROM image, netlist ({blocks} EBR blocks)", good, out,
                     ["bytes read back"])

    vvp = cosim._build("cool8_mem_tb", os.path.join(TB, "cool8_mem_tb.v"),
                       SOC + [cells], gen="2012")
    good, out = run(vvp, ["+verbose"] if args.verbose else [])
    ok &= report("the overlay", good, out, ["checks,"])

    vvp = cosim._build("cool8_boot_tb", os.path.join(TB, "cool8_boot_tb.v"),
                       SOC + CORE + [cells], gen="2012")
    good, out = run(vvp, [f"+rom={ROM_HEX}"])
    ok &= report("booting, cold and through BOOTRAM", good, out,
                 ["checks,", "after", "clocks"])

    print("\n" + ("PASS" if ok else "FAIL"))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
