#!/usr/bin/env python3
"""Elite's Cobra Mk III for both COBRAs: demos/cobra.bas, and the model
block demos/cobra.act compiles behind.

    python tools/mk3d.py            write both
    python tools/mk3d.py --check    both are what this writes

**The model is the published one.** 28 vertices, 38 edges, 13 faces and
the edge-to-face table, transcribed from the annotated BBC Elite source
at bbcelite.com (the SHIP_COBRA_MK_3 blueprint); the transcription is
asserted against the counts the source states.

## demos/cobra.bas

**The tilt is baked, the spin is runtime.** The host rotates the model
20 degrees about X once; BASIC spins it about the view's vertical axis,
which never touches y, so each vertex's screen Y is one constant and
only screen X varies. Everything is integer, and the largest
|qx*cos + qz*sin| is asserted inside 16-bit signed.

**Visibility is decided by the projected polygon, not the published
normal.** Elite's normals are hand-rounded integers -- (0,62,31) is
near its face's plane, not on it -- so a normal-based cull flips a few
degrees away from where the *drawn* geometry turns edge-on, and edges
vanished while their faces were still visibly open. Here each face's
boundary loop is walked out of the edge table (spurs like the laser
line pruned), its winding calibrated once against the published normal
far from the silhouette, and then every frame's visibility is the
**signed area of the face under the exact integer projection the
machine draws**, kept visible through a small grace margin. Measured
across the revolution: 24.6 edges a frame mean against the normal
cull's 23.6, worst 33 against 32 -- accuracy priced at about one LINE
a frame.

**One mode.** The see-through wireframe is gone by decision -- the
hidden-line ship is simply better -- so the draw loop erases the
two-flips-old frame's edges in black (its list precomputed like every
other) and draws the new set; two CLGs at start cover pages that have
never been drawn. Mode 5 double buffer throughout, D92's split: DBASE
names the glass, BASE the pencil, flipped in two POKEs after VSYNC.

## demos/cobra.act ([D105](../docs/01-decisions.md))

**It is its own program now.** The ship tumbles on three axes and
every frame is computed between two vertical blanks, so what it takes
from here is the model and two tables, not frames. The vertices carry
the bias its transform needs -- MUL is unsigned, so a coordinate goes
in with 128 added and the product's surplus comes back off as two
constants -- and so do the faces' normals, which go through the same
multiply-add. Sine is 1,024 steps to a turn at 127 to a unit, so the
three rates step it evenly; the reciprocal of depth is a byte,
256 * FOCAL / depth for bins two model units deep.

**The cull is by normals, not by the area on the screen.** Each face's
normal is its own triangle's, from the vertices the program draws, 127
long, with the plane's distance folded into a threshold; a face shows
while its rotated normal's z is under it, with HYST of hysteresis. The
area was tried first and flickered: near edge-on a long thin face's
area is the rounding of its corners. Against the true planes the
decision is wrong only within EDGEON degrees of edge-on, and against
the triangles on the screen only below an area of SURE -- both
measured here, over every pose.

**The camera is checked against the machine's own arithmetic.** Every
pose the tumble reaches in its first 4,096 frames, and a grid of the
rest, go through the integer steps the program takes -- the rounded
products, the bias modulo 65,536, the depth bin, a product's high byte
-- and every vertex must land on the screen, every reciprocal fit a
byte, every product stay inside an INT, no edge flicker, and the
picture close: no drawn edge but the laser ends in nothing.
"""
import io
import math
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BAS = os.path.join(ROOT, "demos", "cobra.bas")
ACT = os.path.join(ROOT, "demos", "cobra.act")
ACT_BEGIN = "; ---- generated by tools/mk3d.py: do not edit ----"
ACT_END = "; ---- end of the generated block ----"

# SHIP_COBRA_MK_3, bbcelite.com -- vertex coordinates as published
VERTS = [
    (32, 0, 76), (-32, 0, 76), (0, 26, 24), (-120, -3, -8),
    (120, -3, -8), (-88, 16, -40), (88, 16, -40), (128, -8, -40),
    (-128, -8, -40), (0, 26, -40), (-32, -24, -40), (32, -24, -40),
    (-36, 8, -40), (-8, 12, -40), (8, 12, -40), (36, 8, -40),
    (36, -12, -40), (8, -16, -40), (-8, -16, -40), (-36, -12, -40),
    (0, 0, 76), (0, 0, 90), (-80, -6, -40), (-80, 6, -40),
    (-88, 0, -40), (80, 6, -40), (88, 0, -40), (80, -6, -40),
]
EDGES = [
    (0, 1), (0, 4), (1, 3), (3, 8), (4, 7), (6, 7), (6, 9), (5, 9),
    (5, 8), (2, 5), (2, 6), (3, 5), (4, 6), (1, 2), (0, 2), (8, 10),
    (10, 11), (7, 11), (1, 10), (0, 11), (1, 5), (0, 6), (20, 21),
    (12, 13), (18, 19), (14, 15), (16, 17), (15, 16), (14, 17),
    (13, 18), (12, 19), (2, 9), (22, 24), (23, 24), (22, 23),
    (25, 26), (26, 27), (25, 27),
]
# face normals as published -- used only to find which way is out
FACES = [
    (0, 62, 31), (-18, 55, 16), (18, 55, 16), (-16, 52, 14),
    (16, 52, 14), (-14, 47, 0), (14, 47, 0), (-61, 102, 0),
    (61, 102, 0), (0, 0, -80), (-7, -42, 9), (0, -30, 6), (7, -42, 9),
]
# each edge's two faces; the rear-panel details (23-30, 32-37) live in
# face 9's plane and appear and vanish with the stern as one unit
EDGE_FACES = [
    (0, 11), (4, 12), (3, 10), (7, 10), (8, 12), (8, 9), (6, 9),
    (5, 9), (7, 9), (1, 5), (2, 6), (3, 7), (4, 8), (0, 1), (0, 2),
    (9, 10), (9, 11), (9, 12), (10, 11), (11, 12), (1, 3), (2, 4),
    (0, 11), (9, 9), (9, 9), (9, 9), (9, 9), (9, 9), (9, 9), (9, 9),
    (9, 9), (5, 6), (9, 9), (9, 9), (9, 9), (9, 9), (9, 9), (9, 9),
]

# ---- demos/cobra.bas
F = 72                       # frames in a revolution: 5 degrees a step
TILT = math.radians(20)
SCALE = 1.10                 # the largest that keeps the products 16-bit
MARGIN = 150                 # px^2 of grace before a closing face hides

# ---- demos/cobra.act (D105)
DIST = 500                   # the camera, model units from the ship's centre
FOCAL = 360                  # 256 * FOCAL / depth is the reciprocal table
ZBIAS = 68                   # Z >> 8 runs -67..66; plus this, the table's index
ZBINS = 136
SINES = 1024                 # sine's steps to a turn: an angle's top ten bits
HYST = 256                   # Faces()'s hysteresis in (Mn)z - T: one in its high byte, 0.9 degrees
SURE = 150                   # past this quarter area on the screen, Faces() and the triangle agree (146 measured)
EDGEON = 2.0                 # and against its plane, it is wrong only this many degrees from edge-on
CX, CY = 128, 120            # the screen's centre: 256 x 240
YAWR, PITCHR, ROLLR = 0x0180, 0x00D3, 0x0111   # a frame's steps; 256 to a turn in the high byte


def face_loops():
    """Each face's boundary loop, walked from the edge table. The laser
    line (20-21) hangs off faces 0 and 11 as a spur -- an edge with a
    degree-1 endpoint -- and spurs bound no area, so they are pruned
    before the walk."""
    loops = []
    for face in range(13):
        es = [list(EDGES[e]) for e in range(38)
              if EDGE_FACES[e] != (9, 9) and face in EDGE_FACES[e]]
        while True:
            deg = {}
            for a, b in es:
                deg[a] = deg.get(a, 0) + 1
                deg[b] = deg.get(b, 0) + 1
            drop = [e for e in es if deg[e[0]] == 1 or deg[e[1]] == 1]
            if not drop:
                break
            es = [e for e in es if e not in drop]
        assert len(es) >= 3, "face %d has no loop" % face
        adj = {}
        for a, b in es:
            adj.setdefault(a, []).append(b)
            adj.setdefault(b, []).append(a)
        assert all(len(v) == 2 for v in adj.values()), \
            "face %d boundary is not one cycle" % face
        start = es[0][0]
        loop, prev = [start], None
        while True:
            nxt = [n for n in adj[loop[-1]] if n != prev]
            prev = loop[-1]
            loop.append(nxt[0])
            if loop[-1] == start:
                break
        loops.append(loop[:-1])
    return loops


def bas_text():
    """demos/cobra.bas, and what it reports."""
    assert len(VERTS) == 28 and len(EDGES) == 38, "not the published ship"
    assert len(FACES) == 13 and len(EDGE_FACES) == 38
    assert all(0 <= a < 28 and 0 <= b < 28 for a, b in EDGES)
    assert all(0 <= a < 13 and 0 <= b < 13 for a, b in EDGE_FACES)

    ct, st = math.cos(TILT), math.sin(TILT)

    def tilt(v):
        x, y, z = v
        return (x, y * ct - z * st, y * st + z * ct)

    qx, qy, qz = [], [], []
    for v in VERTS:
        x, y, z = tilt(v)
        qx.append(int(round(x * SCALE)))
        qy.append(int(round(y * SCALE)))
        qz.append(int(round(z * SCALE)))

    worst = max(abs(qx[v]) + abs(qz[v]) for v in range(28)) * 127
    assert worst < 32000, "products overflow 16-bit: %d" % worst

    sy = [96 - qy[v] for v in range(28)]
    assert all(4 <= y <= 188 for y in sy), "screen y out of mode 5"
    sn = [int(round(127 * math.sin(2 * math.pi * i / F)))
          for i in range(F)]

    def project(f):
        """integer screen coordinates, exactly as line 133 computes"""
        c, s = sn[(f + F // 4) % F], sn[f]
        return [(128 + int((qx[v] * c + qz[v] * s) / 256), sy[v])
                for v in range(28)]

    for f in range(F):
        for (x, _) in project(f):
            assert 4 <= x <= 251, "screen x out of range: %d" % x

    loops = face_loops()

    def area(face, pts):
        a, lp = 0, loops[face]
        for i in range(len(lp)):
            x0, y0 = pts[lp[i]]
            x1, y1 = pts[lp[(i + 1) % len(lp)]]
            a += x0 * y1 - x1 * y0
        return a

    # winding calibration: at each face's farthest-from-silhouette
    # frame the published normal is unambiguous, and the signed area's
    # sign there fixes the loop's orientation for good
    nrm = [tilt(n) for n in FACES]
    cal = []
    for face in range(13):
        best, bf = 0.0, 0
        for f in range(F):
            th = 2 * math.pi * f / F
            vz = -nrm[face][0] * math.sin(th) + nrm[face][2] * math.cos(th)
            if abs(vz) > abs(best):
                best, bf = vz, f
        a = area(face, project(bf))
        assert a != 0, "face %d degenerate at calibration" % face
        cal.append(-1 if (best < 0) == (a < 0) else 1)

    vis = []
    for f in range(F):
        pts = project(f)
        fv = [cal[k] * area(k, pts) < MARGIN for k in range(13)]
        vis.append([e for e in range(38)
                    if fv[EDGE_FACES[e][0]] or fv[EDGE_FACES[e][1]]])
    counts = [len(v) for v in vis]
    assert all(8 <= n < 38 for n in counts), "culling degenerate: %s" % (
        sorted(set(counts)))
    # no edge may flicker: visible, gone for one frame, visible again
    for e in range(38):
        v = [e in vis[f] for f in range(F)]
        assert not any(v[f - 1] and v[(f + 1) % F] and not v[f]
                       for f in range(F)), "edge %d flickers" % e
    slots = sum(counts)

    body = """1 GOTO 100
10 A=A+1:IF A>71 THEN A=0
11 VSYNC
12 POKE $FF30,P:P=96-P:POKE $FF13,P
13 IF R>0 THEN R=R-1:CLG 0:GOTO 16
14 Y=A-2:IF Y<0 THEN Y=Y+72
15 D=O(Y)+Q(Y)-1:FOR K=O(Y) TO D:LINE H(K),J(K),L(K),M(K),0:NEXT K
16 D=O(A)+Q(A)-1:FOR K=O(A) TO D:LINE H(K),J(K),L(K),M(K),10:NEXT K
17 IF INKEY=0 THEN GOTO 10
18 MODE 0
19 CURSOR 1
20 END
100 PRINT "COBRA MK III"
101 PRINT "COMPUTING 72 FRAMES..."
102 DIM U(2015):DIM W(27):DIM E(37):DIM G(37):DIM S(71)
103 DIM X(27):DIM Z(27)
104 DIM H(%d):DIM J(%d):DIM L(%d):DIM M(%d)
105 DIM O(71):DIM Q(71)
110 FOR V=0 TO 27
111 READ N:X(V)=N
112 READ N:W(V)=N
113 READ N:Z(V)=N
114 NEXT V
115 FOR K=0 TO 37
116 READ N:E(K)=N
117 READ N:G(K)=N
118 NEXT K
120 FOR V=0 TO 71
121 READ N:S(V)=N
122 NEXT V
130 FOR F=0 TO 71
131 T=F+18:IF T>71 THEN T=T-72
132 C=S(T):D=S(F):B=F*28
133 FOR V=0 TO 27:U(B+V)=128+(X(V)*C+Z(V)*D)/256:NEXT V
134 NEXT F
135 PRINT "CULLING..."
140 B=0
141 FOR F=0 TO 71
142 READ N:Q(F)=N:O(F)=B:C=F*28
143 FOR K=1 TO N
144 READ T
145 H(B)=U(C+E(T)):J(B)=W(E(T)):L(B)=U(C+G(T)):M(B)=W(G(T))
146 B=B+1
147 NEXT K
148 NEXT F
150 MODE 5
151 CURSOR 0
152 CLG 0
153 POKE $FF30,0:POKE $FF11,$7A
154 A=71:P=0:R=2
155 GOTO 10
""" % (slots - 1, slots - 1, slots - 1, slots - 1)

    def data(vals, start):
        lines, n, i = [], start, 0
        while i < len(vals):
            chunk = vals[i:i + 14]
            while len(("%d DATA " % n) + ",".join(map(str, chunk))) > 79:
                chunk = chunk[:-1]
            lines.append("%d DATA %s" % (n, ",".join(map(str, chunk))))
            i += len(chunk)
            n += 1
        return lines

    model = []
    for v in range(28):
        model += [qx[v], sy[v], qz[v]]
    edges = [n for e in EDGES for n in e]
    seen = []
    for f in range(F):
        seen += [counts[f]] + vis[f]
    src = body + "\n".join(
        data(model, 200) + data(edges, 250) + data(sn, 300)
        + data(seen, 350)) + "\n"
    lines = [l for l in src.split("\n") if l.strip()]
    ns = [int(l.split()[0]) for l in lines]
    assert ns == sorted(ns), "line numbers not ascending"
    over = [n for n, l in zip(ns, lines) if len(l) > 79]
    assert not over, "lines over 79 chars: %s" % over
    report = [
        "  cobra.bas: %d lines, 28 vertices, 38 edges, %d frames" % (len(lines), F),
        "  visible edges a frame: %d-%d, mean %.1f; %d slots, %s bytes"
        % (min(counts), max(counts), slots / float(F), slots, "{:,}".format(slots * 8)),
        "  cull: projected signed area, %d px^2 grace, 0 flickers" % MARGIN]
    return src, report


# ------------------------------------------------------ demos/cobra.act

def _sub(a, b):
    return tuple(x - y for x, y in zip(a, b))


def _cross(a, b):
    return (a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0])


def _dot(a, b):
    return sum(x * y for x, y in zip(a, b))


def act_model():
    """What demos/cobra.act is built from -- the model, the tables, each
    face's normal and threshold -- checked against the arithmetic the
    program does, over the tumble's first 4,096 frames and a grid of
    every pose. sim/test_action.py holds the program to it."""
    loops = face_loops()
    V = [tuple(max(-127, min(127, c)) for c in v) for v in VERTS]

    # a triangle per face: the loop's three vertices spanning the most
    # area, wound so its normal is the published outward one
    tris = []
    for f, lp in enumerate(loops):
        best, tri = -1, None
        for i in range(len(lp)):
            for j in range(i + 1, len(lp)):
                for k in range(j + 1, len(lp)):
                    a, b, c = VERTS[lp[i]], VERTS[lp[j]], VERTS[lp[k]]
                    n = _cross(_sub(b, a), _sub(c, a))
                    if _dot(n, n) > best:
                        best, tri = _dot(n, n), (lp[i], lp[j], lp[k])
        a, b, c = (VERTS[t] for t in tri)
        if _dot(_cross(_sub(b, a), _sub(c, a)), FACES[f]) < 0:
            tri = (tri[0], tri[2], tri[1])
        tris.append(tri)

    sn = [int(round(127 * math.sin(2 * math.pi * i / SINES))) for i in range(SINES)]
    rz = []
    for i in range(ZBINS):
        dep = DIST + 2 * (i - ZBIAS) + 1
        r = int(round(256.0 * FOCAL / dep))
        assert 1 <= r <= 255, "the reciprocal outgrew a byte at bin %d: %d" % (i, r)
        rz.append(r)

    def inside(*vals):
        assert all(-32768 <= q <= 32767 for q in vals), "an INT overflowed: %s" % (vals,)

    def r7(x):
        """(x + 64) >> 7: an INT shift floors, so 64 first rounds"""
        inside(x + 64)
        return (x + 64) >> 7

    def matrix(ya, pa, ra):
        """Matrix(): roll x pitch x yaw from the table, each product of
        two brought back to 127 a unit, rounded"""
        q = SINES // 4
        sa, ca = sn[ya], sn[(ya + q) % SINES]
        sb, cb = sn[pa], sn[(pa + q) % SINES]
        sc, cc = sn[ra], sn[(ra + q) % SINES]
        t, u = r7(sb * sa), r7(sb * ca)
        m = [[r7(cc * ca - sc * t), -r7(sc * cb), r7(cc * sa + sc * u)],
             [r7(sc * ca + cc * t), r7(cc * cb), r7(sc * sa - cc * u)],
             [-r7(cb * sa), sb, r7(cb * ca)]]
        assert all(-127 <= e <= 127 for row in m for e in row)
        return m

    biased = [0]

    def project(m):
        """Transform(): the screen coordinates, as the assembly makes them"""
        pts = []
        for v in V:
            X, Y, Z = (sum(m[r][j] * v[j] for j in range(3)) for r in range(3))
            inside(X, Y, Z)
            if biased[0] < 2000:            # the biased route, modulo 65,536
                biased[0] += 1
                for r, q in enumerate((X, Y, Z)):
                    acc = (sum((m[r][j] + 128) * (v[j] + 128) for j in range(3))
                           - (128 * sum(m[r]) + 49152) - 128 * sum(v)) & 0xFFFF
                    assert acc == q & 0xFFFF, "the bias does not come back off"
            idx = (Z >> 8) + ZBIAS
            assert 0 <= idx < ZBINS, "depth bin %d" % idx
            r = rz[idx]
            ox, oy = ((abs(X) >> 7) * r) >> 8, ((abs(Y) >> 7) * r) >> 8
            sx = CX + ox if X >= 0 else CX - ox
            sy = CY - oy if Y >= 0 else CY + oy
            assert 0 <= sx <= 255 and 0 <= sy <= 239, "off the screen: %d,%d" % (sx, sy)
            pts.append((sx, sy))
        return pts

    def area4(pts, tri):
        """a face's triangle's area on the screen, differences halved,
        INT >> flooring: what Faces() is held to where it is decisive"""
        (xa, ya), (xb, yb), (xc, yc) = (pts[t] for t in tri)
        return ((xb - xa) >> 1) * ((yc - ya) >> 1) - ((yb - ya) >> 1) * ((xc - xa) >> 1)

    # **the faces, by their normals** (Faces()). A face is turned to the
    # viewer when the eye is on the outer side of its plane, and after
    # the rotation that is one comparison: the rotated normal's z against
    # a threshold of the face's own, which is its plane's distance from
    # the ship's centre as seen from DIST away. The normal is not the
    # published one -- those are hand-rounded, degrees off their faces
    # (the cobra.bas notes above) -- but the face's own triangle's, from
    # the vertices the program draws, 127 long so a component is a byte.
    #
    # In Transform's units a coordinate is 127 of the model's and the eye
    # is at Z = -128 DIST (depth is DIST + Z / 128), so n.(eye - P) > 0 is
    # -128 DIST (Mn)z / 127 - 127 n.c > 0 for a point c of the plane: the
    # face shows when (Mn)z < -127^2 n.c / (128 DIST), which is T.
    fn = []
    for a, b, c in tris:
        n = _cross(_sub(V[b], V[a]), _sub(V[c], V[a]))
        s = 127.0 / math.sqrt(_dot(n, n))
        n = tuple(int(round(q * s)) for q in n)
        cen = [(V[a][j] + V[b][j] + V[c][j]) / 3.0 for j in range(3)]
        fn.append((n, int(round(-127 * 127 * _dot(n, cen) / (128.0 * DIST)))))

    def facing(m):
        """Faces(): each face's (Mn)z - T, negative when it is turned to
        the viewer, by the biased route the assembly takes"""
        out = []
        for n, T in fn:
            q = sum(m[2][j] * n[j] for j in range(3)) - T
            inside(q)
            acc = (sum((m[2][j] + 128) * (n[j] + 128) for j in range(3))
                   - (128 * sum(m[2]) + 49152) - (128 * sum(n) + T)) & 0xFFFF
            assert acc == q & 0xFFFF, "the bias does not come back off a normal"
            out.append(q)
        return out

    # **the triangles on the screen**, wound so a face turned to the
    # viewer has a positive area there -- which way that is, measured
    # far from edge-on rather than assumed. The program has no use for
    # them; the checks below and sim/test_action.py compare the cull with
    # the picture through them.
    eye = (0, 0, -128 * DIST)
    agree = against = 0
    for ya in range(0, SINES, SINES // 8):
        for pa in range(0, SINES, SINES // 8):
            for ra in range(0, SINES, SINES // 8):
                m = matrix(ya, pa, ra)
                pts = project(m)
                for t, q in zip(tris, facing(m)):
                    ar = area4(pts, t)
                    if abs(ar) >= 64:
                        if (ar > 0) == (q < 0):
                            agree += 1
                        else:
                            against += 1
    scr = tris if agree >= against else [(a, c, b) for a, b, c in tris]

    # **the tumble itself**: its first 4,096 frames, as the loop steps
    # the angles, culled and listed as the program does -- no edge may
    # flicker, off for a frame and on again -- and then a grid of every
    # pose: each vertex on the screen, each face's decision against its
    # plane in floating point (wrong only within EDGEON degrees of edge-on)
    # and against its triangle on the screen (only where the area, whose
    # sign the rounding of the corners makes unreliable near zero -- the
    # reason for the normals -- is within SURE)
    #
    # **Faces() has HYST of hysteresis, and this is why**: without it
    # edges flickered here, of two kinds -- a face crossing edge-on in a
    # frame that moved it less than the matrix's rounding (-5, then +5),
    # and an edge whose two faces are both within a degree of edge-on
    # for one frame as one turns away and the other turns in. A face
    # turned to the viewer stays so until (Mn)z - T is HYST past zero,
    # and one turned away turns in only HYST short of it.
    assert HYST == 256, "Faces() adds and takes HYST in the high byte"
    ang = [0, 0, 0]
    fv = [False] * 13
    vis, pix, qs, loose = [], [], [], []
    sure, tilt = 0, 0.0
    for fr in range(4096):
        ang = [(a + d) & 0xFFFF for a, d in zip(ang, (YAWR, PITCHR, ROLLR))]
        m = matrix(*(a * SINES >> 16 for a in ang))
        pts = project(m)
        qs.append(facing(m))
        fv = [q - HYST < 0 if was else q + HYST < 0 for q, was in zip(qs[-1], fv)]
        for t, v in zip(scr, fv):
            ar = area4(pts, t)
            if (ar > 0) != v:
                sure = max(sure, abs(ar))
        es = [e for e in range(38) if fv[EDGE_FACES[e][0]] or fv[EDGE_FACES[e][1]]]
        vis.append(set(es))
        pix.append(sum(max(abs(pts[EDGES[e][0]][0] - pts[EDGES[e][1]][0]),
                           abs(pts[EDGES[e][0]][1] - pts[EDGES[e][1]][1])) + 1 for e in es))
        deg = {}
        for e in es:
            for v in EDGES[e]:
                deg[v] = deg.get(v, 0) + 1
        loose += [(fr, v, [e for e in es if v in EDGES[e]], fv) for v, d in deg.items()
                  if d == 1 and v not in (20, 21)]
    # **the picture closes**: a face turned to the viewer brings its whole
    # boundary, so no vertex but the laser's ends a single drawn edge
    assert not loose, "a drawn edge ends in nothing: %s" % [
        "frame %d vertex %d edge %s faces %s shown %s" % (
            fr, v, es, [EDGE_FACES[e] for e in es], [f for f in range(13) if fv[f]])
        for fr, v, es, fv in loose[:6]]
    flick = [(e, i) for e in range(38) for i in range(1, len(vis) - 1)
             if e in vis[i - 1] and e in vis[i + 1] and e not in vis[i]]
    assert not flick, "edges flicker in the tumble:\n" + "\n".join(
        "  edge %d frame %d: faces %d and %d, (Mn)z - T %s and %s" % (
            e, i, EDGE_FACES[e][0], EDGE_FACES[e][1],
            [qs[j][EDGE_FACES[e][0]] for j in range(i - 2, i + 3)],
            [qs[j][EDGE_FACES[e][1]] for j in range(i - 2, i + 3)])
        for e, i in flick[:16])
    xs, ys = [], []
    for ya in range(0, SINES, SINES // 16):
        for pa in range(0, SINES, SINES // 16):
            for ra in range(0, SINES, SINES // 16):
                m = matrix(ya, pa, ra)
                pts = project(m)
                xs += [p[0] for p in pts]
                ys += [p[1] for p in pts]
                P = [tuple(sum(m[r][j] * v[j] for j in range(3)) for r in range(3)) for v in V]
                for (a, b, c), t, q in zip(tris, scr, facing(m)):
                    ar = area4(pts, t)
                    if (ar > 0) != (q < 0):
                        sure = max(sure, abs(ar))
                    nn = _cross(_sub(P[b], P[a]), _sub(P[c], P[a]))
                    e = _sub(eye, P[a])
                    cosv = _dot(nn, e) / math.sqrt(_dot(nn, nn) * _dot(e, e))
                    if (cosv > 0) != (q < 0):
                        tilt = max(tilt, math.degrees(math.asin(abs(cosv))))
    assert sure <= SURE, "a face disagrees with its triangle on the screen at area %d" % sure
    assert tilt <= EDGEON, "a face disagrees with its plane %.2f degrees off edge-on" % tilt
    return dict(V=V, scr=scr, fn=fn, sn=sn, rz=rz, vis=vis, pix=pix, xs=xs, ys=ys,
                sure=sure, tilt=tilt, agree=agree, matrix=matrix, project=project)


def act_text():
    """The block demos/cobra.act compiles behind, and what it reports."""
    md = act_model()
    V, fn, sn, rz, vis, pix, xs, ys = (md[k] for k in ("V", "fn", "sn", "rz", "vis", "pix", "xs", "ys"))

    def rows(vals, per):
        return "\n".join("  " + " ".join(str(v) for v in vals[i:i + per])
                         for i in range(0, len(vals), per))

    vb = []
    for v in V:
        lv = (128 * sum(v)) & 0xFFFF
        vb += [v[0] + 128, v[1] + 128, v[2] + 128, lv & 0xFF, lv >> 8]
    nb = []
    for n, T in fn:
        k = (128 * sum(n) + T) & 0xFFFF
        nb += [n[0] + 128, n[1] + 128, n[2] + 128, k & 0xFF, k >> 8]
    o = [ACT_BEGIN,
         "; the Cobra Mk III as bbcelite.com publishes it: 28 vertices, each as",
         "; x+128 y+128 z+128 and the 16-bit 128*(x+y+z) Transform takes back off;",
         "; 128 is 127 here, the one coordinate a signed byte cannot hold",
         "BYTE ARRAY vb(140) = [\n%s]" % rows(vb, 15),
         "; 38 edges: their two vertices, and the two faces they border",
         "BYTE ARRAY ea(38) = [\n%s]" % rows([a for a, _ in EDGES], 19),
         "BYTE ARRAY eb(38) = [\n%s]" % rows([b for _, b in EDGES], 19),
         "BYTE ARRAY ef1(38) = [\n%s]" % rows([a for a, _ in EDGE_FACES], 19),
         "BYTE ARRAY ef2(38) = [\n%s]" % rows([b for _, b in EDGE_FACES], 19),
         "; 13 faces: the normal of each one's own triangle of the vertices above,",
         "; 127 long, as nx+128 ny+128 nz+128 and the 16-bit 128*(nx+ny+nz) + T,",
         "; T being where the rotated normal's z turns the face to the viewer",
         "BYTE ARRAY nb(65) = [\n%s]" % rows(nb, 15),
         "; sine, 127 to a unit, %d steps to a turn: cosine is sn(a + %d)" % (SINES, SINES // 4),
         "INT ARRAY sn(%d) = [\n%s]" % (SINES, rows(sn, 16)),
         "; 256 * FOCAL / depth, for bins two model units deep from DIST - 2 * ZBIAS",
         "BYTE ARRAY rz(%d) = [\n%s]" % (ZBINS, rows(rz, 17)),
         "CONST DIST = %d                     ; the camera, model units from the ship's centre" % DIST,
         "CONST FOCAL = %d" % FOCAL,
         "CONST ZBIAS = %d                     ; Z's high byte plus this is the depth bin" % ZBIAS,
         "CONST CX = %d" % CX,
         "CONST CY = %d" % CY,
         "CONST YAWR = $%04X                  ; the angles' steps a frame" % YAWR,
         "CONST PITCHR = $%04X" % PITCHR,
         "CONST ROLLR = $%04X" % ROLLR,
         ACT_END]
    counts = [len(v) for v in vis]
    report = [
        "  cobra.act: 13 faces culled by their normals -- against their planes, wrong only"
        " %.2f degrees from edge-on; against their triangles on the screen, only below"
        " an area of %d" % (md["tilt"], md["sure"]),
        "  on the screen over %d poses: x %d-%d, y %d-%d; reciprocals %d-%d"
        % (len(xs) // 28 + 4096, min(xs), max(xs), min(ys), max(ys), min(rz), max(rz)),
        "  the tumble's first 4,096 frames: %d-%d edges a frame, mean %.1f; %d-%d pixels,"
        " mean %d; no edge flickers" % (min(counts), max(counts), sum(counts) / 4096.0,
                                          min(pix), max(pix), sum(pix) // 4096)]
    return "\n".join(o), report


def splice(text, block):
    a = text.index(ACT_BEGIN)
    b = text.index(ACT_END, a) + len(ACT_END)
    return text[:a] + block + text[b:]


def main():
    check = "--check" in sys.argv
    bas, bas_report = bas_text()
    block, act_report = act_text()
    act_now = io.open(ACT, encoding="utf-8").read()
    act_new = splice(act_now, block)
    if check:
        stale = []
        if io.open(BAS, encoding="utf-8").read() != bas:
            stale.append(BAS)
        if act_now != act_new:
            stale.append(ACT)
        for p in stale:
            print("  %s is not what tools/mk3d.py writes: python tools/mk3d.py"
                  % os.path.relpath(p, ROOT))
        if not stale:
            print("  demos/cobra.bas and cobra.act's model block are current")
        return 1 if stale else 0
    io.open(BAS, "w", encoding="utf-8", newline="\n").write(bas)
    io.open(ACT, "w", encoding="utf-8", newline="\n").write(act_new)
    for line in bas_report + act_report:
        print(line)
    print("  -> %s, %s" % (os.path.relpath(BAS, ROOT), os.path.relpath(ACT, ROOT)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
