#!/usr/bin/env python3
"""Wrap a system image in the stub that puts it where it belongs.

    python tools/mkboot.py sim/build/basic.bin -o sim/build/BOOT.BIN

The boot ROM's autoboot loads `BOOT.BIN` to `$0200` and jumps to it.
BASIC links at `$A000`, because program text grows up from `$0200` and
the screen is at `$8000`, so the two addresses cannot both be right.
Something has to move the image after it is loaded.

**The stub does it, and not the ROM.** Teaching autoboot to read a load
address out of a header would be a dozen bytes in a 4 KB ROM that has 36
free -- and it is the one part of the machine that cannot be reflashed
if it turns out to be wrong. A stub costs nothing anybody else has to
live with, and a file that carries its own relocation works on a ROM
that was burned before it existed.

The copy is upward and cannot overlap: the payload sits just above
`$0200` and the destination starts at `$A000`, so a 21 KB image occupies
`$0220-$5620` on the way in. ROMEN goes off *before* the jump, because
BASIC's last bytes are above `$F000` and would otherwise be read out of
the boot ROM rather than out of themselves.
"""

import argparse
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# The stub, with its three constants filled in. Generated rather than
# committed for the same reason sim/build/boot.hex is: it is derived
# from the image it carries, and a stale copy would be a loader that
# moves the wrong number of bytes.
STUB = """
; Generated by tools/mkboot.py -- do not edit.
;
; Autoboot has just loaded this whole file to $0200 and jumped here.
; Move the payload up to where it was linked, drop the ROM overlay, and
; go. SP is left where sw/boot.asm put it: the stack grows down from
; $0200 and this code runs upward from it, so they do not meet.

        .org  $@ORG@

SYSCTRL = $FE00

reloc:  LDW  X,#src
        LDW  Y,#$@DEST@
        MOV  R2,#$@LO@          ; @SIZE@ bytes
        MOV  R3,#$@HI@

        ; The autoboot loop's own shape (sw/boot.asm .ab4): test the
        ; 16-bit count against zero as two bytes, and carry the borrow
        ; into the high one by hand.
.cp:    MOV  R0,R2
        OR   R0,R3
        BEQ  .go
        LD   R0,[X]
        ST   [Y],R0
        INCW X
        INCW Y
        SUB  R2,#1
        BCS  .cp
        SUB  R3,#1
        BRA  .cp

        ; ROMEN is bit 0 and every other bit reads 0, so this clears the
        ; overlay and nothing else. It has to happen before the jump:
        ; the image runs past $F000, and those bytes are only its own
        ; once the ROM stops answering for them.
.go:    CLR  R0
        ST   [SYSCTRL],R0

        ; ------------------------------------------------- the dressing
        ; One-shot initialisation that costs ZERO resident bytes: this
        ; stub lives at $0200 in user RAM and the first line typed into
        ; the editor is stored on top of it. So the default palettes and
        ; the startup chime live here, run once, and are reclaimed --
        ; the machine's whole make-up ritual in memory it gives back.

        ; palette bank 0: the editor's sixteen, CGA slot meanings kept
        ; so attribute nibbles stay true, values softened. Bank 1: the
        ; Pico-8 sixteen, quantised to RGB444 -- a designed game
        ; palette for sprites and tiles to point at.
        CLR  R0
        ST   [$FE1E],R0
        LDW  X,#paltab
        MOV  R2,#64
.pl:    LD   R0,[X]
        ST   [$FE1F],R0
        INCW X
        SUB  R2,#1
        BNE  .pl

        ; the chime: three rising notes on voice 0, ~60 ms each, then
        ; silence. C5, E5, G5 as phase increments (f = inc / 2).
        LDW  X,#chime
.nx:    LD   R2,[X]
        INCW X
        LD   R3,[X]
        INCW X
        MOV  R0,R2
        OR   R0,R3
        BEQ  .off
        CLR  R0
        ST   [$FE50],R0
        ST   [$FE51],R2
        ST   [$FE51],R3
        MOV  R0,#4
        ST   [$FE50],R0
        MOV  R0,#$06
        ST   [$FE51],R0
        MOV  R0,#$40
        ST   [$FE51],R0
        CLR  R0
        CLR  R1
.dl:    ADD  R0,#1
        ADC  R1,#0
        CMP  R1,#$C0
        BNE  .dl
        BRA  .nx
.off:   MOV  R0,#4
        ST   [$FE50],R0
        CLR  R0
        ST   [$FE51],R0
        ST   [$FE51],R0

        ; GTEXT's font: 96 glyphs of 8x8, 1 bpp, seeded into VRAM at
        ; $FC00 through the port. VRAM is RAM: it survives every mode
        ; switch, so this happens once, here, in reclaimed memory.
        MOV  R0,#1
        ST   [$FE28],R0
        CLR  R0
        ST   [$FE26],R0
        MOV  R0,#$FC
        ST   [$FE27],R0
        LDW  X,#font8
        CLR  R2                 ; 768 bytes, the autoboot count idiom
        MOV  R3,#3
.fc:    MOV  R0,R2
        OR   R0,R3
        BEQ  .fdone
        LD   R0,[X]
        ST   [$FE29],R0
        INCW X
        SUB  R2,#1
        BCS  .fc
        SUB  R3,#1
        BRA  .fc
.fdone:
        LDW  X,#$@DEST@
        JMP  [X]

font8:
@FONT@

paltab: ; bank 0 -- softened CGA, semantics preserved
        .byte $00,$00, $01,$2B, $01,$A4, $02,$AB
        .byte $0B,$32, $0A,$3A, $0B,$72, $0B,$BC
        .byte $05,$56, $05,$9F, $06,$E7, $07,$EE
        .byte $0F,$66, $0E,$7E, $0F,$D5, $0F,$FF
        ; bank 1 -- Pico-8, quantised to RGB444
        .byte $00,$00, $01,$23, $07,$25, $00,$85
        .byte $0A,$53, $05,$55, $0C,$CC, $0F,$FE
        .byte $0F,$04, $0F,$A0, $0F,$E2, $00,$E3
        .byte $02,$AF, $08,$79, $0F,$7A, $0F,$CA

chime:  .word 1047, 1320, 1571
        .word 0

src:
"""


def _font8():
    """96 glyphs of 8x8, 1 bpp, from the bitstream's own 8x16 font --
    the same BDF, so the two faces always agree. The face inks only a
    band of its 16 rows (Spleen: about ten of them), so the band is
    found first and resampled onto the 8 output rows, OR-merging where
    two source rows land on one. Sampling fixed rows instead left the
    glyphs' bottom quarter blank."""
    import glob
    import mkfont
    bdf = sorted(glob.glob(os.path.join(ROOT, "assets", "font", "*.bdf")))[0]
    img, _, _ = mkfont.build(bdf)
    inked = [r for r in range(16)
             if any(img[ch * 16 + r] for ch in range(33, 128))]
    lo, n = inked[0], inked[-1] - inked[0] + 1
    out = bytearray()
    for ch in range(32, 128):
        cell = img[ch * 16:(ch + 1) * 16]
        for i in range(8):
            a = lo + (i * n) // 8
            b = max(a + 1, lo + ((i + 1) * n) // 8)
            acc = 0
            for r in range(a, b):
                acc |= cell[r]
            out.append(acc)
    lines = []
    for i in range(0, len(out), 16):
        row = ",".join("$%02X" % b for b in out[i:i + 16])
        lines.append("        .byte " + row)
    return "\n".join(lines)


def build(payload, dest=0xA000, org=0x0200, build_dir=None):
    """The stub for `payload`, assembled, with the payload after it."""
    build_dir = build_dir or os.path.join(ROOT, "sim", "build")
    os.makedirs(build_dir, exist_ok=True)

    text = (STUB.replace("@FONT@", _font8())
                .replace("@ORG@", "%04X" % org)
                .replace("@DEST@", "%04X" % dest)
                .replace("@LO@", "%02X" % (len(payload) & 0xFF))
                .replace("@HI@", "%02X" % (len(payload) >> 8))
                .replace("@SIZE@", "%d" % len(payload)))
    apath = os.path.join(build_dir, "bootstub.asm")
    with open(apath, "w") as fh:
        fh.write(text)

    out = os.path.join(build_dir, "bootstub.bin")
    r = subprocess.run([sys.executable, os.path.join(HERE, "cool8asm.py"),
                        apath, "-o", out, "-I", os.path.join(ROOT, "sw")],
                       capture_output=True, text=True)
    if r.returncode != 0:
        sys.stderr.write(r.stdout + r.stderr)
        raise SystemExit("the boot stub would not assemble")
    with open(out, "rb") as fh:
        stub = fh.read()

    end = dest + len(payload)
    if org + len(stub) + len(payload) > dest:
        raise SystemExit("the payload would land on its own destination")
    if end > 0x10000:
        raise SystemExit("the image does not fit below $10000")
    return stub + payload


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("image", help="the linked system image, e.g. basic.bin")
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument("--dest", type=lambda s: int(s, 0), default=0xA000,
                    help="where the image was linked (default $A000)")
    args = ap.parse_args()

    with open(args.image, "rb") as fh:
        payload = fh.read()
    out = build(payload, dest=args.dest)
    with open(args.output, "wb") as fh:
        fh.write(out)
    print("%s: %d bytes of stub + %d of image -> %s"
          % (os.path.basename(args.image), len(out) - len(payload),
             len(payload), args.output))
    return 0


if __name__ == "__main__":
    sys.exit(main())
