#!/usr/bin/env python3
"""Wrap a system image in the stub that puts it where it belongs.

    python tools/mkboot.py sim/build/basic.bin -o sim/build/BOOT.BIN

The boot ROM's autoboot loads `BOOT.BIN` to `$0200` and jumps to it.
BASIC links at `$A000`, because program text grows up from `$0200` and
the screen is at `$8000`, so the two addresses cannot both be right.
Something has to move the image after it is loaded.

**The stub does it, and not the ROM.** Teaching autoboot to read a load
address out of a header would be a dozen bytes in a 4 KB ROM that has 36
free -- and it is the one part of the machine that cannot be reflashed
if it turns out to be wrong. A stub costs nothing anybody else has to
live with, and a file that carries its own relocation works on a ROM
that was burned before it existed.

The copy is upward and cannot overlap: the payload sits just above
`$0200` and the destination starts at `$A000`, so a 21 KB image occupies
`$0220-$5620` on the way in. ROMEN goes off *before* the jump, because
BASIC's last bytes are above `$F000` and would otherwise be read out of
the boot ROM rather than out of themselves.
"""

import argparse
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# The stub, with its three constants filled in. Generated rather than
# committed for the same reason sim/build/boot.hex is: it is derived
# from the image it carries, and a stale copy would be a loader that
# moves the wrong number of bytes.
STUB = """
; Generated by tools/mkboot.py -- do not edit.
;
; Autoboot has just loaded this whole file to $0200 and jumped here.
; Move the payload up to where it was linked, drop the ROM overlay, and
; go. SP is left where sw/boot.asm put it: the stack grows down from
; $0200 and this code runs upward from it, so they do not meet.

        .org  $@ORG@

SYSCTRL = $FE00

reloc:  LDW  X,#src
        LDW  Y,#$@DEST@
        MOV  R2,#$@LO@          ; @SIZE@ bytes
        MOV  R3,#$@HI@

        ; The autoboot loop's own shape (sw/boot.asm .ab4): test the
        ; 16-bit count against zero as two bytes, and carry the borrow
        ; into the high one by hand.
.cp:    MOV  R0,R2
        OR   R0,R3
        BEQ  .go
        LD   R0,[X]
        ST   [Y],R0
        INCW X
        INCW Y
        SUB  R2,#1
        BCS  .cp
        SUB  R3,#1
        BRA  .cp

        ; ROMEN is bit 0 and every other bit reads 0, so this clears the
        ; overlay and nothing else. It has to happen before the jump:
        ; the image runs past $F000, and those bytes are only its own
        ; once the ROM stops answering for them.
.go:    CLR  R0
        ST   [SYSCTRL],R0
        LDW  X,#$@DEST@
        JMP  [X]

src:
"""


def build(payload, dest=0xA000, org=0x0200, build_dir=None):
    """The stub for `payload`, assembled, with the payload after it."""
    build_dir = build_dir or os.path.join(ROOT, "sim", "build")
    os.makedirs(build_dir, exist_ok=True)

    text = (STUB.replace("@ORG@", "%04X" % org)
                .replace("@DEST@", "%04X" % dest)
                .replace("@LO@", "%02X" % (len(payload) & 0xFF))
                .replace("@HI@", "%02X" % (len(payload) >> 8))
                .replace("@SIZE@", "%d" % len(payload)))
    apath = os.path.join(build_dir, "bootstub.asm")
    with open(apath, "w") as fh:
        fh.write(text)

    out = os.path.join(build_dir, "bootstub.bin")
    r = subprocess.run([sys.executable, os.path.join(HERE, "cool8asm.py"),
                        apath, "-o", out, "-I", os.path.join(ROOT, "sw")],
                       capture_output=True, text=True)
    if r.returncode != 0:
        sys.stderr.write(r.stdout + r.stderr)
        raise SystemExit("the boot stub would not assemble")
    with open(out, "rb") as fh:
        stub = fh.read()

    end = dest + len(payload)
    if org + len(stub) + len(payload) > dest:
        raise SystemExit("the payload would land on its own destination")
    if end > 0x10000:
        raise SystemExit("the image does not fit below $10000")
    return stub + payload


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("image", help="the linked system image, e.g. basic.bin")
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument("--dest", type=lambda s: int(s, 0), default=0xA000,
                    help="where the image was linked (default $A000)")
    args = ap.parse_args()

    with open(args.image, "rb") as fh:
        payload = fh.read()
    out = build(payload, dest=args.dest)
    with open(args.output, "wb") as fh:
        fh.write(out)
    print("%s: %d bytes of stub + %d of image -> %s"
          % (os.path.basename(args.image), len(out) - len(payload),
             len(payload), args.output))
    return 0


if __name__ == "__main__":
    sys.exit(main())
