#!/usr/bin/env python3
"""Wrap a system image in the stub that puts it where it belongs.

    python tools/mkboot.py sim/build/basic.bin -o sim/build/BOOT.BIN

The boot ROM's autoboot loads `BOOT.BIN` to `$0200` and jumps to it.
BASIC links at `$A000`, because program text grows up from `$0200` and
the screen is at `$8000`, so the two addresses cannot both be right.
Something has to move the image after it is loaded.

**The stub does it, and not the ROM.** Teaching autoboot to read a load
address out of a header would be a dozen bytes in a 4 KB ROM that has 36
free -- and it is the one part of the machine that cannot be reflashed
if it turns out to be wrong. A stub costs nothing anybody else has to
live with, and a file that carries its own relocation works on a ROM
that was burned before it existed.

The copy is upward and cannot overlap: the payload sits just above
`$0200` and the destination starts at `$A000`, so a 21 KB image occupies
`$0220-$5620` on the way in. ROMEN goes off *before* the jump, because
BASIC's last bytes are above `$F000` and would otherwise be read out of
the boot ROM rather than out of themselves.
"""

import argparse
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

sys.path.insert(0, HERE)

import ioregs                                              # noqa: E402
import memmap                                              # noqa: E402

# The stub, with its three constants filled in. Generated rather than
# committed for the same reason sim/build/boot.hex is: it is derived
# from the image it carries, and a stale copy would be a loader that
# moves the wrong number of bytes.
STUB = """
; Generated by tools/mkboot.py -- do not edit.
;
; Autoboot has just loaded this whole file to $0200 and jumped here.
; Move the payload up to where it was linked, drop the ROM overlay, and
; go. SP is left where sw/boot.asm put it: the stack grows down from
; $0200 and this code runs upward from it, so they do not meet.

        .org  $@ORG@

SYSCTRL = $@SYSCTRL@

reloc:  LDW  X,#src
        LDW  Y,#$@DEST@
        MOV  R2,#$@LO@          ; @SIZE@ bytes
        MOV  R3,#$@HI@

        ; The autoboot loop's own shape (sw/boot.asm .ab4): test the
        ; 16-bit count against zero as two bytes, and carry the borrow
        ; into the high one by hand.
.cp:    MOV  R0,R2
        OR   R0,R3
        BEQ  .go
        LD   R0,[X]
        ST   [Y],R0
        INCW X
        INCW Y
        SUB  R2,#1
        BCS  .cp
        SUB  R3,#1
        BRA  .cp

        ; ROMEN is bit 0 and every other bit reads 0, so this clears the
        ; overlay and nothing else. It has to happen before the jump:
        ; the image runs past $F000, and those bytes are only its own
        ; once the ROM stops answering for them.
.go:    CLR  R0
        ST   [SYSCTRL],R0

        ; ------------------------------------------------- the dressing
        ; One-shot initialisation that costs ZERO resident bytes: this
        ; stub lives at $0200 in user RAM and the first line typed into
        ; the editor is stored on top of it. So the default palettes and
        ; the startup chime live here, run once, and are reclaimed --
        ; the machine's whole make-up ritual in memory it gives back.

        ; palette bank 0: the editor's sixteen, CGA slot meanings kept
        ; so attribute nibbles stay true, values softened. Bank 1: the
        ; Pico-8 sixteen, quantised to RGB444 -- a designed game
        ; palette for sprites and tiles to point at.
        CLR  R0
        ST   [$FF1E],R0
        LDW  X,#paltab
        MOV  R2,#64
.pl:    LD   R0,[X]
        ST   [$FF1F],R0
        INCW X
        SUB  R2,#1
        BNE  .pl

        ; the boot screen. It lives here, not in the image: 400-odd
        ; bytes of text and painting that run once and are reclaimed.
        ; The free count is computed by mkboot.py at build time -- the
        ; machine is empty at this moment by definition. The boot ROM
        ; already has mode 0 up with the base at $8000.
        ;
        ; The ROM also left ITS cursor enabled, parked wherever its
        ; monitor last put it. Off, before anything is painted: BASIC
        ; turns it back on at the end of init, already in place.
        CLR  R0
        ST   [$FF24],R0
        LDW  Y,#@SCREEN@        ; clear: char 32, attr $07 -- 2560
        CLR  R2                 ; **CELLS, two bytes each.** 160 bytes a
        MOV  R3,#$0A            ;   row for 32 rows is 5120 bytes, which
                                ;   is $0A00 cells -- not $1400. Counting
                                ;   bytes here cleared twice the map and
                                ;   ran straight over the image above it,
                                ;   which reads as a relocation that
                                ;   never happened.
                                ; relocated image with it
.sc:    MOV  R0,#$20
        ST   [Y],R0
        INCW Y
        MOV  R0,#$07
        ST   [Y],R0
        INCW Y
        SUB  R2,#1
        BCS  .sc
        SUB  R3,#1
        BNE  .sc

        LDW  X,#btext           ; rows of: row, attr, text, 0
.bl:    LD   R0,[X]
        CMP  R0,#$FF
        BEQ  .bdone
        ; Row base: $8000 + row * CSTRIDE. **This was `+ $80` into the
        ; high byte**, which is row * 256 and was right for exactly as
        ; long as the map had a 256-byte row. 160 is 5 * 32 and 5r fits
        ; in a byte for r < 32, so the product is `q = 5r` then `q << 5`
        ; -- high `q >> 3`, low `(q AND 7) << 5`, the same three adds
        ; and shift sw/console.asm's con_row does.
        MOV  R1,R0
        ADD  R0,R0
        ADD  R0,R0
        ADD  R0,R1              ; q = 5r
        MOV  R1,R0
        AND  R1,#7
        ADD  R1,R1
        ADD  R1,R1
        ADD  R1,R1
        ADD  R1,R1
        ADD  R1,R1              ; (q AND 7) << 5
        SHR  R0
        SHR  R0
        SHR  R0                 ; q >> 3
        ADD  R0,#@SCRPAGE@      ; + >CSCRN
        MOV  YH,R0
        MOV  YL,R1
        INCW X
        LD   R1,[X]             ; the line's attribute
        INCW X
.bc:    LD   R0,[X]
        TST  R0
        BEQ  .bnl
        ST   [Y],R0
        INCW Y
        MOV  R0,R1
        ST   [Y],R0
        INCW Y
        INCW X
        BRA  .bc
.bnl:   INCW X
        BRA  .bl
.bdone:

        ; GTEXT's font: 96 glyphs of 8x8, 1 bpp, seeded into VRAM at
        ; $FC00 through the port. VRAM is RAM: it survives every mode
        ; switch, so this happens once, here, in reclaimed memory.
        MOV  R0,#1
        ST   [$FF28],R0
        CLR  R0
        ST   [$FF26],R0
        MOV  R0,#$FC
        ST   [$FF27],R0
        LDW  X,#font8
        CLR  R2                 ; 768 bytes, the autoboot count idiom
        MOV  R3,#3
.fc:    MOV  R0,R2
        OR   R0,R3
        BEQ  .fdone
        LD   R0,[X]
        ST   [$FF29],R0
        INCW X
        SUB  R2,#1
        BCS  .fc
        SUB  R3,#1
        BRA  .fc
.fdone:
        ; ...and the same 96 glyphs at 8x16, verbatim from the face the
        ; text modes read out of their ROM, seeded below the 8x8 set at
        ; $F600. Mode 3's console blits these: its cells are 16 raster
        ; lines with no doubling, and this is what fills them at text
        ; mode's own quality. The step register still holds 1.
        CLR  R0
        ST   [$FF26],R0
        MOV  R0,#$F6
        ST   [$FF27],R0
        LDW  X,#font16
        CLR  R2                 ; 1536 bytes
        MOV  R3,#6
.gc:    MOV  R0,R2
        OR   R0,R3
        BEQ  .gdone
        LD   R0,[X]
        ST   [$FF29],R0
        INCW X
        SUB  R2,#1
        BCS  .gc
        SUB  R3,#1
        BRA  .gc
.gdone:
        LDW  X,#$@DEST@
        JMP  [X]

font8:
@FONT@

font16:
@FONT16@

paltab: ; bank 0 -- softened CGA, semantics preserved
        .byte $00,$00, $01,$2B, $01,$A4, $02,$AB
        .byte $0B,$32, $0A,$3A, $0B,$72, $0B,$BC
        .byte $05,$56, $05,$9F, $06,$E7, $07,$EE
        .byte $0F,$66, $0E,$7E, $0F,$D5, $0F,$FF
        ; bank 1 -- Pico-8, quantised to RGB444
        .byte $00,$00, $01,$23, $07,$25, $00,$85
        .byte $0A,$53, $05,$55, $0C,$CC, $0F,$FE
        .byte $0F,$04, $0F,$A0, $0F,$E2, $00,$E3
        .byte $02,$AF, $08,$79, $0F,$7A, $0F,$CA

btext:
@BANNER@
        .byte $FF

src:
"""

# The boot screen's text. The free count is a build-time constant --
# a freshly booted machine holds nothing -- but **not a written-down
# one**: it said `$7EDF - $0200`, which was the user area before the
# console and main.asm claimed storage under it, and it would have gone
# on advertising 313 bytes that a program cannot have. It comes from
# the same computed floor the assembler gets ([D67]).
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import memmap                                            # noqa: E402

FREE = memmap.usertop() - 0x0200 + 1

# BASIC's version, and the only place it is written down. The banner is
# the machine's own statement of what it is running, so tests that want
# to name the version import this rather than repeating the string.
VERSION = "1.2"

BANNER = [
    (1, 0x0B, "    COOL8"),
    (2, 0x0F, "    8-bit home computer"),
    (4, 0x08, "    CPU     COOL8 @ 8.375 MHz        RAM    64K main, 64K video"),
    (5, 0x08, "    VIDEO   640x480, 32 sprites      SOUND  8 voices, 1-bit DAC"),
    (7, 0x0E, f"COOLBASIC {VERSION}"),
    (8, 0x07, f"{FREE} BYTES FREE"),
]


def _banner():
    lines = []
    for row, attr, text in BANNER:
        lines.append(f"        .byte {row}, ${attr:02X}")
        lines.append(f'        .asciz "{text}"')
    return "\n".join(lines)


def _font8():
    """96 glyphs of 8x8, 1 bpp, from the bitstream's own 8x16 font --
    the same face, so GTEXT matches the editor.

    The resample leans on measured Spleen geometry rather than
    arithmetic: caps sit on rows 2-11 with the baseline at 11, and the
    ten rows are bars joined by *duplicate* body rows -- B is bar,
    three identical rows, bar, four identical rows, bar. So rows 4, 7
    and 9 are dropped, never merged, and every feature row -- cap top,
    crossbars, baseline -- lands in the cell verbatim. Naive schemes
    fail here precisely because they merge: OR-ing distinct rows
    mangles the letter tops, and fixed-step sampling missed the
    baseline entirely. A glyph that does ink a dropped row uniquely
    (no cap does; some punctuation) keeps it by an OR into the kept
    row below. Rows 12-14 -- the descenders -- compress into cell
    row 7, so g, j, p, q and y keep their tails below the baseline.

    (Spleen's own 5x8 was tried instead: honest pixels, but 4-wide
    letters swim in an 8-wide cell. Chunky beat authentic.)"""
    import mkfont
    img, _, _ = mkfont.build(
        os.path.join(ROOT, "assets", "font", "spleen-8x16.bdf"))
    keep = (2, 3, 5, 6, 8, 10, 11)
    out = bytearray()
    for ch in range(32, 128):
        cell = img[ch * 16:(ch + 1) * 16]
        rows8 = [cell[r] for r in keep]
        for r in (4, 7, 9):
            if cell[r] and cell[r] != cell[r - 1] and cell[r] != cell[r + 1]:
                rows8[keep.index(r + 1)] |= cell[r]
        rows8.append(cell[12] | cell[13] | cell[14])
        out += bytes(rows8)
    # Hand fix-ups where the row-drop merges features the eye needs
    # apart: the dotted glyphs lose the gap between dot and stem.
    for ch, rows in (("i", (0x00, 0x30, 0x00, 0x70, 0x30, 0x30,
                            0x78, 0x00)),
                     ("j", (0x00, 0x0C, 0x00, 0x0C, 0x0C, 0x0C,
                            0xCC, 0x78))):
        o = (ord(ch) - 32) * 8
        out[o:o + 8] = bytes(rows)
    lines = []
    for i in range(0, len(out), 16):
        row = ",".join("$%02X" % b for b in out[i:i + 16])
        lines.append("        .byte " + row)
    return "\n".join(lines)


def _font16():
    """96 glyphs of 8x16, 1 bpp, verbatim from the bitstream's font —
    no resampling at all: mode 3's console shows the exact pixels text
    mode does."""
    import mkfont
    img, _, _ = mkfont.build(
        os.path.join(ROOT, "assets", "font", "spleen-8x16.bdf"))
    out = bytes(img[32 * 16:128 * 16])
    lines = []
    for i in range(0, len(out), 16):
        row = ",".join("$%02X" % b for b in out[i:i + 16])
        lines.append("        .byte " + row)
    return "\n".join(lines)


def build(payload, dest=None, org=0x0200, build_dir=None):
    """The stub for `payload`, assembled, with the payload after it.

    `dest` defaults to `memmap.ORG`, which is derived from the image's
    size ([D69]). **It used to default to $A000**, and tools/flash.py
    passed that explicitly -- so `poe disk` built the image `poe emu`
    boots with the stub relocating to an address the image was not
    linked for. Every suite passed, because sim/build_basic.py had
    already been changed to pass ORG, and only the emulator ran garbage.
    """
    dest = memmap.ORG if dest is None else dest
    build_dir = build_dir or os.path.join(ROOT, "sim", "build")
    os.makedirs(build_dir, exist_ok=True)

    text = (STUB.replace("@FONT@", _font8())
                .replace("@FONT16@", _font16())
                .replace("@BANNER@", _banner())
                # **The map's address, not a written-down $A000.** The
                # stub clears the screen and paints the banner, and it
                # carried the address twice -- so moving the map left a
                # machine that booted from flash to an uncleared screen
                # with no banner, and the first line typed landed on
                # whatever was there. The fifth place this number lived.
                .replace("@SCREEN@", "$%04X" % memmap.SCREEN)
                .replace("@SCRPAGE@", "$%02X" % (memmap.SCREEN >> 8))
                .replace("@ORG@", "%04X" % org)
                .replace("@DEST@", "%04X" % dest)
                .replace("@LO@", "%02X" % (len(payload) & 0xFF))
                .replace("@HI@", "%02X" % (len(payload) >> 8))
                .replace("@SIZE@", "%d" % len(payload))
                # The stub is assembled standalone, with no sw/ on the
                # include path, so it cannot reach sw/io.asm -- but it
                # must not carry a literal either. Substituted from the
                # one source, like every other number in this template.
                .replace("@SYSCTRL@", "%04X" % ioregs.addr_of("SYS_CTRL")))
    apath = os.path.join(build_dir, "bootstub.asm")
    with open(apath, "w") as fh:
        fh.write(text)

    out = os.path.join(build_dir, "bootstub.bin")
    r = subprocess.run([sys.executable, os.path.join(HERE, "cool8asm.py"),
                        apath, "-o", out, "-I", os.path.join(ROOT, "sw")],
                       capture_output=True, text=True)
    if r.returncode != 0:
        sys.stderr.write(r.stdout + r.stderr)
        raise SystemExit("the boot stub would not assemble")
    with open(out, "rb") as fh:
        stub = fh.read()

    end = dest + len(payload)
    # **The image is top-aligned, so it must end at the I/O page.** Any
    # other `dest` means the stub is relocating to an address the image
    # was not linked for -- which is not a crash, it is a machine that
    # boots and then executes the middle of a routine. tools/flash.py
    # passed a written-down $A000 for exactly one build after [D69] made
    # the origin derived, and every suite passed while `poe emu` ran
    # garbage, because only that one path was not covered.
    if end != memmap.TOP:
        raise SystemExit(
            "the stub would relocate to $%04X, and a %d-byte image linked "
            "there ends at $%04X rather than $%04X. The origin is derived "
            "(memmap.ORG = $%04X) -- pass that, or nothing."
            % (dest, len(payload), end - 1, memmap.TOP - 1, memmap.ORG))
    if org + len(stub) + len(payload) > dest:
        raise SystemExit("the payload would land on its own destination")
    if end > memmap.TOP:
        # The relocation would write into the I/O page — poking random
        # registers on the way — and the lost tail is the high code:
        # the blitter, the filesystem, the ISR. That failure presents
        # as an editor that half works, not as a build error, which is
        # how a 7-bytes-over image cost a debugging round once.
        raise SystemExit("the image is %d bytes over the I/O page"
                         % (end - memmap.TOP))
    if end > 0x10000:
        raise SystemExit("the image does not fit below $10000")
    return stub + payload


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("image", help="the linked system image, e.g. basic.bin")
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument("--dest", type=lambda s: int(s, 0), default=memmap.ORG,
                    help="where the image was linked (default $A000)")
    args = ap.parse_args()

    with open(args.image, "rb") as fh:
        payload = fh.read()
    out = build(payload, dest=args.dest)
    with open(args.output, "wb") as fh:
        fh.write(out)
    print("%s: %d bytes of stub + %d of image -> %s"
          % (os.path.basename(args.image), len(out) - len(payload),
             len(payload), args.output))
    return 0


if __name__ == "__main__":
    sys.exit(main())
