#!/usr/bin/env python3
"""Emit rust/src/optab.rs from tools/opcodes.py.

The Rust fast runner (see RUST_PORT.md) must not carry its own copy of
the encoding tables — that is the second-mnemonic-table trap AGENTS.md
warns about. Everything tabular the Rust core needs — cycle costs per
encoding, the page-2 assigned/reserved split, the interrupt entry cost —
is generated here from opcodes.py, the single source of truth. The
hand-written Rust states semantics only, and sim/rustsim.py holds those
to the emulator's trace, instruction by instruction.

`--check` regenerates and compares without writing — the same drift gate
asic/tt/prepare.py --check gives the TinyTapeout copy of the RTL.

    python tools/mkrsopc.py            # (re)write rust/src/optab.rs
    python tools/mkrsopc.py --check    # report drift, write nothing
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

import opcodes  # noqa: E402

OUT = os.path.join(ROOT, "rust", "src", "optab.rs")


def _array(name, ty, values, per_line, fmt):
    lines = [f"pub const {name}: [{ty}; 256] = ["]
    for i in range(0, 256, per_line):
        row = ", ".join(fmt(v) for v in values[i:i + per_line])
        lines.append(f"    {row},")
    lines.append("];")
    return "\n".join(lines)


def generate():
    cyc, cyc_taken = [], []
    for op in range(256):
        c = opcodes.cycles(op)
        if isinstance(c, tuple):
            cyc.append(c[0])
            cyc_taken.append(c[1])
        else:
            cyc.append(c)
            cyc_taken.append(c)

    p2_cyc = [opcodes.cycles(0x2F, op2 if op2 in opcodes.page2 else None)
              for op2 in range(256)]
    p2_have = [op2 in opcodes.page2 for op2 in range(256)]

    parts = [
        "// GENERATED by tools/mkrsopc.py from tools/opcodes.py."
        " Do not edit;",
        "// regenerate after any change to the encoding, and `--check`"
        " gates drift.",
        "",
        "/// Clocks for a hardware interrupt entry: three pushes and two"
        " vector reads.",
        f"pub const INTERRUPT_CYCLES: u64 = {opcodes.INTERRUPT_CYCLES};",
        "",
        "/// Primary-page cycle cost. Conditional branches ($70-$7F) hold"
        " the",
        "/// not-taken cost; BRK's entry cost is included.",
        _array("CYCLES", "u8", cyc, 16, str),
        "",
        "/// Taken cost for conditional branches; equal to CYCLES"
        " everywhere else.",
        _array("CYCLES_TAKEN", "u8", cyc_taken, 16, str),
        "",
        "/// Page-2 total cost including the $2F escape. Reserved"
        " encodings carry",
        "/// the full BRK-trap cost, entry included.",
        _array("P2_CYCLES", "u8", p2_cyc, 16, str),
        "",
        "/// Whether a page-2 encoding is assigned; a reserved one traps"
        " to the",
        "/// BRK vector.",
        _array("P2_ASSIGNED", "bool", p2_have, 8,
               lambda v: "true" if v else "false"),
        "",
    ]
    return "\n".join(parts)


def main():
    text = generate()
    have = None
    if os.path.exists(OUT):
        with open(OUT, encoding="utf-8") as fh:
            have = fh.read()

    if "--check" in sys.argv:
        if have == text:
            print("rust/src/optab.rs is up to date")
            return 0
        print("rust/src/optab.rs is out of date; run "
              "python tools/mkrsopc.py")
        return 1

    if have == text:
        print("rust/src/optab.rs unchanged")
        return 0
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print("wrote rust/src/optab.rs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
