#!/usr/bin/env python3
"""Emit rust/src/optab.rs from tools/opcodes.py.

The Rust fast runner (see RUST_PORT.md) must not carry its own copy of
the encoding tables — that is the second-mnemonic-table trap AGENTS.md
warns about. Everything tabular the Rust core needs — cycle costs per
encoding, the page-2 assigned/reserved split, the interrupt entry cost —
is generated here from opcodes.py, the single source of truth. The
hand-written Rust states semantics only, and sim/cosim.py holds those
to the emulator's trace, instruction by instruction.

`--check` regenerates and compares without writing — the same drift gate
asic/tt/prepare.py --check gives the TinyTapeout copy of the RTL.

    python tools/mkrsopc.py            # (re)write rust/src/optab.rs
    python tools/mkrsopc.py --check    # report drift, write nothing
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

import opcodes  # noqa: E402
import cool8asm  # noqa: E402

OUT = os.path.join(ROOT, "rust", "src", "optab.rs")


def _rs_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _encodings():
    """The assembler's signature table, as cool8asm.TABLE holds it.

    The CoolAction! compiler (rust/src/action/) carries an assembler so
    the browser build can go from source to bytes with no Python. It
    must not carry a mnemonic table of its own -- the first draft did,
    and got PUSH, LD [SP+u8], MUL and LDW all wrong -- so the table is
    this one, rendered: the same signatures cool8asm normalises a
    source line to, with the opcode, page-2 byte and operand kind. The
    Rust side re-implements only the normalisation (logic, not data)
    and sim/test_action.py checks the two assemblers produce identical
    bytes from the compiler's own output.
    """
    rows = []
    for (mnem, canon), (op, op2, kind) in sorted(cool8asm.TABLE.items()):
        sig = mnem + (" " + ",".join(canon) if canon else "")
        rows.append((sig, op, op2, kind))
    return rows


def _aliases():
    """cool8asm.ALIASES, each evaluated on a placeholder operand so the
    rewrite can be carried as text: (alias, mnemonic, operands with
    {0} where the operand goes)."""
    rows = []
    for (name, n), fn in sorted(cool8asm.ALIASES.items()):
        assert n == 1
        mnem, ops = fn("{0}")
        rows.append((name, mnem, ops))
    return rows


def _array(name, ty, values, per_line, fmt):
    lines = [f"pub const {name}: [{ty}; 256] = ["]
    for i in range(0, 256, per_line):
        row = ", ".join(fmt(v) for v in values[i:i + per_line])
        lines.append(f"    {row},")
    lines.append("];")
    return "\n".join(lines)


def generate():
    cyc, cyc_taken = [], []
    for op in range(256):
        c = opcodes.cycles(op)
        if isinstance(c, tuple):
            cyc.append(c[0])
            cyc_taken.append(c[1])
        else:
            cyc.append(c)
            cyc_taken.append(c)

    p2_cyc = [opcodes.cycles(0x2F, op2 if op2 in opcodes.page2 else None)
              for op2 in range(256)]
    p2_have = [op2 in opcodes.page2 for op2 in range(256)]

    parts = [
        "// GENERATED by tools/mkrsopc.py from tools/opcodes.py."
        " Do not edit;",
        "// regenerate after any change to the encoding, and `--check`"
        " gates drift.",
        "",
        "/// Clocks for a hardware interrupt entry: three pushes and two"
        " vector reads.",
        f"pub const INTERRUPT_CYCLES: u64 = {opcodes.INTERRUPT_CYCLES};",
        "",
        "/// Primary-page cycle cost. Conditional branches ($70-$7F) hold"
        " the",
        "/// not-taken cost; BRK's entry cost is included.",
        _array("CYCLES", "u8", cyc, 16, str),
        "",
        "/// Taken cost for conditional branches; equal to CYCLES"
        " everywhere else.",
        _array("CYCLES_TAKEN", "u8", cyc_taken, 16, str),
        "",
        "/// Page-2 total cost including the $2F escape. Reserved"
        " encodings carry",
        "/// the full BRK-trap cost, entry included.",
        _array("P2_CYCLES", "u8", p2_cyc, 16, str),
        "",
        "/// Whether a page-2 encoding is assigned; a reserved one traps"
        " to the",
        "/// BRK vector.",
        _array("P2_ASSIGNED", "bool", p2_have, 8,
               lambda v: "true" if v else "false"),
        "",
        "/// Operand kinds, as tools/opcodes.py numbers them.",
        "pub const K_NONE: u8 = %d;" % opcodes.NONE,
        "pub const K_IMM8: u8 = %d;" % opcodes.IMM8,
        "pub const K_MASK8: u8 = %d;" % opcodes.MASK8,
        "pub const K_DISP8: u8 = %d;" % opcodes.DISP8,
        "pub const K_U8: u8 = %d;" % opcodes.U8,
        "pub const K_REL8: u8 = %d;" % opcodes.REL8,
        "pub const K_ABS16: u8 = %d;" % opcodes.ABS16,
        "pub const K_IMM16: u8 = %d;" % opcodes.IMM16,
        "",
        "/// Bytes that follow the opcode, by operand kind.",
        "pub const EXTRA: [u8; 8] = [%s];" % ", ".join(
            str(opcodes.EXTRA[k]) for k in range(8)),
        "",
        "/// The condition codes in encoding order; a branch's inverse is",
        "/// its index with the bottom bit flipped.",
        "pub const COND: [&str; 16] = [%s];" % ", ".join(
            _rs_str(c) for c in opcodes.COND),
        "",
        "/// One assemblable signature: the canonical text tools/cool8asm.py",
        "/// normalises a source line to, the opcode, the page-2 byte if",
        "/// any, and the operand kind.",
        "pub struct Enc {",
        "    pub sig: &'static str,",
        "    pub op: u8,",
        "    pub op2: Option<u8>,",
        "    pub kind: u8,",
        "}",
        "",
        "/// Every encoding the assembler accepts, as cool8asm.TABLE.",
        "pub const ENCODINGS: &[Enc] = &[",
    ]
    for sig, op, op2, kind in _encodings():
        o2 = "None" if op2 is None else "Some(0x%02X)" % op2
        parts.append("    Enc { sig: %s, op: 0x%02X, op2: %s, kind: %d },"
                     % (_rs_str(sig), op, o2, kind))
    parts += [
        "];",
        "",
        "/// Assembler aliases (docs/08-assembler.md section 2.6): alias,",
        "/// the mnemonic it rewrites to, and its operands with {0} where",
        "/// the alias's one operand goes.",
        "pub const ALIASES: &[(&str, &str, &str)] = &[",
    ]
    for name, mnem, ops in _aliases():
        parts.append("    (%s, %s, %s)," % (_rs_str(name), _rs_str(mnem),
                                            _rs_str(ops)))
    parts += ["];", ""]
    return "\n".join(parts)


def main():
    text = generate()
    have = None
    if os.path.exists(OUT):
        with open(OUT, encoding="utf-8") as fh:
            have = fh.read()

    if "--check" in sys.argv:
        if have == text:
            print("rust/src/optab.rs is up to date")
            return 0
        print("rust/src/optab.rs is out of date; run "
              "python tools/mkrsopc.py")
        return 1

    if have == text:
        print("rust/src/optab.rs unchanged")
        return 0
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print("wrote rust/src/optab.rs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
