#!/usr/bin/env python3
"""The default palette, and the only place its colours are written down.

    python tools/palette.py            # (re)write both generated copies
    python tools/palette.py --check    # report drift, write nothing

## Why this exists

The palette block RAM comes up zeroed from the bitstream -- 256 entries
of black, **including entry 0, which is the border** -- so a machine
that never writes it shows nothing at all. Until [D77] three different
pieces of software wrote one: the boot ROM's sixteen, the flash stub's
thirty-two, and `sw/console.asm`'s one-entry override for mode 3. Three
copies of "what colour is blue", and the machine was black for the
milliseconds between reset and whichever of them ran.

Now the bitstream carries it. `cool8_pal.v` reads `pal.hex` at
elaboration exactly as `cool8_rom.v` reads `boot.hex`, and the EBR is
allocated either way -- only its INIT bits change. **Measured at 76
logic cells cheaper**, reproducibly, at 98 % occupancy where that
matters. `pal.hex` is staged into the run directory by `stage()` below
and is not committed, for the same reason `font.hex` and `boot.hex` are
not: it is derived.

The emulator has to agree or the two models draw different colours, and
every suite that compares them would still pass because they would be
consistent with each other -- the failure [D74] is about. So this emits
`rust/src/pal.rs` too, and `poe check` fails on drift in either.

## The format

Twelve bits, `RRRRGGGGBBBB`. The hardware takes an entry as two writes
of `PAL_DATA` -- `0000RRRR` then `GGGGBBBB` -- but that is the port's
shape, not the colour's.

## The banks

256 entries is not one palette. In the tile mode the attribute's low
nibble picks a **bank of sixteen**, so the table is sixteen palettes,
and a bank is the unit that gets designed. Modes 0, 1, 4 and 5 use bank
0; mode 3 reaches only entries 0 and 1; mode 6 is the only one that
sees all 256 at once.
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RS = os.path.join(ROOT, "rust", "src", "pal.rs")

# ---------------------------------------------------------------------
# Bank 0 -- softened CGA, and the slot meanings are load-bearing.
#
# A text cell's attribute is `bg[7:4] fg[3:0]`, so entry 4 must be the
# red a program means when it writes 4. The values are softened from the
# hard 0/A/5/F levels the boot ROM used, which read as harsh on a
# modern display; the *meanings* are CGA's exactly.
# ---------------------------------------------------------------------
BANK0 = [
    0x000, 0x12B, 0x1A4, 0x2AB, 0xB32, 0xA3A, 0xB72, 0xBBC,
    0x556, 0x59F, 0x6E7, 0x7EE, 0xF66, 0xE7E, 0xFD5, 0xFFF,
]

# ---------------------------------------------------------------------
# Bank 1 -- PICO-8, quantised to RGB444. A designed game palette with
# ramps that hold together at sixteen colours, which is what a tile or
# sprite bank wants and what CGA's slot semantics prevent bank 0 from
# being.
# ---------------------------------------------------------------------
BANK1 = [
    0x000, 0x123, 0x725, 0x085, 0xA53, 0x555, 0xCCC, 0xFFE,
    0xF04, 0xFA0, 0xFE2, 0x0E3, 0x2AF, 0x879, 0xF7A, 0xFCA,
]

BANKS = [BANK0, BANK1]


def table():
    """All 256 entries, banks first and black for the rest."""
    out = []
    for b in BANKS:
        assert len(b) == 16, "a bank is sixteen entries"
        out += b
    return out + [0x000] * (256 - len(out))


def hex_text():
    return "".join("%03x\n" % e for e in table())


def rs_text():
    t = table()
    rows = []
    for i in range(0, 256, 8):
        rows.append("    " + " ".join("0x%03X," % e for e in t[i:i + 8]))
    return (
        "// pal.rs -- GENERATED by tools/palette.py. Do not edit.\n"
        "//\n"
        "// The same 256 entries rtl/soc/pal.hex carries, because the\n"
        "// emulator's display and the hardware's must agree: two models\n"
        "// gated against each other catch a disagreement and cannot\n"
        "// catch a shared assumption ([D74]). `poe check` fails on drift.\n"
        "\n"
        "pub const DEFAULT: [u16; 256] = [\n" + "\n".join(rows) + "\n];\n")


def stage(build_dir):
    """Write `pal.hex` where yosys or vvp will resolve it.

    **Not committed, and not in rtl/.** `cool8_pal.v` reads it at
    elaboration from the working directory, exactly as `cool8_rom.v`
    reads `boot.hex` and the pixel stage reads `font.hex` -- so like
    those two it is built into the run directory by whoever is about to
    elaborate. Written here rather than by each of them so the colours
    live in one file.
    """
    with open(os.path.join(build_dir, "pal.hex"), "w", newline=chr(10)) as fh:
        fh.write(hex_text())


def main():
    want = {RS: rs_text()}
    if "--check" in sys.argv:
        bad = []
        for path, text in want.items():
            got = ""
            if os.path.exists(path):
                with open(path, encoding="utf-8") as fh:
                    got = fh.read()
            if got != text:
                bad.append("%s is stale -- run python tools/palette.py"
                           % os.path.relpath(path, ROOT))
        for b in bad:
            print("  DRIFT:", b)
        if not bad:
            print("  the palette agrees: %d entries, %d designed banks"
                  % (len(table()), len(BANKS)))
        return 1 if bad else 0
    for path, text in want.items():
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        print("  wrote", os.path.relpath(path, ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
