10 REM ============================================
11 REM THE HITCHHIKER'S GUIDE TO THE GALAXY
12 REM INFOCOM INTERACTIVE FICTION (1984)
13 REM DOUGLAS ADAMS & STEVE MERETZKY
14 REM NATIVE COOL8 Z-MACHINE V3 INTERPRETER
15 REM ============================================
20 DRIVE 14 : MODE 0 : COLOR 15, 1 : CLS
30 SYS "HHGG.BIN"
