10 REM ============================================
11 REM LEATHER GODDESSES OF PHOBOS
12 REM INFOCOM INTERACTIVE FICTION (1986)
13 REM STEVE MERETZKY
14 REM NATIVE COOL8 Z-MACHINE V3 INTERPRETER
15 REM ============================================
20 DRIVE 14 : MODE 0 : COLOR 7, 8 : CLS
30 SYS "LGOP.BIN"
