10 REM ============================================
11 REM ZORK I: THE GREAT UNDERGROUND EMPIRE
12 REM INFOCOM INTERACTIVE FICTION (1980)
13 REM TIM ANDERSON, MARC BLANK, BRUCE DANIELS, DAVE LEBLING
14 REM NATIVE COOL8 Z-MACHINE V3 INTERPRETER
15 REM ============================================
20 DRIVE 14 : MODE 0 : COLOR 14, 0 : CLS
30 SYS "ZORK1.BIN"
